// Icon inventory: semantic key -> lucide@1.48.0 canonical name or custom geometry (AWR-15 §7.6 groups A-N; d03 §4.1).
// Source of apps/web/src/ui/icons/{registry,whitelist}.ts (tools/shadcn/icons/gen-registry.mjs). The registry is the
// only source of truth for the icon count (ADR-030 second round); verify.mjs checks canonical names and morph plans.
// Row: [group, key, name, partner, mode, spring] where mode is 'morph' (whitelisted pair), 'swap' (explicit swap
// partner), 'rot' (continuous angle, CSS rotate) or null. AWR-15 §7.6 lists cmd.search twice (A: Search for the
// command palette, E: ScanSearch for the search mission); the E row is registered as cmd.search-area.
export const INVENTORY = [
  ['A', 'nav.world', 'Earth', null, null, null],
  ['A', 'nav.layers', 'Layers', null, null, null],
  ['A', 'nav.environment', 'CloudSunRain', null, null, null],
  ['A', 'nav.fleet', 'Drone', null, null, null],
  ['A', 'nav.mission', 'Route', null, null, null],
  ['A', 'nav.agents', 'Bot', null, null, null],
  ['A', 'nav.data', 'Database', null, null, null],
  ['A', 'nav.perf', 'Gauge', null, null, null],
  ['A', 'nav.settings', 'Settings', null, null, null],
  ['A', 'nav.menu', 'Menu', 'X', 'morph', null],
  ['A', 'panel.left', 'PanelLeftClose', 'PanelLeftOpen', 'morph', null],
  ['A', 'panel.right', 'PanelRightClose', 'PanelRightOpen', 'morph', null],
  ['A', 'panel.bottom', 'PanelBottomClose', 'PanelBottomOpen', 'morph', null],
  ['A', 'cmd.search', 'Search', null, null, null],
  ['A', 'cmd.command', 'Command', null, null, null],
  ['A', 'theme.light', 'Sun', 'Moon', 'morph', 'smooth'],
  ['A', 'theme.dark', 'Moon', 'Sun', 'morph', 'smooth'],
  ['A', 'theme.system', 'Monitor', null, null, null],
  ['A', 'view.fullscreen', 'Maximize', 'Minimize', 'morph', null],
  ['A', 'help', 'CircleQuestionMark', null, null, null],
  ['A', 'shortcuts', 'Keyboard', null, null, null],
  ['A', 'notify', 'Bell', 'BellOff', 'swap', null],
  ['A', 'notify.ring', 'BellRing', null, null, null],
  ['A', 'user', 'CircleUser', null, null, null],
  ['A', 'logout', 'LogOut', null, null, null],
  ['A', 'conn.online', 'Wifi', 'WifiOff', 'morph', null],
  ['B', 'layer.pointcloud', 'custom:PointCloud', null, null, null],
  ['B', 'layer.terrain', 'Mountain', null, null, null],
  ['B', 'layer.building', 'BuildingComplex', null, null, null],
  ['B', 'layer.semantic', 'Tags', null, null, null],
  ['B', 'layer.lidar', 'Radar', null, null, null],
  ['B', 'layer.mesh', 'Box', null, null, null],
  ['B', 'layer.splat', 'Sparkles', null, null, null],
  ['B', 'layer.trajectory', 'Spline', null, null, null],
  ['B', 'layer.occupancy', 'Grid3x3', null, null, null],
  ['B', 'layer.bbox', 'SquareDashed', null, null, null],
  ['B', 'layer.lod', 'custom:OctreeLod', null, null, null],
  ['B', 'layer.visible', 'Eye', 'EyeOff', 'swap', null],
  ['B', 'layer.lock', 'Lock', 'LockOpen', 'morph', null],
  ['B', 'layer.opacity', 'Blend', null, null, null],
  ['B', 'layer.pointsize', 'CircleDot', null, null, null],
  ['B', 'layer.colormode', 'Palette', null, null, null],
  ['B', 'layer.loading', 'LoaderCircle', 'CircleCheck', 'morph', 'smooth'],
  ['B', 'layer.stream', 'CloudDownload', null, null, null],
  ['B', 'tool.measure', 'Ruler', null, null, null],
  ['B', 'tool.clip', 'Scissors', null, null, null],
  ['B', 'tool.slice', 'Slice', null, null, null],
  ['B', 'tool.axis', 'Axis3d', null, null, null],
  ['C', 'env.clear', 'Sun', 'CloudSun', 'morph', 'smooth'],
  ['C', 'env.partly', 'CloudSun', 'Cloud', 'morph', 'smooth'],
  ['C', 'env.cloud', 'Cloud', 'CloudRain', 'morph', 'smooth'],
  ['C', 'env.overcast', 'Cloudy', null, null, null],
  ['C', 'env.rain', 'CloudRain', 'CloudFog', 'morph', 'smooth'],
  ['C', 'env.storm', 'CloudRainWind', null, null, null],
  ['C', 'env.drizzle', 'CloudDrizzle', null, null, null],
  ['C', 'env.thunder', 'CloudLightning', null, null, null],
  ['C', 'env.snow', 'CloudSnow', null, null, null],
  ['C', 'env.fog', 'CloudFog', 'Haze', 'morph', 'smooth'],
  ['C', 'env.haze', 'Haze', null, null, null],
  ['C', 'env.sand', 'custom:SandDust', null, null, null],
  ['C', 'env.wind', 'Wind', null, null, null],
  ['C', 'env.wind.dir', 'Navigation2', null, 'rot', null],
  ['C', 'env.gust', 'WindArrowDown', null, null, null],
  ['C', 'env.turbulence', 'Tornado', null, null, null],
  ['C', 'env.temperature', 'Thermometer', null, null, null],
  ['C', 'env.humidity', 'Droplets', null, null, null],
  ['C', 'env.visibility', 'Binoculars', null, null, null],
  ['C', 'env.sunrise', 'Sunrise', 'Sunset', 'morph', 'smooth'],
  ['C', 'env.time', 'SunMoon', null, null, null],
  ['C', 'env.field', 'WavesHorizontal', null, null, null],
  ['D', 'drone.quad', 'Drone', null, null, null],
  ['D', 'drone.hexa', 'custom:DroneHexa', null, null, null],
  ['D', 'drone.takeoff', 'PlaneTakeoff', 'PlaneLanding', 'morph', null],
  ['D', 'drone.land', 'PlaneLanding', null, null, null],
  ['D', 'drone.armed', 'ShieldCheck', 'ShieldAlert', 'morph', 'smooth'],
  ['D', 'drone.power', 'Power', 'PowerOff', 'morph', null],
  ['D', 'bat.full', 'BatteryFull', 'BatteryMedium', 'morph', 'hud'],
  ['D', 'bat.medium', 'BatteryMedium', 'BatteryLow', 'morph', 'hud'],
  ['D', 'bat.low', 'BatteryLow', 'BatteryWarning', 'morph', 'hud'],
  ['D', 'bat.warn', 'BatteryWarning', null, null, null],
  ['D', 'bat.charging', 'BatteryCharging', null, null, null],
  ['D', 'gnss.rtk', 'Satellite', null, null, null],
  ['D', 'gnss.fix', 'LocateFixed', 'LocateOff', 'swap', null],
  ['D', 'gnss.nofix', 'LocateOff', null, null, null],
  ['D', 'link.high', 'SignalHigh', 'SignalMedium', 'morph', 'hud'],
  ['D', 'link.medium', 'SignalMedium', 'SignalLow', 'morph', 'hud'],
  ['D', 'link.low', 'SignalLow', 'SignalZero', 'morph', 'hud'],
  ['D', 'link.lost', 'SignalZero', null, null, null],
  ['D', 'link.radio', 'RadioTower', null, null, null],
  ['D', 'alt', 'MoveVertical', null, null, null],
  ['D', 'speed', 'Gauge', null, null, null],
  ['D', 'heading', 'Compass', null, 'rot', null],
  ['D', 'health', 'HeartPulse', null, null, null],
  ['D', 'sensor.camera', 'Camera', null, null, null],
  ['D', 'sensor.video', 'Video', 'VideoOff', 'swap', null],
  ['D', 'sensor.thermal', 'ThermometerSun', null, null, null],
  ['D', 'sensor.lidar', 'Radar', null, null, null],
  ['D', 'sensor.compute', 'Cpu', null, null, null],
  ['D', 'mode.manual', 'Hand', null, null, null],
  ['D', 'mode.offboard', 'Bot', null, null, null],
  ['D', 'mode.hold', 'Anchor', null, null, null],
  ['D', 'mode.rtl', 'House', null, null, null],
  ['E', 'cmd.takeoff', 'PlaneTakeoff', null, null, null],
  ['E', 'cmd.land', 'PlaneLanding', null, null, null],
  ['E', 'cmd.goto', 'MapPin', null, null, null],
  ['E', 'cmd.followpath', 'Waypoints', null, null, null],
  ['E', 'cmd.orbit', 'Orbit', null, null, null],
  ['E', 'cmd.hover', 'Crosshair', null, null, null],
  ['E', 'cmd.rth', 'House', null, null, null],
  ['E', 'cmd.coverage', 'Scan', null, null, null],
  ['E', 'cmd.search-area', 'ScanSearch', null, null, null],
  ['E', 'cmd.track', 'Focus', null, null, null],
  ['E', 'cmd.formation', 'custom:Formation', null, null, null],
  ['E', 'cmd.avoid', 'ShieldHalf', null, null, null],
  ['E', 'wp.add', 'MapPinPlus', null, null, null],
  ['E', 'wp.remove', 'MapPinX', null, null, null],
  ['E', 'mission.list', 'ListChecks', null, null, null],
  ['E', 'mission.pending', 'CircleDashed', 'LoaderCircle', 'swap', null],
  ['E', 'mission.running', 'LoaderCircle', 'CircleCheck', 'morph', 'smooth'],
  ['E', 'mission.done', 'CircleCheck', null, null, null],
  ['E', 'mission.failed', 'CircleX', null, null, null],
  ['E', 'mission.paused', 'CirclePause', 'CirclePlay', 'morph', null],
  ['E', 'mission.start', 'Play', 'Square', 'morph', null],
  ['E', 'mission.abort', 'OctagonX', null, null, null],
  ['E', 'mission.delete', 'Trash', null, null, null],
  ['E', 'mission.edit', 'Pencil', null, null, null],
  ['F', 'tl.play', 'Play', 'Pause', 'morph', null],
  ['F', 'tl.pause', 'Pause', 'Play', 'morph', null],
  ['F', 'tl.stop', 'Square', null, null, null],
  ['F', 'tl.skipback', 'SkipBack', null, null, null],
  ['F', 'tl.skipfwd', 'SkipForward', null, null, null],
  ['F', 'tl.rewind', 'Rewind', 'FastForward', 'morph', null],
  ['F', 'tl.ff', 'FastForward', null, null, null],
  ['F', 'tl.stepback', 'StepBack', null, null, null],
  ['F', 'tl.stepfwd', 'StepForward', null, null, null],
  ['F', 'tl.loop', 'Repeat', 'Repeat1', 'morph', null],
  ['F', 'tl.replay', 'RotateCcw', null, null, null],
  ['F', 'tl.history', 'RotateCcwClock', null, null, null],
  ['F', 'tl.clock', 'Clock', null, null, null],
  ['F', 'tl.speed', 'Gauge', null, null, null],
  ['F', 'tl.marker', 'Flag', null, null, null],
  ['F', 'tl.bookmark', 'Bookmark', null, null, null],
  ['F', 'tl.live', 'Radio', null, null, null],
  ['F', 'tl.record', 'CircleDot', null, null, null],
  ['G', 'cam.free', 'Move3d', null, null, null],
  ['G', 'cam.orbit', 'Orbit', null, null, null],
  ['G', 'cam.third', 'Video', null, null, null],
  ['G', 'cam.fpv', 'ScanEye', null, null, null],
  ['G', 'cam.bird', 'Map', null, null, null],
  ['G', 'cam.follow', 'Locate', 'LocateFixed', 'morph', null],
  ['G', 'cam.fov', 'Cone', null, null, null],
  ['G', 'cam.reset', 'Fullscreen', null, null, null],
  ['G', 'cam.zoomin', 'ZoomIn', null, null, null],
  ['G', 'cam.zoomout', 'ZoomOut', null, null, null],
  ['G', 'cam.screenshot', 'ImageDown', null, null, null],
  ['G', 'cam.switch', 'SwitchCamera', null, null, null],
  ['H', 'alert.info', 'Info', null, null, null],
  ['H', 'alert.success', 'CircleCheck', null, null, null],
  ['H', 'alert.warning', 'TriangleAlert', 'OctagonAlert', 'morph', 'smooth'],
  ['H', 'alert.error', 'CircleAlert', null, null, null],
  ['H', 'alert.critical', 'OctagonAlert', null, null, null],
  ['H', 'alert.emergency', 'Siren', null, null, null],
  ['H', 'alert.geofence', 'ShieldAlert', null, null, null],
  ['H', 'alert.linklost', 'WifiOff', null, null, null],
  ['H', 'alert.battery', 'BatteryWarning', null, null, null],
  ['H', 'alert.wind', 'Wind', null, null, null],
  ['H', 'alert.weather', 'CloudLightning', null, null, null],
  ['H', 'alert.collision', 'ShieldHalf', null, null, null],
  ['I', 'agent', 'Bot', 'BotOff', 'morph', null],
  ['I', 'agent.offline', 'BotOff', null, null, null],
  ['I', 'agent.brain', 'BrainCircuit', null, null, null],
  ['I', 'agent.network', 'Network', null, null, null],
  ['I', 'agent.capability', 'ScanSearch', null, null, null],
  ['I', 'agent.task', 'Workflow', null, null, null],
  ['I', 'agent.collab', 'Handshake', null, null, null],
  ['I', 'agent.msg', 'MessagesSquare', null, null, null],
  ['I', 'agent.share', 'Share2', null, null, null],
  ['J', 'perf.fps', 'Activity', null, null, null],
  ['J', 'perf.cpu', 'Cpu', null, null, null],
  ['J', 'perf.mem', 'MemoryStick', null, null, null],
  ['J', 'perf.gpu', 'Zap', null, null, null],
  ['J', 'perf.budget', 'custom:OctreeLod', null, null, null],
  ['J', 'perf.chart', 'ChartLine', null, null, null],
  ['J', 'perf.bench', 'FlaskConical', null, null, null],
  ['J', 'perf.debug', 'Bug', null, null, null],
  ['J', 'perf.timer', 'Timer', null, null, null],
  ['K', 'data.import', 'Upload', null, null, null],
  ['K', 'data.export', 'Download', null, null, null],
  ['K', 'data.folder', 'FolderOpen', null, null, null],
  ['K', 'data.package', 'Package', null, null, null],
  ['K', 'data.file', 'FileBox', null, null, null],
  ['K', 'data.json', 'FileBraces', null, null, null],
  ['K', 'data.server', 'Server', null, null, null],
  ['K', 'data.drive', 'HardDrive', null, null, null],
  ['L', 'chev.down', 'ChevronDown', 'ChevronUp', 'morph', null],
  ['L', 'chev.up', 'ChevronUp', null, null, null],
  ['L', 'chev.left', 'ChevronLeft', 'ChevronRight', 'morph', null],
  ['L', 'chev.right', 'ChevronRight', 'ChevronDown', 'morph', null],
  ['L', 'chev.updown', 'ChevronsUpDown', 'ChevronsDownUp', 'morph', null],
  ['L', 'check', 'Check', 'X', 'morph', null],
  ['L', 'close', 'X', null, null, null],
  ['L', 'plus', 'Plus', 'X', 'morph', null],
  ['L', 'minus', 'Minus', null, null, null],
  ['L', 'more', 'Ellipsis', null, null, null],
  ['L', 'more.v', 'EllipsisVertical', null, null, null],
  ['L', 'grip', 'GripVertical', null, null, null],
  ['L', 'copy', 'Copy', 'Check', 'morph', null],
  ['L', 'refresh', 'RefreshCw', null, null, null],
  ['L', 'external', 'ExternalLink', null, null, null],
  ['L', 'filter', 'Funnel', null, null, null],
  ['L', 'sort', 'ArrowDownUp', null, null, null],
  ['L', 'sliders', 'SlidersHorizontal', null, null, null],
  ['L', 'pin', 'Pin', 'PinOff', 'swap', null],
  ['L', 'star', 'Star', null, null, null],
  ['L', 'link', 'Link', 'Link2Off', 'swap', null],
  ['M', 'cmd.velocity', 'Gamepad2', null, null, null],
  ['M', 'lease.held', 'KeyRound', null, null, null],
  ['M', 'state.hold', 'Hourglass', null, null, null],
  ['M', 'state.stale', 'TimerOff', null, null, null],
  ['M', 'zone.nofly', 'ShieldBan', null, null, null],
  ['M', 'effect.verified', 'BadgeCheck', null, null, null],
  ['M', 'perf.degraded', 'TrendingDown', null, null, null],
  ['M', 'mission.target', 'Target', null, null, null],
  ['N', 'edit.undo', 'Undo2', null, null, null],
  ['N', 'edit.redo', 'Redo2', null, null, null],
  ['N', 'tool.select', 'MousePointer2', null, null, null],
  ['N', 'tool.box', 'SquareDashedMousePointer', null, null, null],
  ['N', 'nav.recon', 'ScanLine', null, null, null],
  ['N', 'drone.ghost', 'Ghost', null, null, null],
  ['N', 'env.blizzard', 'Snowflake', null, null, null],
  ['N', 'sensor.imu', 'Rotate3d', null, null, null],
  ['N', 'sensor.baro', 'MoveVertical', null, null, null],
]

// Custom stroke icons on the 24 grid (AWR-15 §7.8; d03 §4.1): stroke only, no fill, no <g>, no transform.
export const CUSTOM = {
  // 点云图层: scan brackets + sampled points
  PointCloud: [
    ['path', { d: 'M3 7V5a2 2 0 0 1 2-2h2' }],
    ['path', { d: 'M17 3h2a2 2 0 0 1 2 2v2' }],
    ['path', { d: 'M21 17v2a2 2 0 0 1-2 2h-2' }],
    ['path', { d: 'M7 21H5a2 2 0 0 1-2-2v-2' }],
    ['circle', { cx: '8', cy: '10', r: '1' }],
    ['circle', { cx: '12', cy: '8', r: '1' }],
    ['circle', { cx: '16', cy: '11', r: '1' }],
    ['circle', { cx: '10', cy: '15', r: '1' }],
    ['circle', { cx: '15', cy: '16', r: '1' }],
  ],
  // 沙尘: horizontal streaks + suspended particles
  SandDust: [
    ['path', { d: 'M2 8h9' }],
    ['path', { d: 'M2 12h13' }],
    ['path', { d: 'M2 16h8' }],
    ['circle', { cx: '15', cy: '7', r: '1' }],
    ['circle', { cx: '20', cy: '9', r: '1' }],
    ['circle', { cx: '19', cy: '14', r: '1' }],
    ['circle', { cx: '13', cy: '17', r: '1' }],
    ['circle', { cx: '20', cy: '19', r: '1' }],
  ],
  // 八叉树 / LOD: quadtree with one refined cell
  OctreeLod: [
    ['rect', { x: '3', y: '3', width: '18', height: '18', rx: '2' }],
    ['path', { d: 'M12 3v18' }],
    ['path', { d: 'M3 12h18' }],
    ['path', { d: 'M16.5 3v9' }],
    ['path', { d: 'M12 7.5h9' }],
  ],
  // 六旋翼 (异构机型, V1.0): body + 6 arms + 6 rotors
  DroneHexa: [
    ['circle', { cx: '12', cy: '12', r: '2' }],
    ['path', { d: 'M12 10V7' }],
    ['path', { d: 'M13.73 11l2.6-1.5' }],
    ['path', { d: 'M13.73 13l2.6 1.5' }],
    ['path', { d: 'M12 14v3' }],
    ['path', { d: 'M10.27 13l-2.6 1.5' }],
    ['path', { d: 'M10.27 11l-2.6-1.5' }],
    ['circle', { cx: '12', cy: '4.5', r: '2.5' }],
    ['circle', { cx: '18.5', cy: '8.25', r: '2.5' }],
    ['circle', { cx: '18.5', cy: '15.75', r: '2.5' }],
    ['circle', { cx: '12', cy: '19.5', r: '2.5' }],
    ['circle', { cx: '5.5', cy: '15.75', r: '2.5' }],
    ['circle', { cx: '5.5', cy: '8.25', r: '2.5' }],
  ],
  // 编队 / Swarm: three agents + links
  Formation: [
    ['circle', { cx: '12', cy: '5', r: '2.5' }],
    ['circle', { cx: '5', cy: '18', r: '2.5' }],
    ['circle', { cx: '19', cy: '18', r: '2.5' }],
    ['path', { d: 'M10.8 7.2 6.2 15.8' }],
    ['path', { d: 'M13.2 7.2l4.6 8.6' }],
    ['path', { d: 'M7.5 18h9' }],
  ],
  // 相机视锥 FOV (alt to lucide Cone): apex at drone, frustum opening
  CameraFrustum: [
    ['circle', { cx: '5', cy: '12', r: '2' }],
    ['path', { d: 'M7 11 19 5' }],
    ['path', { d: 'M7 13l12 6' }],
    ['path', { d: 'M19 5v14' }],
  ],
}
