// Formation slots and CAPT golden against the Python reference (M10-FR-042, M10-AC-018; AWR-18 §8.3).
// golden/formation.json is generated by tests/swarm/gen_formation_golden.py (scipy linear_sum_assignment).
import { describe, expect, it } from 'vitest'
import { captAssign, captCost, formationSlots, FORMATION_SHAPES, hungarian, rotateSlots, type FormationShape } from '@/stores/missionGeom'
import golden from './golden/formation.json'

interface SlotCase { shape: FormationShape; n: number; spacing_m: number; half_angle_deg: number; cols: number | null; offsets: number[] }
interface CaptCase { P: number[]; G: number[]; assign: number[]; cost: number }

describe('formation slots (Python golden)', () => {
  it('covers the six shapes', () => {
    expect(new Set((golden.slots as SlotCase[]).map((c) => c.shape))).toEqual(new Set(FORMATION_SHAPES))
  })
  it.each(golden.slots as SlotCase[])('$shape n=$n s=$spacing_m', (c) => {
    const off = formationSlots(c.shape, c.n, c.spacing_m, c.half_angle_deg, c.cols ?? undefined)
    expect(off.length).toBe(c.offsets.length)
    for (let i = 0; i < off.length; i++) expect(Math.abs(off[i] - c.offsets[i])).toBeLessThan(1e-9)
  })
  it('virtual anchor: offsets have zero centroid', () => {
    const off = formationSlots('v', 7, 6)
    for (let d = 0; d < 3; d++) {
      let s = 0
      for (let k = 0; k < 7; k++) s += off[3 * k + d]
      expect(Math.abs(s)).toBeLessThan(1e-9)
    }
  })
  it('rotates FLU offsets into ENU', () => {
    const off = new Float64Array([1, 0, 0, 0, 1, 0])
    const r = rotateSlots(off, Math.PI / 2)
    expect(r[0]).toBeCloseTo(0, 12)
    expect(r[1]).toBeCloseTo(1, 12)
    expect(r[3]).toBeCloseTo(-1, 12)
    expect(r[4]).toBeCloseTo(0, 12)
  })
})

describe('CAPT assignment (Python golden)', () => {
  it.each(golden.capt as CaptCase[])('n=%#', (c) => {
    const P = Float64Array.from(c.P)
    const G = Float64Array.from(c.G)
    const a = captAssign(P, G)
    expect(Array.from(a)).toEqual(c.assign)
    const cost = captCost(P, G, a)
    expect(Math.abs(cost - c.cost)).toBeLessThanOrEqual(1e-6 + 1e-9 * Math.abs(c.cost))
  })
  it('hungarian solves a rectangular problem', () => {
    // rows 2, cols 3: optimum picks columns 2 and 0
    const C = Float64Array.from([4, 2, 1, 1, 5, 6])
    expect(Array.from(hungarian(C, 2, 3))).toEqual([2, 0])
  })
})
