// GENERATED by tools/shadcn/gen-theme-tokens.mjs from tools/shadcn/tokens/input.json. DO NOT EDIT.

/** input thresholds (AWR-14 §6.1), one-red arbitration (AWR-15 §3.7.2) and M15 presentation timers (M15 §6.14); ms, px, Hz */
export const INPUT = {
  "clickTolPx": 4,
  "contextMaxMs": 300,
  "boxMinPx": 6,
  "hoverPickHz": 20,
  "rayPreviewHz": 5,
  "sliderCommitIdleMs": 500,
  "validateIdleMs": 300,
  "resultHoldMs": 1500,
  "killHoldMs": 1000,
  "urlSyncHz": 1,
  "offlineBannerDelayMs": 1000,
  "staleAfterMs": 1000,
  "redEvalIntervalMs": 250,
  "redDwellMs": 1500,
  "bridgeFlushMs": 250,
  "persistDebounceMs": 500,
  "toastInfoMs": 4000,
  "toastWarnMs": 6000,
  "iconDwellMs": 1500,
  "bootSlowHintMs": 8000,
  "shakeDedupMs": 10000,
  "governorToastDedupMs": 10000,
  "storeWriteWindowMs": 1000,
  "resizeDebounceMs": 120
} as const

/** capacities and caps (M15 §6.14) */
export const LIMITS = {
  "bridgeRingCap": 8192,
  "eventLogCap": 5000,
  "alarmCap": 512,
  "toastLimit": 3,
  "sanitizeMaxCodepoints": 256,
  "sanitizeLruCap": 512,
  "storeWritesWarnPerS": 10,
  "selectionMax": 1000,
  "selectionUrlMax": 32,
  "virtualizeListRows": 100,
  "virtualizeTableRows": 200
} as const

/** shell geometry in CSS px (AWR-14 §3.3, §14.1) */
export const LAYOUT = {
  "headerPx": 44,
  "timelinePx": 48,
  "gapPx": 8,
  "replayBannerPx": 32,
  "leftDefaultPx": 288,
  "leftMinPx": 256,
  "leftMaxPx": 400,
  "rightDefaultPx": 320,
  "rightMinPx": 280,
  "rightMaxPx": 480,
  "dockDefaultPx": 240,
  "dockMinPx": 160,
  "dockMaxFrac": 0.5,
  "unobscuredMinWPx": 320,
  "unobscuredMinHPx": 180,
  "minViewportWPx": 1280,
  "minViewportHPx": 720,
  "railRowPx": 56,
  "railOverscan": 10,
  "hudWidthPx": 264
} as const

/** lieflat scheduler and canvas limits (ADR-031; d01 §3.6) */
export const LF = {
  "ringCap": 1200,
  "canvasDprMax": 2,
  "drawsPerFrame": 2,
  "drawBudgetMs": 2,
  "streamingSlotsTierS": 4,
  "hudHz": 4,
  "focusHz": 10,
  "focusHzTierS": 4,
  "svgHzMax": 2,
  "loopFallbackFrames": 2
} as const

/** DOM motion budget (ADR-029; d02 §4.7) and morph concurrency K (ADR-030) */
export const MOTION_BUDGET = {
  "morphK": 8,
  "blurMax": 12,
  "popPerS": 24,
  "loopMax": 2
} as const

/** telemetry icon buckets (d03 §3.6) */
export const ICON_BUCKETS = {"batteryEdgesPct":[20,40,70],"linkEdgesPct":[25,50,75],"hysteresisPct":3,"prewarmSliceMs":3} as const
