// GENERATED by tools/shadcn/gen-theme-tokens.mjs from styles/motion/tokens.css, styles/motion/ext-tokens.css, tools/shadcn/tokens/motion.json. DO NOT EDIT.

/** Durations in ms, distances in CSS px (ADR-029; AWR-15 §8.1). Tier S writes continuous telemetry text every 250 ms. */
export const MOTION = {
  "durationStaggerMs": 40,
  "durationMicroMs": 80,
  "durationQuickMs": 150,
  "durationFastMs": 250,
  "durationMediumMs": 350,
  "durationSlowMs": 400,
  "durationVerySlowMs": 500,
  "panelOpenMs": 400,
  "panelCloseMs": 350,
  "dropdownOpenMs": 250,
  "dropdownCloseMs": 150,
  "modalOpenMs": 250,
  "modalCloseMs": 150,
  "iconSwapMs": 250,
  "textSwapMs": 150,
  "toastOpenMs": 350,
  "toastCloseMs": 250,
  "digitMs": 500,
  "digitStaggerMs": 70,
  "shakeSegmentAMs": 80,
  "shakeSegmentBMs": 60,
  "shakeTotalMs": 280,
  "revealMs": 400,
  "pulseMs": 1000,
  "staggerTextMs": 500,
  "staggerTextStepMs": 40,
  "resizeMs": 300,
  "badgePopMs": 500,
  "badgeCloseMs": 180,
  "tabsMs": 250,
  "accordionMs": 250,
  "cameraMinMs": 400,
  "cameraMaxMs": 1200,
  "lodFadeMs": 250,
  "chartEnterMs": 900,
  "chartSlowMs": 1200,
  "telemetryAnimIntervalMs": 500,
  "telemetryTextIntervalMs": {
    "S": 250,
    "B": 100,
    "A": 100
  },
  "staggerCapMs": {
    "full": 300,
    "lite": 150
  },
  "springSettleMs": {
    "snappy": 450,
    "smooth": 800,
    "hud": 380
  },
  "distanceDrawerPx": 40,
  "distanceMicroPx": 4,
  "distanceBasePx": 8,
  "distanceMediumPx": 12,
  "digitDistancePx": 8,
  "textSwapDistancePx": 4,
  "shakeDistancePx": 6,
  "shakeOvershootPx": 4,
  "blurSmallPx": 2,
  "iconSwapStartScale": 0.25
} as const

/** Cubic bezier control points [x1, y1, x2, y2]; CSS keywords are given as their equivalent curves (g07 §3.1). */
export const EASE = {"smoothOut":[0.22,1,0.36,1],"bounce":[0.34,1.36,0.64,1],"bounceStrong":[0.34,3.85,0.64,1],"springSnappy":[0.34,1.36,0.64,1],"digit":[0.34,1.45,0.64,1],"shake":[0.22,1,0.36,1],"inOut":[0.42,0,0.58,1],"out":[0,0,0.58,1],"linear":[0,0,1,1]} as const

/** CSS timing-function strings for WAAPI (Element.animate) options. */
export const EASE_CSS = {
  "smoothOut": "cubic-bezier(0.22, 1, 0.36, 1)",
  "bounce": "cubic-bezier(0.34, 1.36, 0.64, 1)",
  "springSnappy": "cubic-bezier(0.34, 1.36, 0.64, 1)",
  "digit": "cubic-bezier(0.34, 1.45, 0.64, 1)",
  "shake": "cubic-bezier(0.22, 1, 0.36, 1)",
  "inOut": "ease-in-out",
  "out": "ease-out",
  "linear": "linear"
} as const

/** morphicons springs {k, c} (d03 §3.2): snappy for user actions, smooth for state processes, hud for lists and HUD. */
export const SPRINGS = {"snappy":{"k":420,"c":30},"smooth":{"k":170,"c":26},"hud":{"k":900,"c":60}} as const

export type MotionTokens = typeof MOTION
