"""AWR contracts: generated types, dtypes, accessors and tables (AWR-03 §5.10).

Generated by tools/contracts/gen.py from packages/contracts. Do not edit."""

__version__ = "1.0.0"
CONTRACTS_VERSION = __version__
LAYOUT_ID = 0x3D5E08D0

__all__ = ["CONTRACTS_VERSION", "LAYOUT_ID", "__version__"]
