"""Location of the packages/contracts source tree (schemas, golden, fixtures).

Generated by tools/contracts/gen.py from packages/contracts. Do not edit."""

from __future__ import annotations

import os
from pathlib import Path


def contracts_root() -> Path:
    """packages/contracts of this checkout; AWR_CONTRACTS_DIR overrides."""
    env = os.environ.get("AWR_CONTRACTS_DIR")
    if env:
        return Path(env)
    return Path(__file__).resolve().parents[3] / "packages" / "contracts"


def schema_path(rel: str) -> Path:
    return contracts_root() / rel
