"""Zenoh key space from packages/contracts/bus/keys.json (AWR-17 §9.3). Key literals are allowed only in this module.

Generated by tools/contracts/gen.py from packages/contracts. Do not edit."""

from __future__ import annotations

import re

NAMESPACE_FMT = "awr/{world}/{run}"
CHUNK_RE = re.compile("^[a-z0-9][a-z0-9_-]*$")
EVENT_CATEGORIES: tuple[str, ...] = ("cmd", "safety", "mission", "sim", "env", "lease", "proc", "rec", "job", "world", "sensor", "agent", "health")
PRODUCERS: tuple[str, ...] = ("sim-core", "replay", "api", "supervisor", "recorder", "replay-worker", "agent-runtime", "job-worker", "geo-worker")


def _chunk(x: str) -> str:
    if not CHUNK_RE.match(x):
        raise ValueError(f"invalid key chunk: {x!r}")
    return x


def namespace(world: str, run: str) -> str:
    return NAMESPACE_FMT.format(world=_chunk(world), run=_chunk(run))


def proc_alive(name: str) -> str:
    return f"proc/{_chunk(name)}/alive"


def proc_ready(name: str) -> str:
    return f"proc/{_chunk(name)}/ready"


def ctl_cmd(producer: str) -> str:
    return f"ctl/{_chunk(producer)}/cmd"


CTL_CLOCK = "ctl/sim-core/clock"


CTL_LEASE = "ctl/sim-core/lease"


def ctl_roster(producer: str) -> str:
    return f"ctl/{_chunk(producer)}/roster"


CTL_ESTIMATE = "ctl/sim-core/estimate"


CTL_QUERY = "ctl/sim-core/query"


CTL_SETPOINT = "ctl/sim-core/setpoint"


CTL_GCS = "ctl/sim-core/gcs"


CTL_INTEREST = "ctl/sim-core/interest"


def evt(producer: str, cat: str) -> str:
    return f"evt/{_chunk(producer)}/{_chunk(cat)}"


def evt_replay(producer: str) -> str:
    return f"evt/{_chunk(producer)}/_replay"


def state_ext(producer: str) -> str:
    return f"state/{_chunk(producer)}/ext"


def state_safety(producer: str) -> str:
    return f"state/{_chunk(producer)}/safety"


def state_sensor(producer: str) -> str:
    return f"state/{_chunk(producer)}/sensor"


STATE_DETAIL = "state/sim-core/detail"


STATE_PERF = "state/sim-core/perf"


STATE_ENV = "state/sim-core/env"


STATE_MISSION = "state/sim-core/mission"


SYS_PROCS = "sys/procs"


SYS_RESTART = "sys/restart"


SYS_RUN = "sys/run"


SYS_START = "sys/start"


SYS_STOP = "sys/stop"


SYS_INJECT = "sys/inject"


def ctl_replay_worker(op: str) -> str:
    return f"ctl/replay-worker/{_chunk(op)}"


def ctl_recorder(op: str) -> str:
    return f"ctl/recorder/{_chunk(op)}"


EVT_RECORDER = "evt/recorder/rec"


def ctl_agent(op: str) -> str:
    return f"ctl/agent-runtime/{_chunk(op)}"


def state_agent(what: str) -> str:
    return f"state/agent-runtime/{_chunk(what)}"


def evt_job(cat: str) -> str:
    return f"evt/job-worker/{_chunk(cat)}"


def svc_job(op: str) -> str:
    return f"svc/job/{_chunk(op)}"


def svc_geo(op: str) -> str:
    return f"svc/geo/{_chunk(op)}"


def state_frame(producer: str) -> str:
    return f"state/{_chunk(producer)}/frame"
