"""Command services, argument schemas and the admission matrix from packages/contracts/rt/commands.json (AWR-17 §7.1; AWR-12 §5.2).

Generated by tools/contracts/gen.py from packages/contracts. Do not edit."""

from __future__ import annotations

import re
from typing import Any, NamedTuple

from .enums import FlightFlags, FlightState

ADMISSION_COLUMNS: tuple[str, ...] = ("UNKNOWN", "DISARMED", "PREFLIGHT", "READY", "TAKING_OFF", "FLYING", "CORRECTING", "HOLD", "RTL_op", "RTL_auto", "LANDING_op", "LANDING_auto", "ELAND", "FAILSAFE", "LANDED", "CRASHED")
ADMISSION_SYMBOL_CODE: dict[str, int] = {"Y": 0, "=": 106, "S": 101, "-": 105}
ADMISSION_CONDITION_ELSE: dict[str, str] = {"sub_ready_to_arm": "-", "agl_ge_2m": "-", "pause_active_nav": "-", "track_suspended": "-", "cause_cleared": "S", "escalation_levels_failsafe": "-"}


class Service(NamedTuple):
    name: str
    op: str
    pattern: re.Pattern[str]
    category: str
    lease: bool | str | None
    agent: str
    d1: str
    batchable: bool
    aliases: tuple[str, ...]
    args_schema: dict[str, Any]
    admission: tuple[str, ...] | None
    admission_cond: dict[str, str]


def _pattern(name: str) -> re.Pattern[str]:
    return re.compile("^" + re.sub(r"\\\{(\w+)\\\}", lambda m: f"(?P<{m.group(1)}>[a-z0-9][a-z0-9_-]*)", re.escape(name)) + "$")


SERVICES: tuple[Service, ...] = (
    Service("uav/{id}/cmd/takeoff", "takeoff", _pattern("uav/{id}/cmd/takeoff"), "nav_setup", True, "own_lease", "core", True, (),
            {"type": "object", "additionalProperties": False, "properties": {"alt_m": {"type": "number", "minimum": 0.5, "maximum": 120, "default": 2.5, "unit": "m", "description": "AGL"}, "auto_arm": {"type": "boolean", "default": True}}},
            ("-", "Y", "-", "Y", "=", "-", "-", "-", "-", "-", "-", "-", "-", "-", "Y", "-"), {"DISARMED": "sub_ready_to_arm"}),
    Service("uav/{id}/cmd/land", "land", _pattern("uav/{id}/cmd/land"), "safety", False, "own_lease", "core", True, (),
            {"type": "object", "additionalProperties": False, "properties": {"at": {"oneOf": [{"enum": ["here", "home"]}, {"type": "object", "additionalProperties": False, "properties": {"pos": {"type": "array", "items": {"type": "number"}, "minItems": 3, "maxItems": 3}}, "required": ["pos"]}], "default": "here"}}},
            ("-", "-", "-", "-", "Y", "Y", "Y", "Y", "Y", "Y", "=", "=", "S", "S", "=", "-"), {}),
    Service("uav/{id}/cmd/goto", "goto", _pattern("uav/{id}/cmd/goto"), "nav", True, "yes", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {"pos": {"type": "array", "items": {"type": "number"}, "minItems": 3, "maxItems": 3, "unit": "m", "description": "world ENU"}, "yaw_rad": {"type": ["number", "null"], "minimum": -3.141592653589793, "maximum": 3.141592653589793, "default": None, "unit": "rad"}, "speed_mps": {"type": "number", "exclusiveMinimum": 0, "maximum": 12, "unit": "m/s", "description": "default: cruise speed of the active limits profile; above the profile limit it is clamped with warnings [SPEED_CLAMPED]"}, "tol_m": {"type": "number", "minimum": 0.2, "maximum": 10, "default": 0.5, "unit": "m"}, "route": {"enum": ["auto", "direct", "safe_transit"], "default": "auto"}}, "required": ["pos"]},
            ("-", "-", "-", "-", "-", "Y", "S", "S", "Y", "S", "Y", "S", "S", "S", "-", "-"), {}),
    Service("uav/{id}/cmd/follow_path", "follow_path", _pattern("uav/{id}/cmd/follow_path"), "nav", True, "yes", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {"waypoints": {"type": "array", "minItems": 2, "maxItems": 1000, "items": {"type": "array", "items": {"type": "number"}, "minItems": 3, "maxItems": 3}, "description": "total length <= 20 km"}, "speed_mps": {"type": "number", "exclusiveMinimum": 0, "maximum": 12, "unit": "m/s", "description": "default: cruise speed of the active limits profile; above the profile limit it is clamped with warnings [SPEED_CLAMPED]"}, "mode": {"enum": ["auto", "mission", "offboard"], "default": "auto"}, "bspline": {"type": "object", "additionalProperties": False, "properties": {"order": {"const": 3}, "ts_s": {"type": "number", "exclusiveMinimum": 0}, "ctrl_pts": {"type": "array", "minItems": 4, "items": {"type": "array", "items": {"type": "number"}, "minItems": 3, "maxItems": 3}}, "t0_ns": {"type": "integer"}, "traj_id": {"type": "string"}}, "required": ["order", "ts_s", "ctrl_pts"]}}, "required": ["waypoints"]},
            ("-", "-", "-", "-", "-", "Y", "S", "S", "Y", "S", "Y", "S", "S", "S", "-", "-"), {}),
    Service("uav/{id}/cmd/orbit", "orbit", _pattern("uav/{id}/cmd/orbit"), "nav", True, "yes", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {"center": {"type": "array", "items": {"type": "number"}, "minItems": 3, "maxItems": 3}, "radius_m": {"type": "number", "minimum": 1, "maximum": 1000, "unit": "m", "description": "speed_mps^2/radius_m <= 3 m/s^2"}, "speed_mps": {"type": "number", "exclusiveMinimum": 0, "maximum": 12, "unit": "m/s", "description": "default: cruise speed of the active limits profile; above the profile limit it is clamped with warnings [SPEED_CLAMPED]"}, "cw": {"type": "boolean", "default": True}, "turns": {"type": "number", "minimum": 0, "maximum": 100, "default": 0}, "yaw_behavior": {"enum": ["center", "tangent", "fixed"], "default": "center"}}, "required": ["center", "radius_m"]},
            ("-", "-", "-", "-", "-", "Y", "S", "S", "Y", "S", "Y", "S", "S", "S", "-", "-"), {}),
    Service("uav/{id}/cmd/hover", "hover", _pattern("uav/{id}/cmd/hover"), "safety_light", False, "own_lease", "core", True, ("uav/{id}/cmd/hold",),
            {"type": "object", "additionalProperties": False, "properties": {}},
            ("-", "-", "-", "-", "Y", "Y", "S", "S", "Y", "S", "Y", "S", "S", "S", "-", "-"), {}),
    Service("uav/{id}/cmd/rtl", "rtl", _pattern("uav/{id}/cmd/rtl"), "safety", False, "own_lease", "core", True, (),
            {"type": "object", "additionalProperties": False, "properties": {"land": {"type": "boolean", "default": True}, "alt_m": {"type": ["number", "null"], "minimum": 10, "maximum": 500, "default": None, "unit": "m", "description": "relative to home; never below the AWR-12 §5.8.3 safe altitude"}}},
            ("-", "-", "-", "-", "-", "Y", "Y", "Y", "=", "=", "Y", "S", "S", "S", "-", "-"), {}),
    Service("uav/{id}/cmd/velocity", "velocity", _pattern("uav/{id}/cmd/velocity"), "nav_stream", True, "no", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {"frame": {"enum": ["world", "body"], "default": "world"}, "hold_alt": {"type": "boolean", "default": True}, "vmax_mps": {"type": "number", "exclusiveMinimum": 0, "unit": "m/s", "description": "default: limits profile maximum"}}},
            ("-", "-", "-", "-", "-", "Y", "S", "S", "Y", "S", "Y", "S", "S", "S", "-", "-"), {}),
    Service("uav/{id}/cmd/velocity_stop", "velocity_stop", _pattern("uav/{id}/cmd/velocity_stop"), "nav_stream", True, "no", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {}},
            ("-", "-", "-", "-", "-", "Y", "S", "S", "Y", "S", "Y", "S", "S", "S", "-", "-"), {}),
    Service("uav/{id}/cmd/safety_stop", "safety_stop", _pattern("uav/{id}/cmd/safety_stop"), "safety_lock", False, "no", "core", True, (),
            {"type": "object", "additionalProperties": False, "properties": {}},
            ("-", "-", "-", "-", "Y", "Y", "Y", "=", "Y", "Y", "Y", "Y", "S", "S", "-", "-"), {"LANDING_op": "agl_ge_2m", "LANDING_auto": "agl_ge_2m"}),
    Service("uav/{id}/cmd/pause", "pause", _pattern("uav/{id}/cmd/pause"), "mission", True, "own_lease", "core", True, (),
            {"type": "object", "additionalProperties": False, "properties": {}},
            ("-", "-", "-", "-", "-", "Y", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"), {"FLYING": "pause_active_nav"}),
    Service("uav/{id}/cmd/resume", "resume", _pattern("uav/{id}/cmd/resume"), "task_or_unlock", "unlock_exempt", "non_unlock_only", "core", True, (),
            {"type": "object", "additionalProperties": False, "properties": {}},
            ("-", "-", "-", "-", "-", "Y", "-", "Y", "-", "Y", "-", "-", "-", "-", "-", "-"), {"FLYING": "track_suspended", "HOLD": "cause_cleared", "RTL_auto": "cause_cleared"}),
    Service("uav/{id}/cmd/arm", "arm", _pattern("uav/{id}/cmd/arm"), "setup", True, "own_lease", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {"force": {"type": "boolean", "default": False, "description": "D1 accepts false only; true returns 109"}}},
            ("-", "Y", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"), {"DISARMED": "sub_ready_to_arm"}),
    Service("uav/{id}/cmd/disarm", "disarm", _pattern("uav/{id}/cmd/disarm"), "setup", True, "own_lease", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {"force": {"type": "boolean", "default": False, "description": "D1 accepts false only; true returns 109"}}},
            ("-", "-", "Y", "Y", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "Y", "-"), {}),
    Service("uav/{id}/cmd/cancel", "cancel", _pattern("uav/{id}/cmd/cancel"), "call_control", False, "own_calls", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {"call_id": {"type": "string", "minLength": 1}}, "required": ["call_id"]},
            ("-", "-", "-", "-", "Y", "Y", "S", "S", "Y", "S", "Y", "S", "S", "S", "-", "-"), {}),
    Service("uav/{id}/cmd/acquire", "acquire", _pattern("uav/{id}/cmd/acquire"), "lease", None, "agent_class", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {"priority": {"enum": ["normal", "override"], "default": "normal"}, "confirm_token": {"type": "string"}}},
            None, {}),
    Service("uav/{id}/cmd/release", "release", _pattern("uav/{id}/cmd/release"), "lease", None, "yes", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {"return_to": {"enum": ["previous", "none"], "default": "previous"}}},
            None, {}),
    Service("uav/{id}/cmd/kill", "kill", _pattern("uav/{id}/cmd/kill"), "safety", False, "no", "ext", False, (),
            {"type": "object", "additionalProperties": False, "properties": {"confirm_token": {"type": "string", "minLength": 1}}, "required": ["confirm_token"]},
            ("-", "-", "-", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "-"), {}),
    Service("uav/{id}/cmd/escalate", "escalate", _pattern("uav/{id}/cmd/escalate"), "safety", False, "no", "ext", False, (),
            {"type": "object", "additionalProperties": False, "properties": {"confirm_token": {"type": "string", "minLength": 1}}, "required": ["confirm_token"]},
            ("-", "-", "-", "-", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "-", "-", "-"), {"ELAND": "escalation_levels_failsafe"}),
    Service("fleet/cmd/{op}", "fleet/cmd", _pattern("fleet/cmd/{op}"), "batch", "per_vehicle", "no", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {"vehicles": {"oneOf": [{"type": "array", "minItems": 1, "maxItems": 1000, "items": {"type": "string", "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$"}}, {"const": "*"}]}, "args": {"type": "object"}}, "required": ["vehicles"]},
            None, {}),
    Service("mission/{mid}/start", "mission/start", _pattern("mission/{mid}/start"), "mission", "engine", "no", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {}},
            None, {}),
    Service("mission/{mid}/pause", "mission/pause", _pattern("mission/{mid}/pause"), "mission", "engine", "no", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {}},
            None, {}),
    Service("mission/{mid}/resume", "mission/resume", _pattern("mission/{mid}/resume"), "mission", "engine", "no", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {}},
            None, {}),
    Service("mission/{mid}/abort", "mission/abort", _pattern("mission/{mid}/abort"), "mission", "engine", "no", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {}},
            None, {}),
    Service("sim/play", "sim/play", _pattern("sim/play"), "clock", None, "no", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {}},
            None, {}),
    Service("sim/pause", "sim/pause", _pattern("sim/pause"), "clock", None, "no", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {}},
            None, {}),
    Service("sim/step", "sim/step", _pattern("sim/step"), "clock", None, "no", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {"ticks": {"type": "integer", "minimum": 1, "maximum": 2500, "default": 25, "description": "4 ms per tick"}}},
            None, {}),
    Service("sim/speed", "sim/speed", _pattern("sim/speed"), "clock", None, "no", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {"rate": {"enum": [0.25, 0.5, 1, 2, 5, 10]}}, "required": ["rate"]},
            None, {}),
    Service("sim/reset", "sim/reset", _pattern("sim/reset"), "clock", None, "no", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {"scenario_id": {"type": ["string", "null"], "default": None}, "profile": {"type": ["string", "null"], "default": None}}},
            None, {}),
    Service("env/set", "env/set", _pattern("env/set"), "env", None, "no", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {"patch": {"type": "object", "description": "partial EnvScalars or Config (field paths per env/presets.json fields[])"}, "duration_s": {"type": "number", "minimum": 0, "maximum": 600, "default": 3, "unit": "s"}, "mode": {"enum": ["smooth", "step", "exp"], "default": "smooth"}}, "required": ["patch"]},
            None, {}),
    Service("env/preset", "env/preset", _pattern("env/preset"), "env", None, "no", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {"name": {"type": "string", "minLength": 1}, "duration_s": {"type": "number", "minimum": 0, "maximum": 600, "default": 30, "unit": "s"}}, "required": ["name"]},
            None, {}),
    Service("env/query", "env/query", _pattern("env/query"), "query", None, "yes", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {"points": {"type": "array", "minItems": 1, "maxItems": 256, "items": {"type": "array", "items": {"type": "number"}, "minItems": 3, "maxItems": 3}}, "t_ns": {"type": "integer"}, "fields": {"type": "array", "items": {"enum": ["WIND", "WIND_PARTS", "TURB_SPEC", "OPTICS", "PRECIP", "THERMO"]}}, "frame": {"enum": ["global", "local", "add_velocity_global", "add_velocity_local"], "default": "global"}, "vel_mps": {"type": "array", "items": {"type": "array", "items": {"type": "number"}, "minItems": 3, "maxItems": 3}}, "q_xyzw": {"type": "array", "items": {"type": "array", "items": {"type": "number"}, "minItems": 4, "maxItems": 4}}}, "required": ["points"]},
            None, {}),
    Service("seat/release", "seat/release", _pattern("seat/release"), "seat", None, "no", "core", False, (),
            {"type": "object", "additionalProperties": False, "properties": {}},
            None, {}),
    Service("seat/takeover", "seat/takeover", _pattern("seat/takeover"), "seat", None, "no", "ext", False, (),
            {"type": "object", "additionalProperties": False, "properties": {"confirm_token": {"type": "string", "minLength": 1}}, "required": ["confirm_token"]},
            None, {}),
    Service("confirm/issue", "confirm/issue", _pattern("confirm/issue"), "confirm", None, "no", "ext", False, (),
            {"type": "object", "additionalProperties": False, "properties": {"action": {"type": "string"}, "target": {"type": "string"}}, "required": ["action", "target"]},
            None, {}),
    Service("rec/start", "rec/start", _pattern("rec/start"), "rec", None, "no", "ext", False, (),
            {"type": "object", "additionalProperties": False, "properties": {}},
            None, {}),
    Service("rec/stop", "rec/stop", _pattern("rec/stop"), "rec", None, "no", "ext", False, (),
            {"type": "object", "additionalProperties": False, "properties": {}},
            None, {}),
)

SERVICE_BY_OP: dict[str, Service] = {s.op: s for s in SERVICES}
_ALIAS: list[tuple[re.Pattern[str], Service]] = [(_pattern(a), s) for s in SERVICES for a in s.aliases]


def match_service(name: str) -> tuple[Service, dict[str, str]] | None:
    """Resolve a WS service name (uav/{id}/cmd/goto, fleet/cmd/rtl, sim/play ...) to its Service and path parameters."""
    for s in SERVICES:
        m = s.pattern.match(name)
        if m:
            return s, m.groupdict()
    for p, s in _ALIAS:
        m = p.match(name)
        if m:
            return s, m.groupdict()
    return None


def admission_column(fs: int, flags: int) -> int:
    """Column index of the admission matrix: RTL and LANDING split by flags.FAILSAFE (operator vs automatic)."""
    auto = bool(flags & FlightFlags.FAILSAFE)
    order = [FlightState.UNKNOWN, FlightState.DISARMED, FlightState.PREFLIGHT, FlightState.READY, FlightState.TAKING_OFF,
             FlightState.FLYING, FlightState.CORRECTING, FlightState.HOLD]
    if fs in order:
        return order.index(fs)
    if fs == FlightState.RTL:
        return 9 if auto else 8
    if fs == FlightState.LANDING:
        return 11 if auto else 10
    return {FlightState.ELAND: 12, FlightState.FAILSAFE: 13, FlightState.LANDED: 14, FlightState.CRASHED: 15}[FlightState(fs)]


def admit_symbol(op: str, fs: int, flags: int) -> tuple[str, str | None]:
    """(symbol, condition id) for a vehicle command; symbol Y, =, S, - (AWR-12 §5.2). Conditions are applied by the caller."""
    s = SERVICE_BY_OP[op]
    if s.admission is None:
        raise KeyError(f"{op} has no admission row")
    col = admission_column(fs, flags)
    return s.admission[col], s.admission_cond.get(ADMISSION_COLUMNS[col])
