"""Enumerations from packages/contracts/rt/enums.json (awr.enums.v1).

Generated by tools/contracts/gen.py from packages/contracts. Do not edit."""

from __future__ import annotations

from enum import IntEnum, IntFlag


class FlightState(IntEnum):
    UNKNOWN = 0
    DISARMED = 1
    PREFLIGHT = 2
    READY = 3
    TAKING_OFF = 4
    FLYING = 5
    CORRECTING = 6
    HOLD = 7
    RTL = 8
    LANDING = 9
    ELAND = 10
    FAILSAFE = 11
    LANDED = 12
    CRASHED = 13


FLIGHTSTATE_NAMES: dict[int, str] = {0: "UNKNOWN", 1: "DISARMED", 2: "PREFLIGHT", 3: "READY", 4: "TAKING_OFF", 5: "FLYING", 6: "CORRECTING", 7: "HOLD", 8: "RTL", 9: "LANDING", 10: "ELAND", 11: "FAILSAFE", 12: "LANDED", 13: "CRASHED"}
FLIGHTSTATE_BY_NAME: dict[str, int] = {"UNKNOWN": 0, "DISARMED": 1, "PREFLIGHT": 2, "READY": 3, "TAKING_OFF": 4, "FLYING": 5, "CORRECTING": 6, "HOLD": 7, "RTL": 8, "LANDING": 9, "ELAND": 10, "FAILSAFE": 11, "LANDED": 12, "CRASHED": 13}


class FlightFlags(IntFlag):
    ARMED = 1
    IN_AIR = 2
    LOC_OK = 4
    FAILSAFE = 8
    GCS_LINK = 16
    FCU_LINK = 32
    LOC_DEGRADED = 64
    ALERT = 128


FLIGHTFLAGS_NAMES: dict[int, str] = {1: "ARMED", 2: "IN_AIR", 4: "LOC_OK", 8: "FAILSAFE", 16: "GCS_LINK", 32: "FCU_LINK", 64: "LOC_DEGRADED", 128: "ALERT"}
FLIGHTFLAGS_BY_NAME: dict[str, int] = {"ARMED": 1, "IN_AIR": 2, "LOC_OK": 4, "FAILSAFE": 8, "GCS_LINK": 16, "FCU_LINK": 32, "LOC_DEGRADED": 64, "ALERT": 128}


class Owner(IntEnum):
    NONE = 0
    OPERATOR = 1
    MISSION = 2
    AGENT = 3
    SWARM = 4
    SAFETY = 5
    PILOT = 6
    EXTERNAL = 7


OWNER_NAMES: dict[int, str] = {0: "NONE", 1: "OPERATOR", 2: "MISSION", 3: "AGENT", 4: "SWARM", 5: "SAFETY", 6: "PILOT", 7: "EXTERNAL"}
OWNER_BY_NAME: dict[str, int] = {"NONE": 0, "OPERATOR": 1, "MISSION": 2, "AGENT": 3, "SWARM": 4, "SAFETY": 5, "PILOT": 6, "EXTERNAL": 7}


class Native(IntEnum):
    INIT = 0
    MANUAL = 1
    COMMAND = 2
    LAND = 3


NATIVE_NAMES: dict[int, str] = {0: "INIT", 1: "MANUAL", 2: "COMMAND", 3: "LAND"}
NATIVE_BY_NAME: dict[str, int] = {"INIT": 0, "MANUAL": 1, "COMMAND": 2, "LAND": 3}


class PoseSrc(IntEnum):
    ESTIMATE = 0
    TRUTH = 1
    FUSED = 2
    KINEMATIC = 3


POSESRC_NAMES: dict[int, str] = {0: "ESTIMATE", 1: "TRUTH", 2: "FUSED", 3: "KINEMATIC"}
POSESRC_BY_NAME: dict[str, int] = {"ESTIMATE": 0, "TRUTH": 1, "FUSED": 2, "KINEMATIC": 3}


class Lifecycle(IntEnum):
    PENDING = 0
    PROVISIONING = 1
    STARTING = 2
    BOOTED = 3
    READY = 4
    DEGRADED = 5
    LOST = 6
    RESTARTING = 7
    FAILED = 8
    DRAINING = 9
    STOPPED = 10
    REMOVED = 11


LIFECYCLE_NAMES: dict[int, str] = {0: "PENDING", 1: "PROVISIONING", 2: "STARTING", 3: "BOOTED", 4: "READY", 5: "DEGRADED", 6: "LOST", 7: "RESTARTING", 8: "FAILED", 9: "DRAINING", 10: "STOPPED", 11: "REMOVED"}
LIFECYCLE_BY_NAME: dict[str, int] = {"PENDING": 0, "PROVISIONING": 1, "STARTING": 2, "BOOTED": 3, "READY": 4, "DEGRADED": 5, "LOST": 6, "RESTARTING": 7, "FAILED": 8, "DRAINING": 9, "STOPPED": 10, "REMOVED": 11}


class LocStatus(IntEnum):
    NO_MAP = 0
    WAIT_INIT = 1
    ALIGNING = 2
    TRACKING = 3
    DEGRADED = 4
    LOST = 5
    OUT_OF_MAP = 6


LOCSTATUS_NAMES: dict[int, str] = {0: "NO_MAP", 1: "WAIT_INIT", 2: "ALIGNING", 3: "TRACKING", 4: "DEGRADED", 5: "LOST", 6: "OUT_OF_MAP"}
LOCSTATUS_BY_NAME: dict[str, int] = {"NO_MAP": 0, "WAIT_INIT": 1, "ALIGNING": 2, "TRACKING": 3, "DEGRADED": 4, "LOST": 5, "OUT_OF_MAP": 6}


class CallStatus(IntEnum):
    ACCEPTED = 0
    REJECTED = 1
    RUNNING = 2
    SUCCEEDED = 3
    FAILED = 4
    CANCELED = 5
    TIMEOUT = 6


CALLSTATUS_NAMES: dict[int, str] = {0: "accepted", 1: "rejected", 2: "running", 3: "succeeded", 4: "failed", 5: "canceled", 6: "timeout"}
CALLSTATUS_BY_NAME: dict[str, int] = {"accepted": 0, "rejected": 1, "running": 2, "succeeded": 3, "failed": 4, "canceled": 5, "timeout": 6}


class ProgressPhase(IntEnum):
    ADMITTED = 0
    PLANNING = 1
    EXECUTING = 2
    PAUSED = 3


PROGRESSPHASE_NAMES: dict[int, str] = {0: "admitted", 1: "planning", 2: "executing", 3: "paused"}
PROGRESSPHASE_BY_NAME: dict[str, int] = {"admitted": 0, "planning": 1, "executing": 2, "paused": 3}


class EffectStatus(IntEnum):
    OK = 0
    UNVERIFIED = 1
    FAILED = 2
    UNAVAILABLE = 3
    PAYMENT_REQUIRED = 4


EFFECTSTATUS_NAMES: dict[int, str] = {0: "OK", 1: "UNVERIFIED", 2: "FAILED", 3: "UNAVAILABLE", 4: "PAYMENT_REQUIRED"}
EFFECTSTATUS_BY_NAME: dict[str, int] = {"OK": 0, "UNVERIFIED": 1, "FAILED": 2, "UNAVAILABLE": 3, "PAYMENT_REQUIRED": 4}


class VerifyTrust(IntEnum):
    V0 = 0
    V1 = 1
    V2 = 2
    V3 = 3
    V4 = 4


VERIFYTRUST_NAMES: dict[int, str] = {0: "V0", 1: "V1", 2: "V2", 3: "V3", 4: "V4"}
VERIFYTRUST_BY_NAME: dict[str, int] = {"V0": 0, "V1": 1, "V2": 2, "V3": 3, "V4": 4}


class TimeState(IntEnum):
    STOPPED = 0
    PLAYING = 1
    PAUSED = 2
    STEPPING = 3
    BUFFERING = 4
    ENDED = 5
    STALLED = 6
    RESTARTING = 7
    FAILED = 8
    LIVE = 9


TIMESTATE_NAMES: dict[int, str] = {0: "STOPPED", 1: "PLAYING", 2: "PAUSED", 3: "STEPPING", 4: "BUFFERING", 5: "ENDED", 6: "STALLED", 7: "RESTARTING", 8: "FAILED", 9: "LIVE"}
TIMESTATE_BY_NAME: dict[str, int] = {"STOPPED": 0, "PLAYING": 1, "PAUSED": 2, "STEPPING": 3, "BUFFERING": 4, "ENDED": 5, "STALLED": 6, "RESTARTING": 7, "FAILED": 8, "LIVE": 9}


class TimeFlags(IntFlag):
    STATE_MASK = 15
    REPLAY = 128


TIMEFLAGS_NAMES: dict[int, str] = {15: "STATE_MASK", 128: "REPLAY"}
TIMEFLAGS_BY_NAME: dict[str, int] = {"STATE_MASK": 15, "REPLAY": 128}


class Kind(IntEnum):
    UAV = 0
    UGV = 1
    ROBOT = 2
    VEHICLE = 3
    SENSOR = 4
    HUMAN = 5


KIND_NAMES: dict[int, str] = {0: "uav", 1: "ugv", 2: "robot", 3: "vehicle", 4: "sensor", 5: "human"}
KIND_BY_NAME: dict[str, int] = {"uav": 0, "ugv": 1, "robot": 2, "vehicle": 3, "sensor": 4, "human": 5}


class ScaleStatus(IntEnum):
    RELATIVE = 0
    ASSUMED = 1
    LANDMARK = 2
    GNSS = 3
    LIDAR = 4
    RTK = 5
    SURVEY = 6


SCALESTATUS_NAMES: dict[int, str] = {0: "relative", 1: "assumed", 2: "landmark", 3: "gnss", 4: "lidar", 5: "rtk", 6: "survey"}
SCALESTATUS_BY_NAME: dict[str, int] = {"relative": 0, "assumed": 1, "landmark": 2, "gnss": 3, "lidar": 4, "rtk": 5, "survey": 6}


class EnvFlags(IntFlag):
    VALID = 1
    IN_SOLID = 2
    OUTSIDE_GRID = 4
    ABOVE_GRID = 8
    IN_FOG_LAYER = 16
    BELOW_CLOUD_PRECIP = 32
    CALM = 64


ENVFLAGS_NAMES: dict[int, str] = {1: "VALID", 2: "IN_SOLID", 4: "OUTSIDE_GRID", 8: "ABOVE_GRID", 16: "IN_FOG_LAYER", 32: "BELOW_CLOUD_PRECIP", 64: "CALM"}
ENVFLAGS_BY_NAME: dict[str, int] = {"VALID": 1, "IN_SOLID": 2, "OUTSIDE_GRID": 4, "ABOVE_GRID": 8, "IN_FOG_LAYER": 16, "BELOW_CLOUD_PRECIP": 32, "CALM": 64}


class EnvSourceLevel(IntEnum):
    ANALYTIC_L0 = 0
    ANALYTIC_L1 = 1
    MASSCONS_LIBRARY = 2
    CFD_LIBRARY = 3
    LBM_FRAME = 4


ENVSOURCELEVEL_NAMES: dict[int, str] = {0: "ANALYTIC_L0", 1: "ANALYTIC_L1", 2: "MASSCONS_LIBRARY", 3: "CFD_LIBRARY", 4: "LBM_FRAME"}
ENVSOURCELEVEL_BY_NAME: dict[str, int] = {"ANALYTIC_L0": 0, "ANALYTIC_L1": 1, "MASSCONS_LIBRARY": 2, "CFD_LIBRARY": 3, "LBM_FRAME": 4}


class EnvFields(IntFlag):
    WIND = 1
    WIND_PARTS = 2
    TURB_SPEC = 4
    OPTICS = 8
    PRECIP = 16
    THERMO = 32
    DEFAULT = 41


ENVFIELDS_NAMES: dict[int, str] = {1: "WIND", 2: "WIND_PARTS", 4: "TURB_SPEC", 8: "OPTICS", 16: "PRECIP", 32: "THERMO", 41: "DEFAULT"}
ENVFIELDS_BY_NAME: dict[str, int] = {"WIND": 1, "WIND_PARTS": 2, "TURB_SPEC": 4, "OPTICS": 8, "PRECIP": 16, "THERMO": 32, "DEFAULT": 41}


class EnvQueryFrame(IntEnum):
    GLOBAL = 0
    LOCAL = 1
    ADD_VELOCITY_GLOBAL = 2
    ADD_VELOCITY_LOCAL = 3


ENVQUERYFRAME_NAMES: dict[int, str] = {0: "GLOBAL", 1: "LOCAL", 2: "ADD_VELOCITY_GLOBAL", 3: "ADD_VELOCITY_LOCAL"}
ENVQUERYFRAME_BY_NAME: dict[str, int] = {"GLOBAL": 0, "LOCAL": 1, "ADD_VELOCITY_GLOBAL": 2, "ADD_VELOCITY_LOCAL": 3}


class EnvMode(IntEnum):
    SMOOTH = 0
    EXP = 1
    STEP = 2


ENVMODE_NAMES: dict[int, str] = {0: "smooth", 1: "exp", 2: "step"}
ENVMODE_BY_NAME: dict[str, int] = {"smooth": 0, "exp": 1, "step": 2}


class SensorKind(IntEnum):
    CAMERA = 0
    LIDAR = 1
    THERMAL = 2
    RADAR = 3
    GNSS = 4
    IMU = 5
    BARO = 6


SENSORKIND_NAMES: dict[int, str] = {0: "camera", 1: "lidar", 2: "thermal", 3: "radar", 4: "gnss", 5: "imu", 6: "baro"}
SENSORKIND_BY_NAME: dict[str, int] = {"camera": 0, "lidar": 1, "thermal": 2, "radar": 3, "gnss": 4, "imu": 5, "baro": 6}


class Encoding(IntEnum):
    RAW = 0
    MSGPACK = 1
    JSON = 2
    BLOB = 3


ENCODING_NAMES: dict[int, str] = {0: "raw", 1: "msgpack", 2: "json", 3: "blob"}
ENCODING_BY_NAME: dict[str, int] = {"raw": 0, "msgpack": 1, "json": 2, "blob": 3}


class EventLevel(IntEnum):
    INFO = 0
    NOTICE = 1
    WARNING = 2
    CRITICAL = 3


EVENTLEVEL_NAMES: dict[int, str] = {0: "INFO", 1: "NOTICE", 2: "WARNING", 3: "CRITICAL"}
EVENTLEVEL_BY_NAME: dict[str, int] = {"INFO": 0, "NOTICE": 1, "WARNING": 2, "CRITICAL": 3}


class SetpointFrame(IntEnum):
    WORLD = 0
    BODY = 1


SETPOINTFRAME_NAMES: dict[int, str] = {0: "world", 1: "body"}
SETPOINTFRAME_BY_NAME: dict[str, int] = {"world": 0, "body": 1}


class CursorMode(IntEnum):
    FREE = 0
    LOSSY = 1
    LOSSLESS = 2


CURSORMODE_NAMES: dict[int, str] = {0: "FREE", 1: "LOSSY", 2: "LOSSLESS"}
CURSORMODE_BY_NAME: dict[str, int] = {"FREE": 0, "LOSSY": 1, "LOSSLESS": 2}


class AwrtDir(IntEnum):
    S2C = 0
    C2S = 1


AWRTDIR_NAMES: dict[int, str] = {0: "s2c", 1: "c2s"}
AWRTDIR_BY_NAME: dict[str, int] = {"s2c": 0, "c2s": 1}


class AwrtKind(IntEnum):
    TEXT = 0
    BINARY = 1


AWRTKIND_NAMES: dict[int, str] = {0: "text", 1: "binary"}
AWRTKIND_BY_NAME: dict[str, int] = {"text": 0, "binary": 1}


class BlobDtype(IntEnum):
    F16 = 1
    F32 = 2
    U8 = 3
    I16 = 4


BLOBDTYPE_NAMES: dict[int, str] = {1: "f16", 2: "f32", 3: "u8", 4: "i16"}
BLOBDTYPE_BY_NAME: dict[str, int] = {"f16": 1, "f32": 2, "u8": 3, "i16": 4}


class AwrvKind(IntEnum):
    WIND_SECTOR = 1
    TURB_BOX = 2
    WIND_SNAPSHOT = 3
    SCALAR_FIELD = 4
    LBM_FRAME = 5
    NOISE_FIELD = 6


AWRVKIND_NAMES: dict[int, str] = {1: "wind_sector", 2: "turb_box", 3: "wind_snapshot", 4: "scalar_field", 5: "lbm_frame", 6: "noise_field"}
AWRVKIND_BY_NAME: dict[str, int] = {"wind_sector": 1, "turb_box": 2, "wind_snapshot": 3, "scalar_field": 4, "lbm_frame": 5, "noise_field": 6}


class AwrvDtype(IntEnum):
    F16 = 1
    F32 = 2
    U8 = 3


AWRVDTYPE_NAMES: dict[int, str] = {1: "f16", 2: "f32", 3: "u8"}
AWRVDTYPE_BY_NAME: dict[str, int] = {"f16": 1, "f32": 2, "u8": 3}


class AwrvAlpha(IntEnum):
    NONE = 0
    SOLID_FRAC = 1
    SPEED = 2
    SIGMA = 3


AWRVALPHA_NAMES: dict[int, str] = {0: "none", 1: "solid_frac", 2: "speed", 3: "sigma"}
AWRVALPHA_BY_NAME: dict[str, int] = {"none": 0, "solid_frac": 1, "speed": 2, "sigma": 3}


class Role(IntEnum):
    VIEWER = 0
    OPERATOR = 1
    ADMIN = 2
    AGENT = 3


ROLE_NAMES: dict[int, str] = {0: "viewer", 1: "operator", 2: "admin", 3: "agent"}
ROLE_BY_NAME: dict[str, int] = {"viewer": 0, "operator": 1, "admin": 2, "agent": 3}


class Entry(IntEnum):
    API = 0
    AGENT_RUNTIME = 1
    SCENARIO = 2


ENTRY_NAMES: dict[int, str] = {0: "api", 1: "agent-runtime", 2: "scenario"}
ENTRY_BY_NAME: dict[str, int] = {"api": 0, "agent-runtime": 1, "scenario": 2}


class SeatState(IntEnum):
    FREE = 0
    HELD = 1
    GRACE = 2


SEATSTATE_NAMES: dict[int, str] = {0: "FREE", 1: "HELD", 2: "GRACE"}
SEATSTATE_BY_NAME: dict[str, int] = {"FREE": 0, "HELD": 1, "GRACE": 2}


class GcsLossPolicy(IntEnum):
    HOLD_RTL = 0
    IGNORE = 1


GCSLOSSPOLICY_NAMES: dict[int, str] = {0: "hold_rtl", 1: "ignore"}
GCSLOSSPOLICY_BY_NAME: dict[str, int] = {"hold_rtl": 0, "ignore": 1}


class TopicKind(IntEnum):
    STATE = 0
    EVENT = 1
    BLOB = 2
    ROSTER = 3


TOPICKIND_NAMES: dict[int, str] = {0: "state", 1: "event", 2: "blob", 3: "roster"}
TOPICKIND_BY_NAME: dict[str, int] = {"state": 0, "event": 1, "blob": 2, "roster": 3}


class SubMode(IntEnum):
    LATEST = 0
    ALL = 1
    M4 = 2


SUBMODE_NAMES: dict[int, str] = {0: "latest", 1: "all", 2: "m4"}
SUBMODE_BY_NAME: dict[str, int] = {"latest": 0, "all": 1, "m4": 2}


class PlaybackStatus(IntEnum):
    IDLE = 0
    OPENING = 1
    PLAYING = 2
    PAUSED = 3
    BUFFERING = 4
    ENDED = 5
    ERROR = 6


PLAYBACKSTATUS_NAMES: dict[int, str] = {0: "idle", 1: "opening", 2: "playing", 3: "paused", 4: "buffering", 5: "ended", 6: "error"}
PLAYBACKSTATUS_BY_NAME: dict[str, int] = {"idle": 0, "opening": 1, "playing": 2, "paused": 3, "buffering": 4, "ended": 5, "error": 6}


class SessionState(IntEnum):
    CREATED = 0
    PREPARING = 1
    READY = 2
    PLAYING = 3
    PAUSED = 4
    STEPPING = 5
    LIVE = 6
    RESETTING = 7
    RECOVERING = 8
    REPLAY = 9
    CLOSING = 10
    CLOSED = 11
    FAILED = 12


SESSIONSTATE_NAMES: dict[int, str] = {0: "CREATED", 1: "PREPARING", 2: "READY", 3: "PLAYING", 4: "PAUSED", 5: "STEPPING", 6: "LIVE", 7: "RESETTING", 8: "RECOVERING", 9: "REPLAY", 10: "CLOSING", 11: "CLOSED", 12: "FAILED"}
SESSIONSTATE_BY_NAME: dict[str, int] = {"CREATED": 0, "PREPARING": 1, "READY": 2, "PLAYING": 3, "PAUSED": 4, "STEPPING": 5, "LIVE": 6, "RESETTING": 7, "RECOVERING": 8, "REPLAY": 9, "CLOSING": 10, "CLOSED": 11, "FAILED": 12}


class WorldStatus(IntEnum):
    ABSENT = 0
    BUILDING = 1
    READY = 2
    INVALID = 3


WORLDSTATUS_NAMES: dict[int, str] = {0: "ABSENT", 1: "BUILDING", 2: "READY", 3: "INVALID"}
WORLDSTATUS_BY_NAME: dict[str, int] = {"ABSENT": 0, "BUILDING": 1, "READY": 2, "INVALID": 3}


class MissionState(IntEnum):
    IDLE = 0
    RUNNING = 1
    PAUSED = 2
    DONE = 3
    ABORTED = 4


MISSIONSTATE_NAMES: dict[int, str] = {0: "IDLE", 1: "RUNNING", 2: "PAUSED", 3: "DONE", 4: "ABORTED"}
MISSIONSTATE_BY_NAME: dict[str, int] = {"IDLE": 0, "RUNNING": 1, "PAUSED": 2, "DONE": 3, "ABORTED": 4}


class TrackState(IntEnum):
    PENDING = 0
    TRANSIT = 1
    WORKING = 2
    WAITING = 3
    RETURNING = 4
    SUSPENDED = 5
    DONE = 6
    DROPPED = 7


TRACKSTATE_NAMES: dict[int, str] = {0: "PENDING", 1: "TRANSIT", 2: "WORKING", 3: "WAITING", 4: "RETURNING", 5: "SUSPENDED", 6: "DONE", 7: "DROPPED"}
TRACKSTATE_BY_NAME: dict[str, int] = {"PENDING": 0, "TRANSIT": 1, "WORKING": 2, "WAITING": 3, "RETURNING": 4, "SUSPENDED": 5, "DONE": 6, "DROPPED": 7}


class ZoneKind(IntEnum):
    BORDER = 0
    NOFLY = 1
    RESTRICTED = 2


ZONEKIND_NAMES: dict[int, str] = {0: "border", 1: "nofly", 2: "restricted"}
ZONEKIND_BY_NAME: dict[str, int] = {"border": 0, "nofly": 1, "restricted": 2}


class FaultKind(IntEnum):
    THRUST_LOSS = 0
    MOTOR_FAIL = 1
    LINK_DROP = 2
    STATE_DROP = 3
    GNSS_DENIED = 4
    BATTERY_DRAIN = 5


FAULTKIND_NAMES: dict[int, str] = {0: "thrust_loss", 1: "motor_fail", 2: "link_drop", 3: "state_drop", 4: "gnss_denied", 5: "battery_drain"}
FAULTKIND_BY_NAME: dict[str, int] = {"thrust_loss": 0, "motor_fail": 1, "link_drop": 2, "state_drop": 3, "gnss_denied": 4, "battery_drain": 5}


class SafetyClass(IntEnum):
    INFO = 0
    WARN = 1
    ACTION = 2
    CRITICAL = 3


SAFETYCLASS_NAMES: dict[int, str] = {0: "info", 1: "warn", 2: "action", 3: "critical"}
SAFETYCLASS_BY_NAME: dict[str, int] = {"info": 0, "warn": 1, "action": 2, "critical": 3}


class SafetyOrigin(IntEnum):
    SYSTEM = 0
    AUTO = 1
    OPERATOR = 2


SAFETYORIGIN_NAMES: dict[int, str] = {0: "SYSTEM", 1: "AUTO", 2: "OPERATOR"}
SAFETYORIGIN_BY_NAME: dict[str, int] = {"SYSTEM": 0, "AUTO": 1, "OPERATOR": 2}


class RecSegmentState(IntEnum):
    OPEN = 0
    CLOSED = 1
    CORRUPT = 2


RECSEGMENTSTATE_NAMES: dict[int, str] = {0: "OPEN", 1: "CLOSED", 2: "CORRUPT"}
RECSEGMENTSTATE_BY_NAME: dict[str, int] = {"OPEN": 0, "CLOSED": 1, "CORRUPT": 2}


class AgentTaskState(IntEnum):
    SUBMITTED = 0
    WORKING = 1
    INPUT_REQUIRED = 2
    COMPLETED = 3
    CANCELED = 4
    FAILED = 5
    REJECTED = 6


AGENTTASKSTATE_NAMES: dict[int, str] = {0: "submitted", 1: "working", 2: "input-required", 3: "completed", 4: "canceled", 5: "failed", 6: "rejected"}
AGENTTASKSTATE_BY_NAME: dict[str, int] = {"submitted": 0, "working": 1, "input-required": 2, "completed": 3, "canceled": 4, "failed": 5, "rejected": 6}


class Timescale(IntEnum):
    UTC = 0
    TAI = 1
    GPST = 2
    HOST_MONO = 3


TIMESCALE_NAMES: dict[int, str] = {0: "utc", 1: "tai", 2: "gpst", 3: "host_mono"}
TIMESCALE_BY_NAME: dict[str, int] = {"utc": 0, "tai": 1, "gpst": 2, "host_mono": 3}


class SyncType(IntEnum):
    PTP = 0
    GPS_PPS = 1
    PX4_TIMESYNC = 2
    NONE = 3
    SIM = 4


SYNCTYPE_NAMES: dict[int, str] = {0: "ptp", 1: "gps_pps", 2: "px4_timesync", 3: "none", 4: "sim"}
SYNCTYPE_BY_NAME: dict[str, int] = {"ptp": 0, "gps_pps": 1, "px4_timesync": 2, "none": 3, "sim": 4}


class CommandCategory(IntEnum):
    NAV = 0
    NAV_SETUP = 1
    NAV_STREAM = 2
    SAFETY = 3
    SAFETY_LIGHT = 4
    SAFETY_LOCK = 5
    MISSION = 6
    TASK_OR_UNLOCK = 7
    SETUP = 8
    CALL_CONTROL = 9
    LEASE = 10
    BATCH = 11
    CLOCK = 12
    ENV = 13
    QUERY = 14
    SEAT = 15
    CONFIRM = 16
    REC = 17
    FLEET = 18


COMMANDCATEGORY_NAMES: dict[int, str] = {0: "nav", 1: "nav_setup", 2: "nav_stream", 3: "safety", 4: "safety_light", 5: "safety_lock", 6: "mission", 7: "task_or_unlock", 8: "setup", 9: "call_control", 10: "lease", 11: "batch", 12: "clock", 13: "env", 14: "query", 15: "seat", 16: "confirm", 17: "rec", 18: "fleet"}
COMMANDCATEGORY_BY_NAME: dict[str, int] = {"nav": 0, "nav_setup": 1, "nav_stream": 2, "safety": 3, "safety_light": 4, "safety_lock": 5, "mission": 6, "task_or_unlock": 7, "setup": 8, "call_control": 9, "lease": 10, "batch": 11, "clock": 12, "env": 13, "query": 14, "seat": 15, "confirm": 16, "rec": 17, "fleet": 18}


class GnssFix(IntEnum):
    NO_FIX = 0
    SINGLE = 1
    DGPS = 2
    RTK_FLOAT = 3
    RTK_FIXED = 4


GNSSFIX_NAMES: dict[int, str] = {0: "NO_FIX", 1: "SINGLE", 2: "DGPS", 3: "RTK_FLOAT", 4: "RTK_FIXED"}
GNSSFIX_BY_NAME: dict[str, int] = {"NO_FIX": 0, "SINGLE": 1, "DGPS": 2, "RTK_FLOAT": 3, "RTK_FIXED": 4}


class GimbalMode(IntEnum):
    FIXED = 0
    LOOK_AT = 1
    LOOK_AT_AXIS = 2
    NADIR = 3
    FORWARD = 4


GIMBALMODE_NAMES: dict[int, str] = {0: "fixed", 1: "look_at", 2: "look_at_axis", 3: "nadir", 4: "forward"}
GIMBALMODE_BY_NAME: dict[str, int] = {"fixed": 0, "look_at": 1, "look_at_axis": 2, "nadir": 3, "forward": 4}


class ReconEngine(IntEnum):
    MOCK = 0
    DA3 = 1
    LINGBOT_MAP = 2
    VGGT = 3
    MAPANYTHING = 4
    COLMAP = 5


RECONENGINE_NAMES: dict[int, str] = {0: "mock", 1: "da3", 2: "lingbot_map", 3: "vggt", 4: "mapanything", 5: "colmap"}
RECONENGINE_BY_NAME: dict[str, int] = {"mock": 0, "da3": 1, "lingbot_map": 2, "vggt": 3, "mapanything": 4, "colmap": 5}


class ReconStage(IntEnum):
    PREPARING = 0
    SEGMENTING = 1
    INFERRING = 2
    FUSING = 3
    GEOREFERENCING = 4
    TILING = 5
    PACKAGING = 6


RECONSTAGE_NAMES: dict[int, str] = {0: "PREPARING", 1: "SEGMENTING", 2: "INFERRING", 3: "FUSING", 4: "GEOREFERENCING", 5: "TILING", 6: "PACKAGING"}
RECONSTAGE_BY_NAME: dict[str, int] = {"PREPARING": 0, "SEGMENTING": 1, "INFERRING": 2, "FUSING": 3, "GEOREFERENCING": 4, "TILING": 5, "PACKAGING": 6}


# FlightSub: 3-bit sub-mode names per FlightState (None = reserved slot)
FLIGHT_SUB: dict[int, tuple[str | None, ...]] = {
    0: ("NO_DATA", "BOOTING", "LINK_LOST", "RESTARTING", "FAILED"),
    1: ("READY_TO_ARM", "NOT_READY", "KILLED"),
    2: ("CHECKING", "COUNTDOWN"),
    3: ("IDLE",),
    4: ("SPOOLUP", "CLIMB"),
    5: ("HOVER", "GOTO", "PATH", "ORBIT", "VELOCITY", "SWARM", "MANUAL", "EXTERNAL"),
    6: ("GEOFENCE", "ALT_MAX", "ALT_MIN", "BUMPER", "SEPARATION"),
    7: ("SAFETY_STOP", "LINK_LOSS", "ESCALATE", "SEPARATION", "LOC_LOST", "AUTOPILOT", None, "OTHER"),
    8: ("CLIMB", "CRUISE", "DESCEND", "FINAL", None, None, None, "OPAQUE"),
    9: ("DESCEND", "GOTO", "TOUCHDOWN"),
    10: ("CONTROLLED", "NO_POSITION"),
    11: ("DESCENT", "TERMINATION"),
    12: ("SETTLING",),
    13: ("TILT", "COLLISION_WORLD", "COLLISION_UAV", "IMPACT"),
}

SEVERITY: dict[int, int] = {FlightState.TAKING_OFF: 0, FlightState.FLYING: 0, FlightState.CORRECTING: 1, FlightState.HOLD: 2, FlightState.RTL: 3, FlightState.LANDING: 4, FlightState.ELAND: 5, FlightState.FAILSAFE: 6, FlightState.CRASHED: 8}

JOB_STATE: dict[str, tuple[str, ...]] = {"recon": ("QUEUED", "PREPARING", "SEGMENTING", "INFERRING", "FUSING", "GEOREFERENCING", "TILING", "PACKAGING", "SUCCEEDED", "FAILED", "CANCELLED"), "world_build": ("QUEUED", "INGESTING", "TILING", "DERIVING", "VALIDATING", "PUBLISHING", "SUCCEEDED", "FAILED", "CANCELLED")}


def sub_name(fs: int, sub: int) -> str | None:
    names = FLIGHT_SUB.get(fs, ())
    return names[sub] if 0 <= sub < len(names) else None


def sub_value(fs: int, name: str) -> int:
    return FLIGHT_SUB[fs].index(name)


def time_state(state_byte: int) -> TimeState:
    """Low 4 bits of TIME.state / clock_state; bit7 (REPLAY) is masked (AWR-03 §5.2 rule 6)."""
    return TimeState(state_byte & TimeFlags.STATE_MASK)


def time_is_replay(state_byte: int) -> bool:
    return bool(state_byte & TimeFlags.REPLAY)


def time_advances(state_byte: int) -> bool:
    """SimClockView advances only in PLAYING and LIVE; every other state freezes."""
    return time_state(state_byte) in (TimeState.PLAYING, TimeState.LIVE)


def red_highlight(fs: int, flags: int) -> bool:
    """Swarm-wide red highlight: CORRECTING <= fs <= CRASHED and fs != LANDED, or ALERT (g04 §5.4)."""
    return (FlightState.CORRECTING <= fs <= FlightState.CRASHED and fs != FlightState.LANDED) or bool(flags & FlightFlags.ALERT)
