"""awr.rt.v1 frame codecs: struct formats, opcodes, flag bits, TIME and BATCH helpers (AWR-17 §6.4).

Generated by tools/contracts/gen.py from packages/contracts. Do not edit."""

from __future__ import annotations

import struct
from collections.abc import Iterator
from typing import NamedTuple

from .enums import TimeFlags, TimeState

STRUCT_FORMATS: dict[str, str] = {
    "awr.DroneState64.v1": "<HBBHBB3f3f4f3fi",
    "awr.SwarmLite32.v1": "<HBB3f4h3hBB",
    "awr.EnvSample32.v1": "<3f3h2BfHHBBh",
    "awr.VelSetpoint16.v1": "<3ff",
    "awr.SensorPose48.v1": "<HBBB3B3f4ffff",
    "awr.SwarmLite32Block.v1": "<IIQ",
    "awr.rt.BatchHeader.v1": "<BBHIq",
    "awr.rt.RecordHeader.v1": "<HBBIIi",
    "awr.rt.Time.v1": "<BBHfqq",
    "awr.rt.ClientDataHeader.v1": "<BBHIq",
    "awr.bus.Setpoint32.v1": "<HBBIq3ff",
    "awr.rec.RecPrefix8.v1": "<HBBi",
    "awr.fixture.AwrtHeader.v1": "<IHHIIQ",
    "awr.fixture.AwrtRecord.v1": "<BBHIQ",
    "awr.blob.Header.v1": "<IHHII",
    "awr.env.AwrvHeader.v1": "<IHHHHHHBBBB3f3fffIII",
    "awr.env.AwslHeader.v1": "<IHHIIffIIffII",
    "awr.recon.AwtrHeader.v1": "<IHHIIqQ",
    "awr.ipc.RingHeader.v1": "<IHHIIIIIIQqqiB3BIIqQIIIIIIQII128B",
    "awr.ipc.ReaderCursor.v1": "<IIQqII",
    "awr.ipc.SlotHeader.v1": "<QQqqIIIIIIII",
    "awr.ipc.Heartbeat16.v1": "<qII",
}
STRUCTS: dict[str, struct.Struct] = {k: struct.Struct(v) for k, v in STRUCT_FORMATS.items()}

FRAME_HDR = STRUCTS["awr.rt.BatchHeader.v1"]
REC_HDR = STRUCTS["awr.rt.RecordHeader.v1"]
TIME = STRUCTS["awr.rt.Time.v1"]
CLIENT_DATA_HDR = STRUCTS["awr.rt.ClientDataHeader.v1"]
SETPOINT32 = STRUCTS["awr.bus.Setpoint32.v1"]
VEL_SETPOINT16 = STRUCTS["awr.VelSetpoint16.v1"]
REC_PREFIX8 = STRUCTS["awr.rec.RecPrefix8.v1"]
AWRT_HDR = STRUCTS["awr.fixture.AwrtHeader.v1"]
AWRT_REC = STRUCTS["awr.fixture.AwrtRecord.v1"]
BLOB_HDR = STRUCTS["awr.blob.Header.v1"]
SWARM_BLOCK_HDR = STRUCTS["awr.SwarmLite32Block.v1"]
AWRV_HDR = STRUCTS["awr.env.AwrvHeader.v1"]
AWSL_HDR = STRUCTS["awr.env.AwslHeader.v1"]
AWTR_HDR = STRUCTS["awr.recon.AwtrHeader.v1"]
HEARTBEAT16 = STRUCTS["awr.ipc.Heartbeat16.v1"]
SETPOINT_BUS = struct.Struct("<HBBIq")  # header part of awr.bus.Setpoint32.v1 (M11 §6.3.9)
assert SETPOINT_BUS.size + VEL_SETPOINT16.size == SETPOINT32.size

OP_TIME = 0x02
OP_BATCH = 0x10
OP_CLIENT_DATA = 0x20

BATCH_SNAPSHOT = 0x01
BATCH_REPLAY = 0x02
BATCH_ZSTD = 0x04
BATCH_GAP = 0x08

RF_KEYFRAME = 0x01
RF_DELTA = 0x02
RF_ZSTD = 0x04
RF_RESET = 0x08

CD_FINAL = 0x01

ENC_RAW = 0
ENC_MSGPACK = 1
ENC_JSON = 2
ENC_BLOB = 3

TIME_REPLAY_BIT = int(TimeFlags.REPLAY)


def pad8(n: int) -> int:
    return (n + 7) & ~7


class TimeFrame(NamedTuple):
    state: int
    replay: bool
    epoch: int
    rate: float
    t_sim_ns: int
    t_srv_ns: int


def encode_time(state: int, epoch: int, rate: float, t_sim_ns: int, t_srv_ns: int, replay: bool = False) -> bytes:
    b = (int(state) & 0x0F) | (TIME_REPLAY_BIT if replay else 0)
    return TIME.pack(OP_TIME, b, epoch & 0xFFFF, rate, t_sim_ns, t_srv_ns)


def decode_time(buf: bytes | memoryview, off: int = 0) -> TimeFrame:
    op, st, epoch, rate, t_sim, t_srv = TIME.unpack_from(buf, off)
    if op != OP_TIME:
        raise ValueError(f"not a TIME frame: op=0x{op:02x}")
    return TimeFrame(st & 0x0F, bool(st & TIME_REPLAY_BIT), epoch, rate, t_sim, t_srv)


def time_advances(frame: TimeFrame) -> bool:
    return frame.state in (TimeState.PLAYING, TimeState.LIVE)


class BatchHeader(NamedTuple):
    flags: int
    epoch: int
    frame_seq: int
    t_sim_ns: int


class Record(NamedTuple):
    channel_id: int
    encoding: int
    rflags: int
    length: int
    seq: int
    dt_us: int
    payload_off: int


def decode_batch_header(buf: bytes | memoryview) -> BatchHeader:
    op, flags, epoch, frame_seq, t_sim = FRAME_HDR.unpack_from(buf, 0)
    if op != OP_BATCH:
        raise ValueError(f"not a BATCH frame: op=0x{op:02x}")
    return BatchHeader(flags, epoch, frame_seq, t_sim)


def iter_records(buf: bytes | memoryview, off: int = 16) -> Iterator[Record]:
    """Walk BATCH records; unknown encodings are yielded too (callers skip them). Raises on truncation."""
    n = len(buf)
    while off < n:
        if off + REC_HDR.size > n:
            raise ValueError("truncated record header")
        ch, enc, rf, length, seq, dt = REC_HDR.unpack_from(buf, off)
        p = off + REC_HDR.size
        if p + length > n:
            raise ValueError("truncated record payload")
        yield Record(ch, enc, rf, length, seq, dt, p)
        off = p + pad8(length)


def encode_record(channel_id: int, encoding: int, rflags: int, seq: int, dt_us: int, payload: bytes) -> bytes:
    n = len(payload)
    return REC_HDR.pack(channel_id, encoding, rflags, n, seq & 0xFFFFFFFF, dt_us) + payload + b"\0" * (pad8(n) - n)


def encode_batch(flags: int, epoch: int, frame_seq: int, t_sim_ns: int, records: list[bytes]) -> bytes:
    return FRAME_HDR.pack(OP_BATCH, flags, epoch & 0xFFFF, frame_seq & 0xFFFFFFFF, t_sim_ns) + b"".join(records)


# ---------------------------------------------------------------- .awrrt protocol fixtures (AWR-16 §13.9)
AWRT_MAGIC = 1414682433
AWRT_VERSION = 1
AWRT_TIMED = 0x01
AWRT_S2C, AWRT_C2S = 0, 1
AWRT_TEXT, AWRT_BINARY = 0, 1


class AwrtRecord(NamedTuple):
    dir: int
    kind: int
    t_rel_ns: int
    payload: bytes


class Awrrt(NamedTuple):
    flags: int
    t0_wall_ns: int
    header: dict
    records: list[AwrtRecord]


def write_awrrt(header: dict, records: list[AwrtRecord], flags: int = AWRT_TIMED, t0_wall_ns: int = 0) -> bytes:
    """Header JSON is written with sorted keys and no whitespace so fixtures are byte-reproducible."""
    import json

    hj = json.dumps(header, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()
    parts = [AWRT_HDR.pack(AWRT_MAGIC, AWRT_VERSION, flags, len(hj), 0, t0_wall_ns), hj, b"\0" * (pad8(len(hj)) - len(hj))]
    last = -1
    for r in records:
        if r.t_rel_ns < last:
            raise ValueError("t_rel_ns must be monotonic")
        last = r.t_rel_ns
        n = len(r.payload)
        parts += [AWRT_REC.pack(r.dir, r.kind, 0, n, r.t_rel_ns), bytes(r.payload), b"\0" * (pad8(n) - n)]
    return b"".join(parts)


def read_awrrt(buf: bytes | memoryview) -> Awrrt:
    import json

    magic, version, flags, hlen, _res, t0 = AWRT_HDR.unpack_from(buf, 0)
    if magic != AWRT_MAGIC or version != AWRT_VERSION:
        raise ValueError(f"not an .awrrt v1 file: magic=0x{magic:08x} version={version}")
    off = AWRT_HDR.size
    header = json.loads(bytes(buf[off:off + hlen]).decode("utf-8"))
    off += pad8(hlen)
    recs: list[AwrtRecord] = []
    n = len(buf)
    while off < n:
        if off + AWRT_REC.size > n:
            raise ValueError("truncated .awrrt record header")
        d, k, _r, length, t_rel = AWRT_REC.unpack_from(buf, off)
        p = off + AWRT_REC.size
        if p + length > n:
            raise ValueError("truncated .awrrt record payload")
        recs.append(AwrtRecord(d, k, t_rel, bytes(buf[p:p + length])))
        off = p + pad8(length)
    return Awrrt(flags, t0, header, recs)
