"""Binary layouts from packages/contracts/rt/layouts.json: numpy dtypes, offsets, bit fields (AWR-17 §10.3, §10.4).

Generated by tools/contracts/gen.py from packages/contracts. Do not edit."""

from __future__ import annotations

import numpy as np

LAYOUT_ID = 0x3D5E08D0
SCHEMA_HASH: dict[str, str] = {
    "awr.DroneState64.v1": "b469b083",
    "awr.SwarmLite32.v1": "8ec882b6",
    "awr.EnvSample32.v1": "a9305d06",
    "awr.VelSetpoint16.v1": "d28ee0d9",
    "awr.SensorPose48.v1": "ecdf1b81",
    "awr.SwarmLite32Block.v1": "5234592a",
    "awr.rt.BatchHeader.v1": "0190531c",
    "awr.rt.RecordHeader.v1": "33c04dbc",
    "awr.rt.Time.v1": "ab634999",
    "awr.rt.ClientDataHeader.v1": "c699eff9",
    "awr.bus.Setpoint32.v1": "96005d59",
    "awr.rec.RecPrefix8.v1": "9a548a6e",
    "awr.fixture.AwrtHeader.v1": "be2d4df9",
    "awr.fixture.AwrtRecord.v1": "b6f9b3be",
    "awr.blob.Header.v1": "96b62dfb",
    "awr.env.AwrvHeader.v1": "80af8588",
    "awr.env.AwslHeader.v1": "58badce4",
    "awr.recon.AwtrHeader.v1": "c09f94c9",
    "awr.ipc.RingHeader.v1": "99392a79",
    "awr.ipc.ReaderCursor.v1": "09ba61b1",
    "awr.ipc.SlotHeader.v1": "4e6ef433",
    "awr.ipc.Heartbeat16.v1": "420007cc",
}

# awr.DroneState64.v1 (64 B): Full64: single vehicle full-precision state (topic uav/{id}/state; StateRing full region).
DRONE_STATE64 = np.dtype({
    "names": ["agent_no", "flight_state", "flags", "mission_item", "battery_pct", "ctrl", "pos", "vel", "q", "omega", "dt_us"],
    "formats": ["<u2", "u1", "u1", "<u2", "u1", "u1", ("<f4", 3), ("<f4", 3), ("<f4", 4), ("<f4", 3), "<i4"],
    "offsets": [0, 2, 3, 4, 6, 7, 8, 20, 32, 48, 60],
    "itemsize": 64,
})
assert DRONE_STATE64.itemsize == 64
DRONE_STATE64_OFFSETS: dict[str, int] = {"agent_no": 0, "flight_state": 2, "flags": 3, "mission_item": 4, "battery_pct": 6, "ctrl": 7, "pos": 8, "vel": 20, "q": 32, "omega": 48, "dt_us": 60}
DRONE_STATE64_NONE: dict[str, int] = {"mission_item": 65535, "battery_pct": 255}
DRONE_STATE64_BITS: dict[str, dict[str, tuple]] = {"flight_state": {"state": (0, 5, "FlightState"), "sub": (5, 3, "FlightSub")}, "flags": {"armed": (0, 1), "in_air": (1, 1), "loc_ok": (2, 1), "failsafe": (3, 1), "gcs_link": (4, 1), "fcu_link": (5, 1), "loc_degraded": (6, 1), "alert": (7, 1)}, "ctrl": {"owner": (0, 3, "Owner"), "locked": (3, 1), "native": (4, 2, "Native"), "pose_src": (6, 2, "PoseSrc")}}

# awr.SwarmLite32.v1 (32 B): Lite32: one row per vehicle, n rows back to back (topic swarm/uav/state; StateRing lite region).
SWARM_LITE32 = np.dtype({
    "names": ["agent_no", "flight_state", "battery_pct", "pos", "q_snorm", "vel_cms", "flags", "ctrl"],
    "formats": ["<u2", "u1", "u1", ("<f4", 3), ("<i2", 4), ("<i2", 3), "u1", "u1"],
    "offsets": [0, 2, 3, 4, 16, 24, 30, 31],
    "itemsize": 32,
})
assert SWARM_LITE32.itemsize == 32
SWARM_LITE32_OFFSETS: dict[str, int] = {"agent_no": 0, "flight_state": 2, "battery_pct": 3, "pos": 4, "q_snorm": 16, "vel_cms": 24, "flags": 30, "ctrl": 31}
SWARM_LITE32_SCALE: dict[str, float] = {"q_snorm": 3.051850947599719e-05, "vel_cms": 0.01}
SWARM_LITE32_NONE: dict[str, int] = {"battery_pct": 255}
SWARM_LITE32_BITS: dict[str, dict[str, tuple]] = {"flight_state": {"state": (0, 5, "FlightState"), "sub": (5, 3, "FlightSub")}, "flags": {"armed": (0, 1), "in_air": (1, 1), "loc_ok": (2, 1), "failsafe": (3, 1), "gcs_link": (4, 1), "fcu_link": (5, 1), "loc_degraded": (6, 1), "alert": (7, 1)}, "ctrl": {"owner": (0, 3, "Owner"), "locked": (3, 1), "native": (4, 2, "Native"), "pose_src": (6, 2, "PoseSrc")}}

# awr.EnvSample32.v1 (32 B): Per-vehicle environment sample (topic uav/{id}/env; bus state/sim-core/detail).
ENV_SAMPLE32 = np.dtype({
    "names": ["wind", "wind_mean", "turb_sigma_uw", "sigma_ext", "rain_eff", "rho", "flags", "source_level", "gust"],
    "formats": [("<f4", 3), ("<i2", 3), ("u1", 2), "<f4", "<u2", "<u2", "u1", "u1", "<i2"],
    "offsets": [0, 12, 18, 20, 24, 26, 28, 29, 30],
    "itemsize": 32,
})
assert ENV_SAMPLE32.itemsize == 32
ENV_SAMPLE32_OFFSETS: dict[str, int] = {"wind": 0, "wind_mean": 12, "turb_sigma_uw": 18, "sigma_ext": 20, "rain_eff": 24, "rho": 26, "flags": 28, "source_level": 29, "gust": 30}
ENV_SAMPLE32_SCALE: dict[str, float] = {"wind_mean": 0.01, "turb_sigma_uw": 0.05, "rain_eff": 0.01, "rho": 3e-05, "gust": 0.01}
ENV_SAMPLE32_BITS: dict[str, dict[str, tuple]] = {"flags": {"valid": (0, 1), "in_solid": (1, 1), "outside_grid": (2, 1), "above_grid": (3, 1), "in_fog_layer": (4, 1), "below_cloud_precip": (5, 1), "calm": (6, 1)}}

# awr.VelSetpoint16.v1 (16 B): CLIENT_DATA payload for velocity teleoperation.
VEL_SETPOINT16 = np.dtype({
    "names": ["vel", "yaw_rate"],
    "formats": [("<f4", 3), "<f4"],
    "offsets": [0, 12],
    "itemsize": 16,
})
assert VEL_SETPOINT16.itemsize == 16
VEL_SETPOINT16_OFFSETS: dict[str, int] = {"vel": 0, "yaw_rate": 12}

# awr.SensorPose48.v1 (48 B): Sensor pose and field of view (topic uav/{id}/sensor/{name}/pose; bus state/sim-core/sensor).
SENSOR_POSE48 = np.dtype({
    "names": ["agent_no", "sensor_no", "kind", "flags", "_pad", "pos", "q", "hfov_rad", "vfov_rad", "range_m"],
    "formats": ["<u2", "u1", "u1", "u1", ("u1", 3), ("<f4", 3), ("<f4", 4), "<f4", "<f4", "<f4"],
    "offsets": [0, 2, 3, 4, 5, 8, 20, 36, 40, 44],
    "itemsize": 48,
})
assert SENSOR_POSE48.itemsize == 48
SENSOR_POSE48_OFFSETS: dict[str, int] = {"agent_no": 0, "sensor_no": 2, "kind": 3, "flags": 4, "_pad": 5, "pos": 8, "q": 20, "hfov_rad": 36, "vfov_rad": 40, "range_m": 44}
SENSOR_POSE48_BITS: dict[str, dict[str, tuple]] = {"flags": {"active": (0, 1), "fov_valid": (1, 1)}}

# awr.SwarmLite32Block.v1 (16 B): Recording block message header, followed by n awr.SwarmLite32.v1 rows sorted by agent_no (AWR-16 §13.4).
SWARM_LITE32BLOCK = np.dtype({
    "names": ["n", "roster_version", "reserved"],
    "formats": ["<u4", "<u4", "<u8"],
    "offsets": [0, 4, 8],
    "itemsize": 16,
})
assert SWARM_LITE32BLOCK.itemsize == 16
SWARM_LITE32BLOCK_OFFSETS: dict[str, int] = {"n": 0, "roster_version": 4, "reserved": 8}

# awr.rt.BatchHeader.v1 (16 B): BATCH frame header (S->C, opcode 0x10), followed by records (AWR-17 §6.4).
RT_BATCH_HEADER = np.dtype({
    "names": ["op", "flags", "epoch", "frame_seq", "t_sim_ns"],
    "formats": ["u1", "u1", "<u2", "<u4", "<i8"],
    "offsets": [0, 1, 2, 4, 8],
    "itemsize": 16,
})
assert RT_BATCH_HEADER.itemsize == 16
RT_BATCH_HEADER_OFFSETS: dict[str, int] = {"op": 0, "flags": 1, "epoch": 2, "frame_seq": 4, "t_sim_ns": 8}
RT_BATCH_HEADER_BITS: dict[str, dict[str, tuple]] = {"flags": {"snapshot": (0, 1), "replay": (1, 1), "zstd": (2, 1), "gap": (3, 1)}}
RT_BATCH_HEADER_CONST: dict[str, int] = {"op": 16}

# awr.rt.RecordHeader.v1 (16 B): BATCH record header; payload follows, zero padded to a multiple of 8 (AWR-17 §6.4).
RT_RECORD_HEADER = np.dtype({
    "names": ["channel_id", "encoding", "rflags", "length", "seq", "dt_us"],
    "formats": ["<u2", "u1", "u1", "<u4", "<u4", "<i4"],
    "offsets": [0, 2, 3, 4, 8, 12],
    "itemsize": 16,
})
assert RT_RECORD_HEADER.itemsize == 16
RT_RECORD_HEADER_OFFSETS: dict[str, int] = {"channel_id": 0, "encoding": 2, "rflags": 3, "length": 4, "seq": 8, "dt_us": 12}
RT_RECORD_HEADER_BITS: dict[str, dict[str, tuple]] = {"rflags": {"keyframe": (0, 1), "delta": (1, 1), "zstd": (2, 1), "reset": (3, 1)}}

# awr.rt.Time.v1 (24 B): TIME frame (S->C, opcode 0x02). Readers mask bit7 before comparing the state; SimClockView advances only in PLAYING and LIVE (AWR-03 §5.2 rule 6).
RT_TIME = np.dtype({
    "names": ["op", "state", "epoch", "rate", "t_sim_ns", "t_srv_ns"],
    "formats": ["u1", "u1", "<u2", "<f4", "<i8", "<i8"],
    "offsets": [0, 1, 2, 4, 8, 16],
    "itemsize": 24,
})
assert RT_TIME.itemsize == 24
RT_TIME_OFFSETS: dict[str, int] = {"op": 0, "state": 1, "epoch": 2, "rate": 4, "t_sim_ns": 8, "t_srv_ns": 16}
RT_TIME_BITS: dict[str, dict[str, tuple]] = {"state": {"state": (0, 4, "TimeState"), "replay": (7, 1)}}
RT_TIME_CONST: dict[str, int] = {"op": 2}

# awr.rt.ClientDataHeader.v1 (16 B): CLIENT_DATA frame header (C->S, opcode 0x20), followed by awr.VelSetpoint16.v1.
RT_CLIENT_DATA_HEADER = np.dtype({
    "names": ["op", "flags", "channel_id", "seq", "t_client_sim_ns"],
    "formats": ["u1", "u1", "<u2", "<u4", "<i8"],
    "offsets": [0, 1, 2, 4, 8],
    "itemsize": 16,
})
assert RT_CLIENT_DATA_HEADER.itemsize == 16
RT_CLIENT_DATA_HEADER_OFFSETS: dict[str, int] = {"op": 0, "flags": 1, "channel_id": 2, "seq": 4, "t_client_sim_ns": 8}
RT_CLIENT_DATA_HEADER_BITS: dict[str, dict[str, tuple]] = {"flags": {"final": (0, 1)}}
RT_CLIENT_DATA_HEADER_CONST: dict[str, int] = {"op": 32}

# awr.bus.Setpoint32.v1 (32 B): Raw setpoint on bus key ctl/sim-core/setpoint (AWR-17 §9.4).
BUS_SETPOINT32 = np.dtype({
    "names": ["agent_no", "flags", "frame", "seq", "t_client_sim_ns", "vel", "yaw_rate"],
    "formats": ["<u2", "u1", "u1", "<u4", "<i8", ("<f4", 3), "<f4"],
    "offsets": [0, 2, 3, 4, 8, 16, 28],
    "itemsize": 32,
})
assert BUS_SETPOINT32.itemsize == 32
BUS_SETPOINT32_OFFSETS: dict[str, int] = {"agent_no": 0, "flags": 2, "frame": 3, "seq": 4, "t_client_sim_ns": 8, "vel": 16, "yaw_rate": 28}
BUS_SETPOINT32_BITS: dict[str, dict[str, tuple]] = {"flags": {"final": (0, 1)}}

# awr.rec.RecPrefix8.v1 (8 B): MCAP awr-raw / awr-msgpack message prefix; the untouched payload follows (AWR-16 §13.4).
REC_REC_PREFIX8 = np.dtype({
    "names": ["epoch", "rflags", "prefix_version", "dt_us"],
    "formats": ["<u2", "u1", "u1", "<i4"],
    "offsets": [0, 2, 3, 4],
    "itemsize": 8,
})
assert REC_REC_PREFIX8.itemsize == 8
REC_REC_PREFIX8_OFFSETS: dict[str, int] = {"epoch": 0, "rflags": 2, "prefix_version": 3, "dt_us": 4}
REC_REC_PREFIX8_BITS: dict[str, dict[str, tuple]] = {"rflags": {"keyframe": (0, 1), "delta": (1, 1), "zstd": (2, 1), "reset": (3, 1)}}
REC_REC_PREFIX8_CONST: dict[str, int] = {"prefix_version": 1}

# awr.fixture.AwrtHeader.v1 (24 B): .awrrt protocol fixture file header; UTF-8 JSON header (header_json_len bytes, zero padded to 8) follows (AWR-16 §13.9).
FIXTURE_AWRT_HEADER = np.dtype({
    "names": ["magic", "version", "flags", "header_json_len", "reserved", "t0_wall_ns"],
    "formats": ["<u4", "<u2", "<u2", "<u4", "<u4", "<u8"],
    "offsets": [0, 4, 6, 8, 12, 16],
    "itemsize": 24,
})
assert FIXTURE_AWRT_HEADER.itemsize == 24
FIXTURE_AWRT_HEADER_OFFSETS: dict[str, int] = {"magic": 0, "version": 4, "flags": 6, "header_json_len": 8, "reserved": 12, "t0_wall_ns": 16}
FIXTURE_AWRT_HEADER_BITS: dict[str, dict[str, tuple]] = {"flags": {"timed": (0, 1)}}
FIXTURE_AWRT_HEADER_CONST: dict[str, int] = {"magic": 1414682433, "version": 1}

# awr.fixture.AwrtRecord.v1 (16 B): .awrrt record header; payload[len] follows, zero padded to 8.
FIXTURE_AWRT_RECORD = np.dtype({
    "names": ["dir", "kind", "reserved", "len", "t_rel_ns"],
    "formats": ["u1", "u1", "<u2", "<u4", "<u8"],
    "offsets": [0, 1, 2, 4, 8],
    "itemsize": 16,
})
assert FIXTURE_AWRT_RECORD.itemsize == 16
FIXTURE_AWRT_RECORD_OFFSETS: dict[str, int] = {"dir": 0, "kind": 1, "reserved": 2, "len": 4, "t_rel_ns": 8}

# awr.blob.Header.v1 (16 B): Generic blob header for encoding 3 records (uav/{id}/path, mission/{mid}/coverage); array follows (AWR-17 §6.5).
BLOB_HEADER = np.dtype({
    "names": ["magic", "version", "dtype", "count", "comp"],
    "formats": ["<u4", "<u2", "<u2", "<u4", "<u4"],
    "offsets": [0, 4, 6, 8, 12],
    "itemsize": 16,
})
assert BLOB_HEADER.itemsize == 16
BLOB_HEADER_OFFSETS: dict[str, int] = {"magic": 0, "version": 4, "dtype": 6, "count": 8, "comp": 12}
BLOB_HEADER_CONST: dict[str, int] = {"magic": 1112692545, "version": 1}

# awr.env.AwrvHeader.v1 (64 B): AWRV v1 volume header (file and typed blob); payload follows (AWR-16 §8.3).
ENV_AWRV_HEADER = np.dtype({
    "names": ["magic", "version", "kind", "nx", "ny", "nz", "comp", "dtype", "layout", "premultiplied", "alpha", "origin_enu_m", "cell_m", "dir_from_deg", "value_scale", "field_version", "payload_bytes", "crc32"],
    "formats": ["<u4", "<u2", "<u2", "<u2", "<u2", "<u2", "<u2", "u1", "u1", "u1", "u1", ("<f4", 3), ("<f4", 3), "<f4", "<f4", "<u4", "<u4", "<u4"],
    "offsets": [0, 4, 6, 8, 10, 12, 14, 16, 17, 18, 19, 20, 32, 44, 48, 52, 56, 60],
    "itemsize": 64,
})
assert ENV_AWRV_HEADER.itemsize == 64
ENV_AWRV_HEADER_OFFSETS: dict[str, int] = {"magic": 0, "version": 4, "kind": 6, "nx": 8, "ny": 10, "nz": 12, "comp": 14, "dtype": 16, "layout": 17, "premultiplied": 18, "alpha": 19, "origin_enu_m": 20, "cell_m": 32, "dir_from_deg": 44, "value_scale": 48, "field_version": 52, "payload_bytes": 56, "crc32": 60}
ENV_AWRV_HEADER_CONST: dict[str, int] = {"magic": 1448236865, "version": 1}

# awr.env.AwslHeader.v1 (48 B): AWSL v1 streamline file header; u32 line_offsets[n_lines + 1] (padded to 8) and f32 verts[n_verts][5] follow (AWR-16 §8.6).
ENV_AWSL_HEADER = np.dtype({
    "names": ["magic", "version", "flags", "n_lines", "n_verts", "dir_from_deg", "ref_speed_mps", "field_version", "stride", "tau_hat_max_m", "s_hat_max", "seed", "reserved"],
    "formats": ["<u4", "<u2", "<u2", "<u4", "<u4", "<f4", "<f4", "<u4", "<u4", "<f4", "<f4", "<u4", "<u4"],
    "offsets": [0, 4, 6, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44],
    "itemsize": 48,
})
assert ENV_AWSL_HEADER.itemsize == 48
ENV_AWSL_HEADER_OFFSETS: dict[str, int] = {"magic": 0, "version": 4, "flags": 6, "n_lines": 8, "n_verts": 12, "dir_from_deg": 16, "ref_speed_mps": 20, "field_version": 24, "stride": 28, "tau_hat_max_m": 32, "s_hat_max": 36, "seed": 40, "reserved": 44}
ENV_AWSL_HEADER_BITS: dict[str, dict[str, tuple]] = {"flags": {"tau_normalized": (0, 1), "shuffled": (1, 1)}}
ENV_AWSL_HEADER_CONST: dict[str, int] = {"magic": 1280530241, "version": 1}

# awr.recon.AwtrHeader.v1 (32 B): trajectory.bin (AWTR v1) header; SoA arrays follow, each 8-byte aligned (AWR-16 §14.1).
RECON_AWTR_HEADER = np.dtype({
    "names": ["magic", "version", "flags", "n", "reserved", "t0_ns", "reserved2"],
    "formats": ["<u4", "<u2", "<u2", "<u4", "<u4", "<i8", "<u8"],
    "offsets": [0, 4, 6, 8, 12, 16, 24],
    "itemsize": 32,
})
assert RECON_AWTR_HEADER.itemsize == 32
RECON_AWTR_HEADER_OFFSETS: dict[str, int] = {"magic": 0, "version": 4, "flags": 6, "n": 8, "reserved": 12, "t0_ns": 16, "reserved2": 24}
RECON_AWTR_HEADER_BITS: dict[str, dict[str, tuple]] = {"flags": {"body_pose": (0, 1)}}
RECON_AWTR_HEADER_CONST: dict[str, int] = {"magic": 1381259073, "version": 1}

# awr.ipc.RingHeader.v1 (256 B): StateRing file header /dev/shm/awr/<run>/state.<producer> (AWR-17 §9.2). The clock group is protected by clock_seq (odd while writing).
IPC_RING_HEADER = np.dtype({
    "names": ["magic", "version", "flags", "slot_count", "slot_bytes", "capacity", "layout_id", "writer_pid", "epoch", "head", "heartbeat_ns", "t_sim_ns", "rate_milli", "clock_state", "_pad0", "roster_version", "segment", "created_ns", "step_seq", "step_budget_us", "step_p99_us", "rtf_milli", "id_base", "id_count", "step_max_us", "clock_seq", "step_p50_us", "catchup_saturated", "_reserved"],
    "formats": ["<u4", "<u2", "<u2", "<u4", "<u4", "<u4", "<u4", "<u4", "<u4", "<u8", "<i8", "<i8", "<i4", "u1", ("u1", 3), "<u4", "<u4", "<i8", "<u8", "<u4", "<u4", "<u4", "<u4", "<u4", "<u4", "<u8", "<u4", "<u4", ("u1", 128)],
    "offsets": [0, 4, 6, 8, 12, 16, 20, 24, 28, 32, 40, 48, 56, 60, 61, 64, 68, 72, 80, 88, 92, 96, 100, 104, 108, 112, 120, 124, 128],
    "itemsize": 256,
})
assert IPC_RING_HEADER.itemsize == 256
IPC_RING_HEADER_OFFSETS: dict[str, int] = {"magic": 0, "version": 4, "flags": 6, "slot_count": 8, "slot_bytes": 12, "capacity": 16, "layout_id": 20, "writer_pid": 24, "epoch": 28, "head": 32, "heartbeat_ns": 40, "t_sim_ns": 48, "rate_milli": 56, "clock_state": 60, "_pad0": 61, "roster_version": 64, "segment": 68, "created_ns": 72, "step_seq": 80, "step_budget_us": 88, "step_p99_us": 92, "rtf_milli": 96, "id_base": 100, "id_count": 104, "step_max_us": 108, "clock_seq": 112, "step_p50_us": 120, "catchup_saturated": 124, "_reserved": 128}
IPC_RING_HEADER_SCALE: dict[str, float] = {"rate_milli": 0.001, "rtf_milli": 0.001}
IPC_RING_HEADER_BITS: dict[str, dict[str, tuple]] = {"flags": {"replay": (0, 1)}, "clock_state": {"state": (0, 4, "TimeState"), "replay": (7, 1)}}
IPC_RING_HEADER_CONST: dict[str, int] = {"magic": 827479873, "version": 1}

# awr.ipc.ReaderCursor.v1 (32 B): StateRing reader cursor row (8 rows at [256, 512)).
IPC_READER_CURSOR = np.dtype({
    "names": ["pid", "mode", "cursor", "heartbeat_ns", "name_hash", "_pad"],
    "formats": ["<u4", "<u4", "<u8", "<i8", "<u4", "<u4"],
    "offsets": [0, 4, 8, 16, 24, 28],
    "itemsize": 32,
})
assert IPC_READER_CURSOR.itemsize == 32
IPC_READER_CURSOR_OFFSETS: dict[str, int] = {"pid": 0, "mode": 4, "cursor": 8, "heartbeat_ns": 16, "name_hash": 24, "_pad": 28}

# awr.ipc.SlotHeader.v1 (64 B): StateRing slot header; Full64[cap] and Lite32[cap] follow.
IPC_SLOT_HEADER = np.dtype({
    "names": ["lock", "frame_seq", "t_sim_ns", "t_pub_ns", "n_rows", "epoch", "roster_version", "flags", "full_off", "full_len", "lite_off", "lite_len"],
    "formats": ["<u8", "<u8", "<i8", "<i8", "<u4", "<u4", "<u4", "<u4", "<u4", "<u4", "<u4", "<u4"],
    "offsets": [0, 8, 16, 24, 32, 36, 40, 44, 48, 52, 56, 60],
    "itemsize": 64,
})
assert IPC_SLOT_HEADER.itemsize == 64
IPC_SLOT_HEADER_OFFSETS: dict[str, int] = {"lock": 0, "frame_seq": 8, "t_sim_ns": 16, "t_pub_ns": 24, "n_rows": 32, "epoch": 36, "roster_version": 40, "flags": 44, "full_off": 48, "full_len": 52, "lite_off": 56, "lite_len": 60}
IPC_SLOT_HEADER_BITS: dict[str, dict[str, tuple]] = {"flags": {"reset": (0, 1), "fastfwd": (1, 1), "replay": (2, 1)}}

# awr.ipc.Heartbeat16.v1 (16 B): Main-loop heartbeat file /dev/shm/awr/<run>/hb.<name> for processes other than sim-core (AWR-17 §9.6).
IPC_HEARTBEAT16 = np.dtype({
    "names": ["mono_ns", "pid", "beat"],
    "formats": ["<i8", "<u4", "<u4"],
    "offsets": [0, 8, 12],
    "itemsize": 16,
})
assert IPC_HEARTBEAT16.itemsize == 16
IPC_HEARTBEAT16_OFFSETS: dict[str, int] = {"mono_ns": 0, "pid": 8, "beat": 12}

DTYPES: dict[str, np.dtype] = {
    "awr.DroneState64.v1": DRONE_STATE64,
    "awr.SwarmLite32.v1": SWARM_LITE32,
    "awr.EnvSample32.v1": ENV_SAMPLE32,
    "awr.VelSetpoint16.v1": VEL_SETPOINT16,
    "awr.SensorPose48.v1": SENSOR_POSE48,
    "awr.SwarmLite32Block.v1": SWARM_LITE32BLOCK,
    "awr.rt.BatchHeader.v1": RT_BATCH_HEADER,
    "awr.rt.RecordHeader.v1": RT_RECORD_HEADER,
    "awr.rt.Time.v1": RT_TIME,
    "awr.rt.ClientDataHeader.v1": RT_CLIENT_DATA_HEADER,
    "awr.bus.Setpoint32.v1": BUS_SETPOINT32,
    "awr.rec.RecPrefix8.v1": REC_REC_PREFIX8,
    "awr.fixture.AwrtHeader.v1": FIXTURE_AWRT_HEADER,
    "awr.fixture.AwrtRecord.v1": FIXTURE_AWRT_RECORD,
    "awr.blob.Header.v1": BLOB_HEADER,
    "awr.env.AwrvHeader.v1": ENV_AWRV_HEADER,
    "awr.env.AwslHeader.v1": ENV_AWSL_HEADER,
    "awr.recon.AwtrHeader.v1": RECON_AWTR_HEADER,
    "awr.ipc.RingHeader.v1": IPC_RING_HEADER,
    "awr.ipc.ReaderCursor.v1": IPC_READER_CURSOR,
    "awr.ipc.SlotHeader.v1": IPC_SLOT_HEADER,
    "awr.ipc.Heartbeat16.v1": IPC_HEARTBEAT16,
}
SIZES: dict[str, int] = {
    "awr.DroneState64.v1": 64,
    "awr.SwarmLite32.v1": 32,
    "awr.EnvSample32.v1": 32,
    "awr.VelSetpoint16.v1": 16,
    "awr.SensorPose48.v1": 48,
    "awr.SwarmLite32Block.v1": 16,
    "awr.rt.BatchHeader.v1": 16,
    "awr.rt.RecordHeader.v1": 16,
    "awr.rt.Time.v1": 24,
    "awr.rt.ClientDataHeader.v1": 16,
    "awr.bus.Setpoint32.v1": 32,
    "awr.rec.RecPrefix8.v1": 8,
    "awr.fixture.AwrtHeader.v1": 24,
    "awr.fixture.AwrtRecord.v1": 16,
    "awr.blob.Header.v1": 16,
    "awr.env.AwrvHeader.v1": 64,
    "awr.env.AwslHeader.v1": 48,
    "awr.recon.AwtrHeader.v1": 32,
    "awr.ipc.RingHeader.v1": 256,
    "awr.ipc.ReaderCursor.v1": 32,
    "awr.ipc.SlotHeader.v1": 64,
    "awr.ipc.Heartbeat16.v1": 16,
}


def pack_bits(spec: dict[str, tuple], **values: int) -> int:
    """Pack named bit fields (spec from *_BITS[field]) into an integer."""
    v = 0
    for name, x in values.items():
        start, width = spec[name][0], spec[name][1]
        v |= (int(x) & ((1 << width) - 1)) << start
    return v


def unpack_bits(spec: dict[str, tuple], value: int) -> dict[str, int]:
    return {name: (int(value) >> s[0]) & ((1 << s[1]) - 1) for name, s in spec.items()}


def pack_fs(state: int, sub: int = 0) -> int:
    """flight_state byte: bit0-4 FlightState, bit5-7 sub-mode."""
    return (state & 0x1F) | ((sub & 7) << 5)


def unpack_fs(b: int) -> tuple[int, int]:
    return b & 0x1F, (b >> 5) & 7


def pack_ctrl(owner: int, locked: bool, native: int, pose: int) -> int:
    """ctrl byte: bit0-2 owner, bit3 locked, bit4-5 native, bit6-7 pose_src."""
    return (owner & 7) | (int(locked) << 3) | ((native & 3) << 4) | ((pose & 3) << 6)


def unpack_ctrl(b: int) -> tuple[int, bool, int, int]:
    return b & 7, bool(b & 8), (b >> 4) & 3, (b >> 6) & 3


def lite_from_full(full: np.ndarray, out: np.ndarray | None = None) -> np.ndarray:
    """Quantise Full64 rows into Lite32 rows (q x32767, vel x100, both rounded and clamped to +-32767)."""
    if out is None:
        out = np.zeros(len(full), SWARM_LITE32)
    out["agent_no"] = full["agent_no"]
    out["flight_state"] = full["flight_state"]
    out["battery_pct"] = full["battery_pct"]
    out["pos"] = full["pos"]
    out["q_snorm"] = np.clip(np.rint(full["q"].astype(np.float64) * 32767.0), -32767, 32767).astype(np.int16)
    out["vel_cms"] = np.clip(np.rint(full["vel"].astype(np.float64) * 100.0), -32767, 32767).astype(np.int16)
    out["flags"] = full["flags"]
    out["ctrl"] = full["ctrl"]
    return out
