"""Reason codes from packages/contracts/rt/reasons.json (AWR-17 §8).

Generated by tools/contracts/gen.py from packages/contracts. Do not edit."""

from __future__ import annotations

from enum import IntEnum
from typing import NamedTuple


class Reason(IntEnum):
    OK = 0
    TEMPORARILY_REJECTED = 1
    DENIED = 2
    UNSUPPORTED = 3
    FAILED = 4
    IN_PROGRESS = 5
    CANCELLED = 6
    COMMAND_LONG_ONLY = 7
    COMMAND_INT_ONLY = 8
    COMMAND_UNSUPPORTED_MAV_FRAME = 9
    NOT_IN_CONTROL = 10
    LEASE_DENIED = 100
    SAFETY_ACTIVE = 101
    GEOFENCE_REJECT = 102
    PREFLIGHT_FAILED = 103
    NOT_ARMED = 104
    STATE = 105
    DUPLICATE = 106
    NO_VEHICLE = 107
    LINK_ERROR = 108
    BACKEND_UNSUPPORTED = 109
    PARAM_OUT_OF_RANGE = 110
    RATE_LIMITED = 111
    CONFIRM_REQUIRED = 112
    LOC_NOT_READY = 113
    LOCKED = 114
    ROLE_FORBIDDEN = 115
    SEAT_TAKEN = 116
    CLOCK_CONSTRAINT = 117
    READ_ONLY_MODE = 118
    ENERGY_INFEASIBLE = 119
    ENV_LIMIT = 120
    SCENARIO_INVALID = 121
    RECORDING_INCOMPATIBLE = 122
    WORLD_NOT_READY = 123
    JOB_CONFLICT = 124
    PLAN_FAILED = 125
    ACK_TIMEOUT = 200
    MODE_NOT_ENTERED = 201
    PROGRESS_TIMEOUT = 202
    STALLED = 203
    PREEMPTED_BY_SAFETY = 204
    PREEMPTED_BY_PILOT = 205
    SUPERSEDED = 206
    VEHICLE_LOST = 207
    CRASHED = 208
    WATCHDOG = 209
    LEASE_PREEMPTED = 210
    SIM_UNAVAILABLE = 211
    SIM_ROLLBACK = 212
    SERVICE_UNAVAILABLE = 213
    PLANNER_CRASHED = 214
    BAD_REQUEST = 300
    AUTH_REQUIRED = 301
    TOKEN_INVALID = 302
    ORIGIN_FORBIDDEN = 303
    ADMIN_SECRET_REQUIRED = 304
    NOT_FOUND = 305
    METHOD_NOT_ALLOWED = 306
    PAYLOAD_TOO_LARGE = 307
    UNSUPPORTED_MEDIA_TYPE = 308
    RANGE_NOT_SATISFIABLE = 309
    CONTENT_VERSION_STALE = 310
    PROTOCOL_UNSUPPORTED = 311
    LAYOUT_MISMATCH = 312
    UNKNOWN_OP = 313
    TOPIC_INVALID = 314
    SUB_LIMIT = 315
    CONN_LIMIT = 316
    HELLO_TIMEOUT = 317
    CONTROL_BACKLOG = 318
    EVENTS_TRUNCATED = 319
    INTERNAL_ERROR = 320
    IDEMPOTENCY_CONFLICT = 321
    CLIENT_PUBLISH_DENIED = 322
    HOST_FORBIDDEN = 323
    RECON_PARAMS_INVALID = 330
    RECON_ENGINE_UNAVAILABLE = 331
    RECON_TARGET_EXISTS = 332
    JOB_QUEUE_FULL = 333
    RECON_INPUT_INVALID = 334
    RECON_OOM = 335
    RECON_POSE_CONVENTION = 336
    RECON_POSE_COLLAPSE = 337
    RECON_NO_GNSS = 338
    RECON_GEOREF_REJECTED = 339
    RECON_IR_INVALID = 340
    RECON_EMPTY = 341
    RECON_TILING_FAILED = 342
    RECON_PACKAGE_INVALID = 343
    JOB_WORKER_CRASHED = 344
    RECON_DISK_QUOTA = 346
    JOB_NOT_FOUND = 347
    JOB_STATE_CONFLICT = 348
    WORLD_INVALID = 350
    FORMAT_UNSUPPORTED = 351
    COORDINATE_MISMATCH = 352
    VEHICLE_PROFILE_INVALID = 353
    ASSET_MISSING = 354
    RESIM_INCOMPATIBLE = 355
    EXPORT_FAILED = 356
    PC_WORLD_NOT_FOUND = 400
    PC_FORMAT_UNSUPPORTED = 401
    PC_CONTENT_STALE = 402
    PC_FIRST_SCREEN_FAILED = 403
    PC_NODE_FAILED = 404
    PC_RANGE_MISMATCH = 405
    PC_POOL_STALL = 406
    PC_CAPACITY_CLAMPED = 407
    PC_WORKER_CRASHED = 408
    PC_GPU_RESET = 409
    PC_PICK_MISS = 410
    PC_PICK_TIMEOUT = 411
    ENV_PRESET_UNKNOWN = 440
    ENV_FIELD_UNKNOWN = 441
    ENV_LEVEL_UNAVAILABLE = 442
    ENV_ASSET_INVALID = 443
    REC_DISK_LOW = 460
    REC_SEGMENT_CORRUPT = 461
    BOOKMARK_LIMIT = 462
    REPLAY_NOT_OPEN = 463
    AGENT_GUARD_INTERNAL = 470
    CAPABILITY_UNKNOWN = 471
    CAPABILITY_NOT_SERVED = 472
    NO_CANDIDATE = 473
    ALL_INFEASIBLE = 474
    QUOTE_TIMEOUT = 475
    DELEGATION_REJECTED = 476
    EXEC_TIMEOUT = 477
    ACCEPT_FALSE = 478
    EFFECT_UNVERIFIED = 479
    SCOPE_VIOLATION = 480
    ESCALATION_TIMEOUT = 481
    AGENT_SCOPE_FORBIDDEN = 482
    TASK_INTERRUPTED = 483
    ANET_WIRE_MISMATCH = 484
    ANET_DAEMON_DOWN = 485
    RECEIPT_INVALID = 486
    TIME_UNSYNCED = 490
    UNIT_MISMATCH = 491
    EXTRINSIC_NOT_IDENTITY = 492
    CALIB_MISSING = 493
    GNSS_INSUFFICIENT = 494
    COLLINEAR_NO_GRAVITY = 495
    SIM3_OUT_OF_BASIN = 496
    QA_GATE_FAILED = 497
    RELEASE_IMMUTABLE = 498
    RELEASE_INTEGRITY = 499


class ReasonInfo(NamedTuple):
    code: int
    name: str
    http: int | None
    category: str
    step: str | None
    message_zh: str
    remedy_zh: str
    d1: str


REASONS: dict[int, ReasonInfo] = {
    0: ReasonInfo(0, "OK", 200, "ok", None, "成功", "无需处理", "core"),
    1: ReasonInfo(1, "TEMPORARILY_REJECTED", 409, "native", "native", "外部飞控暂时拒绝", "稍后重试", "V0.2"),
    2: ReasonInfo(2, "DENIED", 409, "native", "native", "外部飞控拒绝该命令", "检查飞控状态与参数后重试", "V0.2"),
    3: ReasonInfo(3, "UNSUPPORTED", 501, "native", "native", "外部飞控不支持该命令", "改用该后端支持的命令", "V0.2"),
    4: ReasonInfo(4, "FAILED", 409, "native", "native", "外部飞控执行失败", "查看飞控日志后重试", "V0.2"),
    5: ReasonInfo(5, "IN_PROGRESS", None, "native", "native", "外部飞控执行中（仅作进度，不作终态）", "等待终态结果", "V0.2"),
    6: ReasonInfo(6, "CANCELLED", None, "call_control", "call_control", "调用已取消（cancel、剧本重置或机体移除）", "如需继续请重新下发", "core"),
    7: ReasonInfo(7, "COMMAND_LONG_ONLY", 409, "native", "native", "外部飞控只接受 COMMAND_LONG", "由适配层改用 COMMAND_LONG", "V0.2"),
    8: ReasonInfo(8, "COMMAND_INT_ONLY", 409, "native", "native", "外部飞控只接受 COMMAND_INT", "由适配层改用 COMMAND_INT", "V0.2"),
    9: ReasonInfo(9, "COMMAND_UNSUPPORTED_MAV_FRAME", 409, "native", "native", "外部飞控不支持该坐标帧", "由适配层改用受支持的坐标帧", "V0.2"),
    10: ReasonInfo(10, "NOT_IN_CONTROL", 409, "native", "native", "遥控器或其他地面站持有控制", "先收回飞控控制权", "V0.2"),
    100: ReasonInfo(100, "LEASE_DENIED", 409, "admission", "5", "未持有租约或优先级不够", "先接管该机", "core"),
    101: ReasonInfo(101, "SAFETY_ACTIVE", 409, "admission", "4", "安全动作进行中，命令被拒绝", "等待安全动作结束或原因解除", "core"),
    102: ReasonInfo(102, "GEOFENCE_REJECT", 409, "admission", "8", "目标越界、进入禁飞区或穿越建筑", "在 border 内重新选点或改用 safe_transit", "core"),
    103: ReasonInfo(103, "PREFLIGHT_FAILED", 409, "admission", "4", "预检不通过", "查看失败项并处理后重试", "core"),
    104: ReasonInfo(104, "NOT_ARMED", 409, "admission", "4", "未解锁且未要求自动解锁", "先解锁或使用 auto_arm", "core"),
    105: ReasonInfo(105, "STATE", 409, "admission", "4", "当前状态或资源状态不允许该操作", "查看准入矩阵，待状态变化后重试", "core"),
    106: ReasonInfo(106, "DUPLICATE", 409, "admission", "4", "同类命令正在执行", "无需重复下发，关注正在执行的调用", "core"),
    107: ReasonInfo(107, "NO_VEHICLE", 404, "admission", "route", "机体不存在或已移除", "刷新机群列表", "core"),
    108: ReasonInfo(108, "LINK_ERROR", 503, "admission", "4", "机体生命周期不在 READY", "等待链路恢复", "core"),
    109: ReasonInfo(109, "BACKEND_UNSUPPORTED", 501, "admission", "7", "当前后端不支持该命令或参数", "改用受支持的命令", "core"),
    110: ReasonInfo(110, "PARAM_OUT_OF_RANGE", 422, "admission", "6", "参数越界或超过上限", "按取值范围修正参数", "core"),
    111: ReasonInfo(111, "RATE_LIMITED", 429, "admission", "2", "请求过于频繁", "降低请求频率后重试", "core"),
    112: ReasonInfo(112, "CONFIRM_REQUIRED", 428, "admission", "3", "缺少或无效的确认令牌", "重新确认后提交", "core"),
    113: ReasonInfo(113, "LOC_NOT_READY", 409, "admission", "4", "定位未就绪", "等待定位就绪", "core"),
    114: ReasonInfo(114, "LOCKED", 409, "admission", "4", "SafetyStop 加锁期间只接受安全类命令", "由席位持有者解除 SafetyStop", "core"),
    115: ReasonInfo(115, "ROLE_FORBIDDEN", 403, "admission", "1", "当前角色无权执行该操作", "使用有权限的角色登录", "core"),
    116: ReasonInfo(116, "SEAT_TAKEN", 409, "admission", "1", "操作席位被他人持有", "等待席位释放或申请接管", "core"),
    117: ReasonInfo(117, "CLOCK_CONSTRAINT", 409, "admission", "4", "时钟状态或倍率不允许该操作", "调整倍率或时钟状态后重试", "core"),
    118: ReasonInfo(118, "READ_ONLY_MODE", 409, "admission", "1", "当前为只读模式（回放或关闭中）", "退出回放后再操作", "core"),
    119: ReasonInfo(119, "ENERGY_INFEASIBLE", 409, "admission", "estimate", "能量不足，任务不可行", "缩短航程或提高初始电量", "core"),
    120: ReasonInfo(120, "ENV_LIMIT", 409, "admission", "estimate", "环境条件超出机体能力", "等待天气好转或调整任务", "ext"),
    121: ReasonInfo(121, "SCENARIO_INVALID", 422, "admission", "scenario", "剧本或谓词校验失败", "按校验信息修正剧本", "core"),
    122: ReasonInfo(122, "RECORDING_INCOMPATIBLE", 409, "admission", "playback", "录制与当前世界或布局不一致", "使用匹配版本回放", "ext"),
    123: ReasonInfo(123, "WORLD_NOT_READY", 409, "admission", "session", "世界未就绪或被会话绑定", "等待世界就绪或结束当前会话", "core"),
    124: ReasonInfo(124, "JOB_CONFLICT", 409, "admission", "job", "同一目标已有进行中的任务", "等待当前任务结束", "ext"),
    125: ReasonInfo(125, "PLAN_FAILED", 422, "admission", "plan", "规划无解或超时", "调整目标或区域后重试", "core"),
    200: ReasonInfo(200, "ACK_TIMEOUT", 504, "runtime", "exec", "外部飞控确认超时", "检查链路后重试", "V0.2"),
    201: ReasonInfo(201, "MODE_NOT_ENTERED", 409, "runtime", "exec", "飞控未进入意图模式", "检查飞控模式与参数", "V0.2"),
    202: ReasonInfo(202, "PROGRESS_TIMEOUT", None, "runtime", "exec", "超过完成截止时间", "检查路径与环境后重试", "core"),
    203: ReasonInfo(203, "STALLED", None, "runtime", "exec", "巡航停滞（5 s 前进不足 0.2 m）", "检查风况与障碍后重试", "core"),
    204: ReasonInfo(204, "PREEMPTED_BY_SAFETY", None, "runtime", "exec", "被自动安全动作抢占", "待安全动作结束后重新下发", "core"),
    205: ReasonInfo(205, "PREEMPTED_BY_PILOT", None, "runtime", "exec", "飞手或外部地面站接管", "与现场协调控制权", "V0.2"),
    206: ReasonInfo(206, "SUPERSEDED", None, "runtime", "exec", "被新的调用取代", "无需处理", "core"),
    207: ReasonInfo(207, "VEHICLE_LOST", None, "runtime", "exec", "机体失联", "等待链路恢复", "core"),
    208: ReasonInfo(208, "CRASHED", None, "runtime", "exec", "机体坠毁", "移除机体或重置剧本", "core"),
    209: ReasonInfo(209, "WATCHDOG", None, "runtime", "exec", "流式指令看门狗超时", "保持遥操作输入或重新开始", "core"),
    210: ReasonInfo(210, "LEASE_PREEMPTED", None, "runtime", "exec", "租约被更高优先级抢占", "重新接管后下发", "core"),
    211: ReasonInfo(211, "SIM_UNAVAILABLE", 503, "runtime", "entry", "仿真进程无回复、准备中或恢复中", "稍后重试", "core"),
    212: ReasonInfo(212, "SIM_ROLLBACK", None, "runtime", "exec", "仿真回滚或重开，调用作废", "重新下发", "core"),
    213: ReasonInfo(213, "SERVICE_UNAVAILABLE", 503, "runtime", "entry", "依赖服务不可用", "稍后重试", "core"),
    214: ReasonInfo(214, "PLANNER_CRASHED", None, "runtime", "exec", "规划进程崩溃且重试失败", "稍后重试", "core"),
    300: ReasonInfo(300, "BAD_REQUEST", 400, "protocol", "entry", "请求格式或 schema 不合法", "按接口文档修正请求", "core"),
    301: ReasonInfo(301, "AUTH_REQUIRED", 401, "protocol", "entry", "缺少 token", "先签发 token", "core"),
    302: ReasonInfo(302, "TOKEN_INVALID", 401, "protocol", "entry", "token 签名错误、过期或不属于当前运行", "重新签发 token", "core"),
    303: ReasonInfo(303, "ORIGIN_FORBIDDEN", 403, "protocol", "entry", "Origin 不在白名单", "从允许的地址访问", "core"),
    304: ReasonInfo(304, "ADMIN_SECRET_REQUIRED", 401, "protocol", "entry", "需要管理口令或口令错误", "提供正确的管理口令", "core"),
    305: ReasonInfo(305, "NOT_FOUND", 404, "protocol", "entry", "资源不存在", "检查资源标识", "core"),
    306: ReasonInfo(306, "METHOD_NOT_ALLOWED", 405, "protocol", "entry", "方法不被允许", "使用正确的 HTTP 方法", "core"),
    307: ReasonInfo(307, "PAYLOAD_TOO_LARGE", 413, "protocol", "entry", "请求体超限", "减小请求体", "core"),
    308: ReasonInfo(308, "UNSUPPORTED_MEDIA_TYPE", 415, "protocol", "entry", "不支持的媒体类型", "使用 application/json", "core"),
    309: ReasonInfo(309, "RANGE_NOT_SATISFIABLE", 416, "protocol", "static", "Range 越界", "修正 Range 请求", "core"),
    310: ReasonInfo(310, "CONTENT_VERSION_STALE", 409, "protocol", "static", "内容版本已变化", "重新打开世界", "core"),
    311: ReasonInfo(311, "PROTOCOL_UNSUPPORTED", 426, "protocol", "ws", "子协议或契约主版本不兼容", "刷新页面", "core"),
    312: ReasonInfo(312, "LAYOUT_MISMATCH", 409, "protocol", "ipc", "二进制布局哈希不一致", "重新构建前端或重启服务", "core"),
    313: ReasonInfo(313, "UNKNOWN_OP", None, "protocol", "ws", "不认识的 op", "升级客户端", "core"),
    314: ReasonInfo(314, "TOPIC_INVALID", None, "protocol", "ws", "topic 或通配语法非法", "修正订阅", "core"),
    315: ReasonInfo(315, "SUB_LIMIT", None, "protocol", "ws", "订阅数超过上限", "减少订阅", "core"),
    316: ReasonInfo(316, "CONN_LIMIT", None, "protocol", "ws", "连接数超过上限", "稍后重连", "core"),
    317: ReasonInfo(317, "HELLO_TIMEOUT", None, "protocol", "ws", "10 s 内未收到 hello", "重新连接", "core"),
    318: ReasonInfo(318, "CONTROL_BACKLOG", None, "protocol", "ws", "控制面积压", "降低发送频率后重连", "core"),
    319: ReasonInfo(319, "EVENTS_TRUNCATED", 410, "protocol", "entry", "事件起点早于缓存范围", "改用各自包含通道的最新值恢复", "core"),
    320: ReasonInfo(320, "INTERNAL_ERROR", 500, "protocol", "entry", "服务内部错误", "附 request_id 报告缺陷", "core"),
    321: ReasonInfo(321, "IDEMPOTENCY_CONFLICT", 422, "protocol", "entry", "同一 Idempotency-Key 的请求体不同", "使用新的 Idempotency-Key", "core"),
    322: ReasonInfo(322, "CLIENT_PUBLISH_DENIED", None, "protocol", "ws", "遥操作数据未声明或没有活动的 velocity 调用", "先发起 velocity 调用", "core"),
    323: ReasonInfo(323, "HOST_FORBIDDEN", 400, "protocol", "entry", "Host 头不在白名单", "使用允许的主机名访问", "core"),
    330: ReasonInfo(330, "RECON_PARAMS_INVALID", 422, "job", "submit", "重建参数校验失败", "按表单提示修正参数", "ext"),
    331: ReasonInfo(331, "RECON_ENGINE_UNAVAILABLE", 409, "job", "submit", "重建引擎不可用", "改用可用引擎", "ext"),
    332: ReasonInfo(332, "RECON_TARGET_EXISTS", 409, "job", "submit", "目标世界已存在或为内置世界", "更换目标世界 id", "ext"),
    333: ReasonInfo(333, "JOB_QUEUE_FULL", 429, "job", "submit", "任务队列已满", "等待队列空闲", "ext"),
    334: ReasonInfo(334, "RECON_INPUT_INVALID", None, "job", "stage", "重建输入无效", "检查输入数据", "ext"),
    335: ReasonInfo(335, "RECON_OOM", None, "job", "stage", "内存超限", "降低规模后重试", "ext"),
    336: ReasonInfo(336, "RECON_POSE_CONVENTION", None, "job", "stage", "位姿方向自检不通过", "检查引擎位姿约定", "ext"),
    337: ReasonInfo(337, "RECON_POSE_COLLAPSE", None, "job", "stage", "位姿崩溃", "更换输入或引擎", "V0.5"),
    338: ReasonInfo(338, "RECON_NO_GNSS", None, "job", "stage", "GNSS 同步样本不足", "补充 GNSS 或按相对尺度发布", "ext"),
    339: ReasonInfo(339, "RECON_GEOREF_REJECTED", None, "job", "stage", "地理配准门禁拒绝", "查看门禁表后人工复核", "ext"),
    340: ReasonInfo(340, "RECON_IR_INVALID", 422, "job", "stage", "Recon IR 校验失败", "查看校验错误", "ext"),
    341: ReasonInfo(341, "RECON_EMPTY", None, "job", "stage", "融合点过少", "增加输入帧", "ext"),
    342: ReasonInfo(342, "RECON_TILING_FAILED", None, "job", "stage", "ingest 或切片失败", "查看任务日志后重试", "ext"),
    343: ReasonInfo(343, "RECON_PACKAGE_INVALID", None, "job", "stage", "世界包深校验失败", "查看校验报告", "ext"),
    344: ReasonInfo(344, "JOB_WORKER_CRASHED", None, "job", "stage", "任务进程崩溃或挂死", "重试任务", "ext"),
    346: ReasonInfo(346, "RECON_DISK_QUOTA", 507, "job", "submit", "磁盘配额不足", "清理空间后重试", "ext"),
    347: ReasonInfo(347, "JOB_NOT_FOUND", 404, "job", "submit", "任务不存在", "检查任务 id", "ext"),
    348: ReasonInfo(348, "JOB_STATE_CONFLICT", 409, "job", "submit", "任务状态不允许该操作", "刷新任务状态", "ext"),
    350: ReasonInfo(350, "WORLD_INVALID", 409, "data", "load", "世界包语义校验失败", "重建该世界", "core"),
    351: ReasonInfo(351, "FORMAT_UNSUPPORTED", 415, "data", "load", "未知的格式主版本或 formatVersion", "升级软件或重建数据", "core"),
    352: ReasonInfo(352, "COORDINATE_MISMATCH", 409, "data", "load", "派生资产的坐标哈希与世界不一致", "重建派生资产", "core"),
    353: ReasonInfo(353, "VEHICLE_PROFILE_INVALID", 422, "data", "load", "机型文件校验或自洽检查失败", "修正机型参数文件", "core"),
    354: ReasonInfo(354, "ASSET_MISSING", 404, "data", "load", "清单引用的资产文件不存在", "重建或重新获取资产", "core"),
    355: ReasonInfo(355, "RESIM_INCOMPATIBLE", 409, "data", "load", "输入日志与当前内核或版本不一致", "使用匹配版本重仿真", "ext"),
    356: ReasonInfo(356, "EXPORT_FAILED", 500, "data", "export", "导出或其校验失败", "查看导出日志", "V0.5"),
    400: ReasonInfo(400, "PC_WORLD_NOT_FOUND", None, "browser", "pointcloud", "世界不存在", "选择其他世界", "core"),
    401: ReasonInfo(401, "PC_FORMAT_UNSUPPORTED", None, "browser", "pointcloud", "世界格式不受支持", "升级前端或重建世界", "core"),
    402: ReasonInfo(402, "PC_CONTENT_STALE", None, "browser", "pointcloud", "世界内容已更新", "重新打开世界", "core"),
    403: ReasonInfo(403, "PC_FIRST_SCREEN_FAILED", None, "browser", "pointcloud", "首屏数据加载失败", "重试加载", "core"),
    404: ReasonInfo(404, "PC_NODE_FAILED", None, "browser", "pointcloud", "节点加载失败", "稍后自动重试", "core"),
    405: ReasonInfo(405, "PC_RANGE_MISMATCH", None, "browser", "pointcloud", "Range 响应不符", "检查静态服务", "core"),
    406: ReasonInfo(406, "PC_POOL_STALL", None, "browser", "pointcloud", "点池分配失败", "无需处理", "core"),
    407: ReasonInfo(407, "PC_CAPACITY_CLAMPED", None, "browser", "pointcloud", "预算受点池容量限制", "无需处理", "core"),
    408: ReasonInfo(408, "PC_WORKER_CRASHED", None, "browser", "pointcloud", "解码 Worker 崩溃", "已自动重建", "core"),
    409: ReasonInfo(409, "PC_GPU_RESET", None, "browser", "pointcloud", "GPU 上下文丢失", "等待自动恢复", "core"),
    410: ReasonInfo(410, "PC_PICK_MISS", None, "browser", "pointcloud", "拾取窗口内无点", "无需处理", "core"),
    411: ReasonInfo(411, "PC_PICK_TIMEOUT", None, "browser", "pointcloud", "拾取超时", "重试拾取", "core"),
    440: ReasonInfo(440, "ENV_PRESET_UNKNOWN", 422, "module", "env", "未知的天气预设", "选择已登记的预设", "core"),
    441: ReasonInfo(441, "ENV_FIELD_UNKNOWN", 422, "module", "env", "环境修改含未登记字段", "按字段登记表修正", "core"),
    442: ReasonInfo(442, "ENV_LEVEL_UNAVAILABLE", 409, "module", "env", "请求的风等级或湍流模型本期不可用", "改用可用等级", "core"),
    443: ReasonInfo(443, "ENV_ASSET_INVALID", 500, "module", "env", "环境资产校验失败", "重新生成环境资产", "core"),
    460: ReasonInfo(460, "REC_DISK_LOW", 507, "module", "rec", "可用空间不足，拒绝开始录制", "清理 runs 目录", "ext"),
    461: ReasonInfo(461, "REC_SEGMENT_CORRUPT", 409, "module", "rec", "录制段损坏且修复失败", "选择其他录制段", "ext"),
    462: ReasonInfo(462, "BOOKMARK_LIMIT", 409, "module", "rec", "书签数量超过上限", "删除部分书签", "ext"),
    463: ReasonInfo(463, "REPLAY_NOT_OPEN", 409, "module", "rec", "该运行未处于回放打开状态", "先打开回放", "ext"),
    470: ReasonInfo(470, "AGENT_GUARD_INTERNAL", 500, "module", "agent", "受信守卫内部异常", "查看 agent-runtime 日志", "ext"),
    471: ReasonInfo(471, "CAPABILITY_UNKNOWN", 422, "module", "agent", "能力 id 不合语法或不在目录", "使用目录中的能力 id", "ext"),
    472: ReasonInfo(472, "CAPABILITY_NOT_SERVED", 409, "module", "agent", "提供方不服务该能力", "换能力或换提供方", "ext"),
    473: ReasonInfo(473, "NO_CANDIDATE", 409, "module", "agent", "没有可用的候选提供方", "稍后重试或增加提供方", "ext"),
    474: ReasonInfo(474, "ALL_INFEASIBLE", 409, "module", "agent", "全部报价不可行", "调整目标或补充电量", "ext"),
    475: ReasonInfo(475, "QUOTE_TIMEOUT", 504, "module", "agent", "报价截止前无回复", "检查 agent-runtime 与仿真进程", "ext"),
    476: ReasonInfo(476, "DELEGATION_REJECTED", 409, "module", "agent", "提供方拒绝委派", "自动更换候选", "ext"),
    477: ReasonInfo(477, "EXEC_TIMEOUT", None, "module", "agent", "执行超时", "重新提交任务", "ext"),
    478: ReasonInfo(478, "ACCEPT_FALSE", None, "module", "agent", "验收谓词为假", "自动更换候选", "ext"),
    479: ReasonInfo(479, "EFFECT_UNVERIFIED", None, "module", "agent", "效果未验证", "补充独立读回证据", "ext"),
    480: ReasonInfo(480, "SCOPE_VIOLATION", None, "module", "agent", "违反负向范围", "检查任务范围", "ext"),
    481: ReasonInfo(481, "ESCALATION_TIMEOUT", None, "module", "agent", "升级等待超时", "及时处理升级请求", "ext"),
    482: ReasonInfo(482, "AGENT_SCOPE_FORBIDDEN", 403, "module", "agent", "命令超出智能体的授权范围", "检查委派与能力范围", "ext"),
    483: ReasonInfo(483, "TASK_INTERRUPTED", None, "module", "agent", "任务因进程重启中断", "重新提交任务", "ext"),
    484: ReasonInfo(484, "ANET_WIRE_MISMATCH", 409, "module", "agent", "ANet 协议版本不一致", "按版本锁重建", "V1.0"),
    485: ReasonInfo(485, "ANET_DAEMON_DOWN", 503, "module", "agent", "ANet 守护进程不可达", "等待编排重启", "V1.0"),
    486: ReasonInfo(486, "RECEIPT_INVALID", None, "module", "agent", "回执绑定校验失败", "检查回执来源", "ext"),
    490: ReasonInfo(490, "TIME_UNSYNCED", 422, "module", "georef", "传感器流未对时", "启用 PTP 或 GPS 授时", "V0.5"),
    491: ReasonInfo(491, "UNIT_MISMATCH", 422, "module", "georef", "IMU 加速度单位不符", "检查 IMU 来源与原始单位", "V0.5"),
    492: ReasonInfo(492, "EXTRINSIC_NOT_IDENTITY", 422, "module", "georef", "驱动侧外参不是恒等", "将驱动外参置零", "V0.5"),
    493: ReasonInfo(493, "CALIB_MISSING", 409, "module", "georef", "引用的标定版本不存在", "先完成标定", "V0.5"),
    494: ReasonInfo(494, "GNSS_INSUFFICIENT", 409, "module", "georef", "GNSS 数据不足", "延长采集或补充 RTK", "V0.5"),
    495: ReasonInfo(495, "COLLINEAR_NO_GRAVITY", 409, "module", "georef", "航带共线且缺少重力信息", "提供 IMU 姿态或人工复核", "V0.5"),
    496: ReasonInfo(496, "SIM3_OUT_OF_BASIN", 409, "module", "georef", "配准门禁失败", "人工粗对齐后重试", "V0.5"),
    497: ReasonInfo(497, "QA_GATE_FAILED", 409, "module", "georef", "质量门禁未通过", "查看报告后补飞或调参", "V0.5"),
    498: ReasonInfo(498, "RELEASE_IMMUTABLE", 409, "module", "georef", "已发布版本不可修改", "发布新版本", "V0.5"),
    499: ReasonInfo(499, "RELEASE_INTEGRITY", 409, "module", "georef", "发布包完整性校验失败", "重新下发正确版本", "V0.5"),
}

DETAIL_ONLY: frozenset[str] = frozenset(("SENSOR_SPEC_INVALID", "SENSOR_UNKNOWN", "TARGET_TABLE_FULL", "TARGET_ID_DUP", "JOB_WORKER_UNAVAILABLE", "PREVIEW_EXPIRED", "PREDICATE_MALFORMED", "KERNEL_LIMIT", "WORLD_NOT_IN_SESSION", "GEO_CEILING"))
WARNINGS: frozenset[str] = frozenset(("SPEED_CLAMPED",))
WS_CLOSE: dict[str, int] = {"NORMAL": 1000, "GOING_AWAY": 1001, "PROTOCOL_ERROR": 1002, "ABNORMAL": 1006, "POLICY_VIOLATION": 1008, "MESSAGE_TOO_BIG": 1009, "INTERNAL_ERROR": 1011, "CONTROL_BACKLOG": 1013, "AUTH": 4401, "SEAT_REVOKED": 4403, "HELLO_TIMEOUT": 4408, "VERSION_MISMATCH": 4426, "CONN_LIMIT": 4429}


def info(code: int) -> ReasonInfo:
    return REASONS[int(code)]


def http_status(code: int) -> int:
    """HTTP status for a REST problem+json response; codes without a mapping use 409."""
    h = REASONS[int(code)].http
    return 409 if h is None else h
