"""RNG stream registry from packages/contracts/rt/rng_streams.json (AWR-17 §10.8; ADR-049).

Generated by tools/contracts/gen.py from packages/contracts. Do not edit."""

from __future__ import annotations

from enum import IntEnum

import numpy as np


class Stream(IntEnum):
    DRYDEN = 1
    FAULTS = 2
    SENSOR_NOISE = 3
    DETECTOR = 4
    ANET_MOCK_LATENCY = 5
    GUST_SCHEDULE = 6
    GEOREF_RANSAC = 8
    GEOREF_MOCK_GNSS = 9
    GEOREF_SUBSAMPLE = 10
    RECON_MOCK_SUBSAMPLE = 11
    RECON_MOCK_GAUGE = 12
    RECON_MOCK_DEPTH_NOISE = 13
    RECON_MOCK_GNSS = 14
    RECON_MOCK_GRAVITY = 15
    RECON_SELFCHECK = 16


def rng(world_seed: int, stream: int, *keys: int) -> np.random.Generator:
    """PCG64(SeedSequence([world_seed, stream_id, *keys])); keys derive keyed child sequences (stream 5)."""
    return np.random.Generator(np.random.PCG64(np.random.SeedSequence([int(world_seed), int(stream), *map(int, keys)])))
