"""SafetyEvent catalogue from packages/contracts/rt/safety_codes.json (M09 §6.13).

Generated by tools/contracts/gen.py from packages/contracts. Do not edit."""

from __future__ import annotations

from typing import NamedTuple


class SafetyCode(NamedTuple):
    code: str
    type: str
    cls: str
    level: int
    fsm: str | None
    ui: str
    icon: str
    merge_key: str | None
    d1: str


SAFETY_CODES: dict[str, SafetyCode] = {
    "SAF.GEOFENCE.NEAR": SafetyCode("SAF.GEOFENCE.NEAR", "safety.geofence", "warn", 2, None, "warning", "alert.geofence", "safety:geofence:near", "core"),
    "SAF.GEOFENCE.BREACH": SafetyCode("SAF.GEOFENCE.BREACH", "safety.geofence", "action", 2, "CORRECTING/GEOFENCE", "warning", "alert.geofence", "safety:correcting:geofence", "core"),
    "SAF.GEOFENCE.CORRECT_TIMEOUT": SafetyCode("SAF.GEOFENCE.CORRECT_TIMEOUT", "safety.geofence", "action", 2, "RTL (AUTO)", "warning", "mode.rtl", "safety:rtl:geofence", "core"),
    "SAF.GEOFENCE.FAR_OUT": SafetyCode("SAF.GEOFENCE.FAR_OUT", "safety.geofence", "action", 2, "RTL (AUTO)", "warning", "mode.rtl", "safety:rtl:geofence", "core"),
    "SAF.GEOFENCE.RESTRICTED": SafetyCode("SAF.GEOFENCE.RESTRICTED", "safety.geofence", "warn", 2, None, "warning", "zone.nofly", "safety:geofence:restricted", "core"),
    "SAF.GEOFENCE.RESTORED": SafetyCode("SAF.GEOFENCE.RESTORED", "safety.geofence", "info", 1, "FLYING/HOVER", "info", "alert.success", None, "core"),
    "SAF.ALT.MAX": SafetyCode("SAF.ALT.MAX", "safety.geofence", "action", 2, "CORRECTING/ALT_MAX", "warning", "alert.geofence", "safety:correcting:alt", "core"),
    "SAF.ALT.MIN": SafetyCode("SAF.ALT.MIN", "safety.geofence", "action", 2, "CORRECTING/ALT_MIN", "warning", "alert.geofence", "safety:correcting:alt", "core"),
    "SAF.BAT.LOW": SafetyCode("SAF.BAT.LOW", "safety.battery", "warn", 2, None, "warning", "alert.battery", "safety:battery:low", "core"),
    "SAF.BAT.CRIT": SafetyCode("SAF.BAT.CRIT", "safety.battery", "action", 2, "RTL (AUTO)", "warning", "alert.battery", "safety:rtl:battery", "core"),
    "SAF.BAT.ENERGY_RTL": SafetyCode("SAF.BAT.ENERGY_RTL", "safety.battery", "action", 2, "RTL (AUTO)", "warning", "alert.battery", "safety:rtl:battery", "core"),
    "SAF.BAT.EMERG": SafetyCode("SAF.BAT.EMERG", "safety.battery", "critical", 3, "LANDING (AUTO)", "critical", "alert.battery", "safety:land:battery", "core"),
    "SAF.LINK.DEGRADED": SafetyCode("SAF.LINK.DEGRADED", "safety.link", "warn", 2, None, "warning", "alert.linklost", "safety:link:degraded", "core"),
    "SAF.LINK.LOST_HOLD": SafetyCode("SAF.LINK.LOST_HOLD", "safety.link", "action", 2, "HOLD/LINK_LOSS", "warning", "alert.linklost", "safety:hold:link_loss", "core"),
    "SAF.LINK.LOST_RTL": SafetyCode("SAF.LINK.LOST_RTL", "safety.link", "action", 2, "RTL or LANDING (AUTO)", "warning", "mode.rtl", "safety:rtl:link", "core"),
    "SAF.LINK.WATCHDOG": SafetyCode("SAF.LINK.WATCHDOG", "safety.link", "action", 2, "HOLD/LINK_LOSS", "warning", "cmd.velocity", "safety:hold:watchdog", "core"),
    "SAF.LINK.RESTORED": SafetyCode("SAF.LINK.RESTORED", "safety.link", "info", 1, "FLYING/HOVER", "info", "alert.success", None, "core"),
    "SAF.LINK.AGENT_LOST": SafetyCode("SAF.LINK.AGENT_LOST", "safety.link", "action", 2, "same B ladder", "warning", "agent", "safety:hold:agent_link", "ext"),
    "SAF.EST.TIMEOUT": SafetyCode("SAF.EST.TIMEOUT", "safety.fastguard", "critical", 3, "FAILSAFE/DESCENT", "critical", "alert.critical", "safety:failsafe", "core"),
    "SAF.EST.LOC_LOST": SafetyCode("SAF.EST.LOC_LOST", "safety.loc", "action", 2, "HOLD/LOC_LOST then LANDING", "warning", "alert.warning", "safety:hold:loc", "ext"),
    "SAF.CTRL.POS_ERR_ELAND": SafetyCode("SAF.CTRL.POS_ERR_ELAND", "safety.fastguard", "critical", 3, "ELAND", "critical", "alert.critical", "safety:eland", "core"),
    "SAF.CTRL.TILT_ELAND": SafetyCode("SAF.CTRL.TILT_ELAND", "safety.fastguard", "critical", 3, "ELAND", "critical", "alert.critical", "safety:eland", "core"),
    "SAF.CTRL.YAW_ERR": SafetyCode("SAF.CTRL.YAW_ERR", "safety.fastguard", "critical", 3, "ELAND", "critical", "alert.critical", "safety:eland", "core"),
    "SAF.CTRL.THROTTLE_SAT": SafetyCode("SAF.CTRL.THROTTLE_SAT", "safety.fastguard", "critical", 3, "ELAND", "critical", "alert.critical", "safety:eland", "core"),
    "SAF.CTRL.POS_ERR_FAILSAFE": SafetyCode("SAF.CTRL.POS_ERR_FAILSAFE", "safety.fastguard", "critical", 3, "FAILSAFE", "critical", "alert.critical", "safety:failsafe", "core"),
    "SAF.CTRL.TILT_KILL": SafetyCode("SAF.CTRL.TILT_KILL", "safety.fastguard", "critical", 3, "DISARMED/KILLED", "critical", "alert.emergency", "safety:kill", "core"),
    "SAF.CTRL.TILT_ERR_KILL": SafetyCode("SAF.CTRL.TILT_ERR_KILL", "safety.fastguard", "critical", 3, "DISARMED/KILLED", "critical", "alert.emergency", "safety:kill", "core"),
    "SAF.CTRL.TRACK_DEGRADED": SafetyCode("SAF.CTRL.TRACK_DEGRADED", "safety.fastguard", "warn", 2, None, "warning", "alert.warning", "safety:track", "core"),
    "SAF.SEP.CONFLICT": SafetyCode("SAF.SEP.CONFLICT", "safety.separation", "warn", 2, None, "warning", "alert.collision", "safety:sep:conflict", "core"),
    "SAF.SEP.AVOIDING": SafetyCode("SAF.SEP.AVOIDING", "safety.separation", "action", 2, "HOLD/SEPARATION", "warning", "alert.collision", "safety:hold:separation", "core"),
    "SAF.SEP.VIOLATION": SafetyCode("SAF.SEP.VIOLATION", "safety.separation", "action", 2, "HOLD/SEPARATION", "warning", "alert.collision", "safety:hold:separation", "core"),
    "SAF.SEP.RESTORED": SafetyCode("SAF.SEP.RESTORED", "safety.separation", "info", 1, "FLYING/HOVER", "info", "alert.success", None, "core"),
    "SAF.SEP.OSCILLATION": SafetyCode("SAF.SEP.OSCILLATION", "safety.separation", "warn", 2, "Track stays suspended", "warning", "alert.collision", "safety:sep:osc", "core"),
    "SAF.SEP.COLLISION": SafetyCode("SAF.SEP.COLLISION", "safety.separation", "critical", 3, "CRASHED/COLLISION_UAV", "critical", "alert.collision", "safety:crash", "core"),
    "SAF.WORLD.COLLISION": SafetyCode("SAF.WORLD.COLLISION", "safety.fsm", "critical", 3, "CRASHED/COLLISION_WORLD", "critical", "alert.critical", "safety:crash", "core"),
    "SAF.WORLD.IMPACT": SafetyCode("SAF.WORLD.IMPACT", "safety.fsm", "critical", 3, "CRASHED/IMPACT", "critical", "alert.critical", "safety:crash", "core"),
    "SAF.ENV.WIND_LIMIT": SafetyCode("SAF.ENV.WIND_LIMIT", "safety.env", "warn", 2, None, "warning", "alert.wind", "safety:env:wind", "ext"),
    "SAF.OP.SAFETY_STOP": SafetyCode("SAF.OP.SAFETY_STOP", "safety.fsm", "action", 2, "HOLD/SAFETY_STOP", "warning", "mission.abort", None, "core"),
    "SAF.OP.RESUME": SafetyCode("SAF.OP.RESUME", "safety.fsm", "info", 1, "FLYING/HOVER", "info", "mission.start", None, "core"),
    "SAF.OP.ESCALATE": SafetyCode("SAF.OP.ESCALATE", "safety.fsm", "critical", 3, "ELAND and above", "critical", "alert.emergency", "safety:op", "ext"),
    "SAF.OP.KILL": SafetyCode("SAF.OP.KILL", "safety.fsm", "critical", 3, "DISARMED/KILLED", "critical", "alert.emergency", "safety:op", "ext"),
    "SAF.FSM.PREFLIGHT_FAILED": SafetyCode("SAF.FSM.PREFLIGHT_FAILED", "safety.fsm", "info", 1, None, "info", "alert.info", None, "core"),
    "SAF.FSM.PREFLIGHT_INACTION": SafetyCode("SAF.FSM.PREFLIGHT_INACTION", "safety.fsm", "info", 1, "DISARMED", "info", "alert.info", None, "core"),
    "SAF.FSM.REJECTED": SafetyCode("SAF.FSM.REJECTED", "safety.fsm", "info", 1, None, "info", "alert.info", None, "core"),
    "SAF.FAULT.INJECTED": SafetyCode("SAF.FAULT.INJECTED", "safety.fault", "warn", 2, None, "warning", "alert.warning", "safety:fault", "ext"),
    "SAF.FAULT.CLEARED": SafetyCode("SAF.FAULT.CLEARED", "safety.fault", "info", 1, None, "info", "alert.warning", "safety:fault", "ext"),
    "HLT.SAFETY.STAGE_ERROR": SafetyCode("HLT.SAFETY.STAGE_ERROR", "safety.health", "critical", 3, "all vehicles HOLD after 3 in a row", "critical", "alert.critical", "safety:health", "core"),
}
