"""Topic table from packages/contracts/rt/topics.json (AWR-17 §6.6).

Generated by tools/contracts/gen.py from packages/contracts. Do not edit."""

from __future__ import annotations

import re
from typing import NamedTuple

RATE_CLASSES: tuple[int, ...] = (1, 2, 5, 10, 15, 20, 30, 60)
TICK_HZ = 60
CHUNK_RE = re.compile("^[a-z0-9][a-z0-9_-]*$")


class Topic(NamedTuple):
    pattern: str
    kind: str
    encoding: str
    schema_name: str
    native_hz: float
    default_rate: dict[str, int] | None
    mode: str | None
    priority: int | None
    self_contained: bool
    owner: str
    d1: str
    aliases: tuple[str, ...]
    regex: re.Pattern[str]


def _rx(p: str) -> re.Pattern[str]:
    return re.compile("^" + re.sub(r"\\\{\w+\\\}", "[a-z0-9][a-z0-9_-]*", re.escape(p)) + "$")


TOPICS: tuple[Topic, ...] = (
    Topic("fleet/roster", "roster", "msgpack", "awr.fleet.roster.v1", 0, {"S": 10, "B": 10, "A": 10}, "latest", 0, True, "M08", "core", (), _rx("fleet/roster")),
    Topic("swarm/uav/state", "state", "raw", "awr.SwarmLite32.v1", 125, {"S": 10, "B": 20, "A": 20}, "latest", 1, False, "M08", "core", ("swarm/state",), _rx("swarm/uav/state")),
    Topic("uav/{id}/state", "state", "raw", "awr.DroneState64.v1", 125, {"S": 30, "B": 30, "A": 30}, "latest", 0, False, "M08", "core", (), _rx("uav/{id}/state")),
    Topic("uav/{id}/state_ext", "state", "msgpack", "awr.uav.state_ext.v1", 2, {"S": 2, "B": 2, "A": 2}, "latest", 2, True, "M08", "core", (), _rx("uav/{id}/state_ext")),
    Topic("uav/{id}/safety", "state", "msgpack", "awr.uav.safety.v1", 10, {"S": 5, "B": 5, "A": 5}, "latest", 1, True, "M09", "core", (), _rx("uav/{id}/safety")),
    Topic("uav/{id}/env", "state", "raw", "awr.EnvSample32.v1", 10, {"S": 10, "B": 10, "A": 10}, "latest", 2, False, "M07", "core", (), _rx("uav/{id}/env")),
    Topic("uav/{id}/sensor/{name}/pose", "state", "raw", "awr.SensorPose48.v1", 10, {"S": 10, "B": 10, "A": 10}, "latest", 2, False, "M13", "core", (), _rx("uav/{id}/sensor/{name}/pose")),
    Topic("uav/{id}/path", "blob", "blob", "awr.blob.polyline4.v1", 0, {"S": 2, "B": 2, "A": 2}, "latest", 2, True, "M10", "core", (), _rx("uav/{id}/path")),
    Topic("mission/{mid}/status", "state", "msgpack", "awr.mission.status.v1", 1, {"S": 2, "B": 2, "A": 2}, "latest", 2, True, "M10", "core", (), _rx("mission/{mid}/status")),
    Topic("mission/{mid}/coverage", "blob", "blob", "awr.blob.grid_u8.v1", 1, {"S": 1, "B": 1, "A": 1}, "latest", 3, True, "M10", "ext", (), _rx("mission/{mid}/coverage")),
    Topic("env/state", "state", "msgpack", "awr.env.keyframe.v1", 1, {"S": 10, "B": 10, "A": 10}, "latest", 2, True, "M07", "core", (), _rx("env/state")),
    Topic("event", "event", "json", "awr.event.v1", 0, {"S": 0, "B": 0, "A": 0}, "all", 0, False, "M11", "core", (), _rx("event")),
    Topic("perf/server", "state", "msgpack", "awr.perf.server.v1", 1, {"S": 1, "B": 1, "A": 1}, "latest", 3, True, "M11", "core", (), _rx("perf/server")),
    Topic("sys/procs", "state", "msgpack", "awr.sys.procs.v1", 1, {"S": 1, "B": 1, "A": 1}, "latest", 3, True, "M11", "core", (), _rx("sys/procs")),
    Topic("perf/clients", "state", "msgpack", "awr.perf.clients.v1", 1, {"S": 1, "B": 1, "A": 1}, "latest", 3, True, "M11", "ext", (), _rx("perf/clients")),
    Topic("agent/{aid}/status", "state", "msgpack", "awr.agent.status.v1", 1, {"S": 1, "B": 1, "A": 1}, "latest", 2, True, "M14", "ext", (), _rx("agent/{aid}/status")),
    Topic("agent/tasks", "state", "msgpack", "awr.agent.tasks.v1", 0, {"S": 2, "B": 2, "A": 2}, "latest", 2, True, "M14", "ext", (), _rx("agent/tasks")),
    Topic("uav/{id}/setpoint", "client", "raw", "awr.VelSetpoint16.v1", 50, None, None, None, False, "M08", "core", (), _rx("uav/{id}/setpoint")),
    Topic("uav/{id}/sensor/lidar/scan", "state", "raw", "awr.LidarScan8.v1", 10, {"S": 5, "B": 5, "A": 5}, "latest", 3, False, "M13", "V0.2", (), _rx("uav/{id}/sensor/lidar/scan")),
    Topic("env/wind/frame", "blob", "blob", "awr.env.AwrvHeader.v1", 2, None, "latest", 3, True, "M07", "V0.4", (), _rx("env/wind/frame")),
)


def match_topic(topic: str) -> Topic | None:
    for t in TOPICS:
        if t.regex.match(topic) or topic in t.aliases:
            return t
    return None


def quantize_rate(rate: float) -> int:
    """Round a requested rate up to the nearest rate class; 0 means native rate capped by the tick (AWR-17 §6.7)."""
    if rate <= 0:
        return TICK_HZ
    for r in RATE_CLASSES:
        if r >= rate:
            return r
    return RATE_CLASSES[-1]


def valid_topic(topic: str, allow_wildcards: bool = False) -> bool:
    """zenoh key-expr subset: chunks [a-z0-9][a-z0-9_-]*; * and ** only in subscriptions."""
    parts = topic.split("/")
    return bool(parts) and all(CHUNK_RE.match(p) or (allow_wildcards and p in ("*", "**")) for p in parts)
