"""Unit suffix dictionary from packages/contracts/rt/units.json (AWR-03 §5.4).

Generated by tools/contracts/gen.py from packages/contracts. Do not edit."""

from __future__ import annotations

SUFFIXES: dict[str, tuple[str, str]] = {
    "_m": ("m", "length, position"),
    "_mps": ("m/s", "speed"),
    "_mps2": ("m/s^2", "acceleration"),
    "_rad": ("rad", "angle"),
    "_rad_s": ("rad/s", "angular rate"),
    "_deg": ("deg", "angle (meteorology and UI only)"),
    "_deg_s": ("deg/s", "angular rate (UI and gimbal)"),
    "_ns": ("ns", "time point, int64"),
    "_ms": ("ms", "duration in MILLISECONDS only"),
    "_s": ("s", "duration"),
    "_us": ("us", "duration in microseconds"),
    "_pct": ("%", "percentage 0-100, u8 255 = unknown"),
    "_mmh": ("mm/h", "precipitation rate (snow as water equivalent)"),
    "_pa": ("Pa", "pressure"),
    "_c": ("degC", "temperature"),
    "_kgm3": ("kg/m^3", "density"),
    "_w": ("W", "power"),
    "_wh": ("Wh", "energy"),
    "_hz": ("Hz", "frequency"),
    "_per_m": ("1/m", "extinction coefficient"),
    "_v": ("V", "voltage"),
    "_a": ("A", "current"),
    "_ah": ("Ah", "battery capacity"),
    "_kbps": ("kbit/s", "bandwidth"),
    "_mb": ("MiB", "size"),
    "_core": ("core", "CPU cores (core-seconds per second)"),
    "_ms_per_s": ("ms/s", "CPU time per simulated second"),
    "_dps": ("deg/s", "yaw rate statistics"),
    "_px": ("px", "pixels"),
    "_kg": ("kg", "mass"),
    "_kgm2": ("kg*m^2", "inertia"),
    "_m2": ("m^2", "area"),
    "_m2kg": ("m^2/kg", "area per mass"),
    "_n": ("N", "force"),
    "_n_per_mps": ("N/(m/s)", "linear drag coefficient"),
    "_k": ("K", "temperature difference (netd)"),
    "_mm": ("mm", "small length"),
    "_km": ("km", "length (display)"),
    "_per_min": ("1/min", "rate"),
    "_pct_s": ("%/s", "rate of percentage"),
    "_mb_per_min": ("MiB/min", "write rate"),
    "_mb_per_s": ("MiB/s", "throughput"),
    "_cms": ("cm/s", "Lite32 vel_cms only (binary layout)"),
    "_milli": ("x1/1000", "fixed point x1000 (StateRing rate_milli, rtf_milli)"),
}
DENIED_SUFFIXES: dict[str, str] = {"_m_s": "write _mps", "_msec": "write _ms", "_sec": "write _s", "_secs": "write _s", "_kmh": "write _mps", "_kts": "write _mps", "_ft": "write _m", "_feet": "write _m", "_meters": "write _m", "_degrees": "write _deg", "_mph": "write _mps"}
DENIED_NAMES: dict[str, str] = {"speed_ms": "speed_mps", "gust_amp_ms": "gust_amp_mps", "vmax_ms": "vmax_mps", "w_mean_ms": "w_mean_mps", "turb_sigma_u_ref_ms": "turb_sigma_u_ref_mps", "wind_rating_ms": "wind_rating_mps", "speed_ref_ms": "speed_ref_mps", "ref_speed_ms": "ref_speed_mps"}
UNIT_LIKE_TOKENS: frozenset[str] = frozenset(("m", "mps", "ms", "s", "us", "ns", "deg", "rad", "hz", "pct", "kg", "km", "cm", "mm", "kmh", "kts", "ft", "min", "h", "sec", "secs", "msec", "mph", "w", "wh", "v", "a", "pa", "c", "px", "mb", "kb", "kbps", "n"))
EXCEPTIONS: dict[str, str] = {"noise_density": "rad/s/sqrt(Hz) (gyro), m/s^2/sqrt(Hz) (accel)", "random_walk": "rad/s^2/sqrt(Hz) (gyro), m/s^3/sqrt(Hz) (accel)", "turn_on_sigma": "rad/s (gyro), m/s^2 (accel)", "factor_sigma": "1", "c_rd": "N*s^2/(m*rad)", "k_f": "N*s^2/rad^2", "km_m": "m", "sih_kdv_equiv": "N/(m/s)", "vmax_per_ref": "1", "acc_unit": "string g", "gyro_unit": "string"}
