// Motion system (M15 §7.1.4; ADR-029).
export { useMotionTier, useMotionSource, getMotionTier, getMotionSource, initMotionTier, setUserMotion, setGovernorMotion, setTestMotion, resolveTier, type MotionTier, type MotionSource, type UserMotion } from './tier'
export { motionBudget, type LoopHandle } from './budget'
export { bindText, flushTexts } from './bindText'
export { MotionNumber, changedDigits } from './MotionNumber'
export { SwapText } from './SwapText'
export { NotificationDot } from './NotificationDot'
export { ShakeOnce } from './ShakeOnce'
export { SkeletonReveal } from './SkeletonReveal'
export { ShimmerText } from './ShimmerText'
export { MatrixLoader } from './MatrixLoader'
export { usePresence } from './usePresence'
export { useReplay } from './useReplay'
export { useListPresence } from './useListPresence'
export { MOTION, EASE, EASE_CSS, SPRINGS } from './tokens'
