"""Numbers quoted in the text, computed from paper/data and written as LaTeX macros (sections/numbers.tex), plus the
parity rows of the consistency table (sections/table_parity_rows.tex)."""

from __future__ import annotations

import pandas as pd

import rtl_common as C
import style as S

SEC = S.ROOT / "sections"
PARITY = {"eval_env": "Field evaluation (wind, gust, optics)", "derive": "Derived weather quantities",
          "sector_slots": "Wind sectors and slots", "conventions": "Frame and unit conventions", "gust": "Gust events",
          "optical_depth": "Slant optical depth", "turb": "Turbulence box", "isa": "Standard atmosphere",
          "anchors": "Keyframe anchors", "profile": "Vertical wind profile"}


def pct(x: float) -> str:
    return f"{100 * x:.1f}"


def main() -> None:
    m: dict[str, str] = {}
    d = C.load()
    m["RTLSEEDS"] = str(d.seed.nunique())
    m["RTLSORTIES"] = f"{len(d):,}"
    m["RTLSORTIESPOL"] = f"{len(d[d.policy == 'coupled']):,}"
    for key, pol in (("PX", "px4"), ("CP", "coupled"), ("DC", "px4_time")):
        x = d[d.policy == pol]
        m[f"{key}UNSAFE"] = pct(x.unsafe.mean())
        m[f"{key}DONE"] = pct(x.completed.mean())
    d["wg"] = d.preset.map(C.weather_group)
    for gk, g in (("CALM", "Calm"), ("WET", "Wet, windy"), ("SEV", "Severe")):
        for key, pol in (("PX", "px4"), ("CP", "coupled")):
            x = d[(d.wg == g) & (d.policy == pol)]
            for col, name in (("completed", "DONE"), ("lost", "LOST"), ("declined", "DECL"), ("over_rating", "OVER")):
                m[f"{key}{gk}{name}"] = f"{100 * x[col].mean():.0f}"
    cw = d[(d.policy == "px4") & (d.wg != "Severe")].groupby("world").unsafe.mean().sort_values()
    names = {"sanfrancisco": "San Francisco", "newyork": "New York", "suzhou": "Suzhou", "shenzhen": "Shenzhen",
             "shanghai": "Shanghai", "chicago": "Chicago", "synthcity": "SynthCity"}
    m["PXCITYLO"], m["PXCITYLOW"] = f"{100 * cw.iloc[0]:.0f}", names[cw.index[0]]
    m["PXCITYHI"], m["PXCITYHIW"] = f"{100 * cw.iloc[-1]:.0f}", names[cw.index[-1]]
    r = d[d.rtl_cmd.astype(bool) & d.z_max_rtl_m.notna()].copy()
    r["climb"] = r.z_max_rtl_m - r.z_home_m
    for key, pol in (("PX", "px4"), ("ND", "no_detour"), ("CP", "coupled")):
        m[f"{key}CLIMB"] = f"{r[r.policy == pol].climb.median():.0f}"
        m[f"{key}RETWH"] = f"{r[r.policy == pol].wh_return.mean():.1f}"
        m[f"{key}COLL"] = pct(d[d.policy == pol].collision.mean())
    s = C.summary(d, ["policy"]).set_index("policy")
    f1 = lambda v: f"{v:.1f}"
    m["NGCOLL"], m["NGDONE"] = f1(s.at["no_geometry", "collision"]), f1(s.at["no_geometry", "completed"])
    m["NWDONE"], m["NWUNSAFE"] = f1(s.at["no_wind", "completed"]), f1(s.at["no_wind", "unsafe"])
    m["NSABORT"], m["CPABORT"] = f1(s.at["no_shared", "aborted"]), f1(s.at["coupled", "aborted"])
    m["NSDONE"] = f1(s.at["no_shared", "completed"])
    m["NSWHPCT"] = f"{100 * (s.at['no_shared', 'wh_completed'] / s.at['coupled', 'wh_completed'] - 1):.0f}"
    m["NDGAIN"] = f1(s.at["coupled", "completed"] - s.at["no_detour", "completed"])
    m["NESTRAND"] = f1(s.at["no_energy", "stranded"])
    m["NPUNSAFE"] = f1(s.at["no_precheck", "unsafe"])
    from fig_micro import STAGE_GROUPS

    sg = S.load("micro_stages2")
    sg = sg.assign(wall=1e3 * sg.wall_s / sg.sim_s).groupby("n").median(numeric_only=True)
    m["STAGERTF"] = f"{sg.at[1000, 'rtf']:.1f}"
    m["STAGERTFTEN"] = f"{sg.at[10, 'rtf']:.1f}"
    m["STAGECORE"] = f"{sg.at[1000, 'wall'] / 1e3:.2f}"
    m["STGTOT"], m["STGWALL"] = f"{sg.at[1000, 'stage_total_ms_per_s']:.0f}", f"{sg.at[1000, 'wall']:.0f}"
    for key, g in (("SAFE", "Safety and energy"), ("DYN", "Dynamics and control"), ("MIS", "Missions"),
                   ("ENV", "Environment"), ("PUB", "State publication")):
        cs = [f"st_{n}" for n in STAGE_GROUPS[g] if f"st_{n}" in sg]
        m[f"STG{key}"] = f"{sg.loc[1000, cs].sum():.0f}"
        m[f"STG{key}TEN"] = f"{sg.loc[10, cs].sum():.0f}"
    with open(SEC / "numbers.tex", "w") as f:
        f.write("% generated by paper/figures/numbers.py\n")
        for k, v in m.items():
            f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
    det = S.load("determinism_full")
    g = det.groupby(["world", "preset", "seed", "t_s"]).hash.nunique()
    DET = (len(g), 100.0 * float((g == 1).mean()))
    p = pd.read_csv(S.DATA / "consistency_env_parity.csv").sort_values("outputs", ascending=False)
    with open(SEC / "table_consistency.tex", "w") as f:
        f.write("% generated by paper/figures/gen_numbers.py\n\\begin{table}[t]\n"
                "\\caption{Consistency of the shared environment model between the server and the browser, and replay "
                "determinism of the fleet runtime.}\\label{tab:consistency}\n\\footnotesize\n"
                "\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}}lrrr@{}}\n\\toprule\n"
                "Environment function & Outputs & Bit-identical & Max.\\ abs.\\ difference \\\\\n\\midrule\n")
        for r in p.itertuples():
            mx = "0" if r.max_abs == 0 else f"${r.max_abs:.1e}".replace("e-", r"\times10^{-") + "}$"
            mx = mx.replace("{-0", "{-")
            f.write(f"{PARITY[r.group]} & {r.outputs:,} & {100 * r.bit_exact:.1f}\\% & {mx} \\\\\n")
        tot = p.outputs.sum()
        be = (p.outputs * p.bit_exact).sum() / tot
        f.write(f"\\emph{{All environment functions}} & {tot:,} & {100 * be:.1f}\\% & "
                f"${p.max_abs.max():.1e}".replace("e-", r"\times10^{-") + "}$ \\\\\n")
        f.write(f"\\midrule\nFleet replay (state hash per second) & {DET[0]:,} & {DET[1]:.0f}\\% & 0 \\\\\n"
                "\\bottomrule\n\\end{tabular*}\n\\end{table}\n")
    print(m)


if __name__ == "__main__":
    main()
