// env-gpu (M07-AC-016; D1-AC-13 GPU sampling): GPU windAtEnu (L0/L1 log profile + DTM bilinear from the live world +
// 4 active fronts + turbulence box texture3D) against windCPU at 32 x 32 points, thunderstorm state; tolerance
// 0.01 vmax + 0.02 m/s with vmax = derive().vmax_vis_mps. Tier S (classic WebGL2 on SwiftShader) and Tier B.
import { expect, test } from '@playwright/test'
import { m07Server, openEnv, pageErrors } from './common'
import { sharedSeeds } from './server'

const srv = m07Server(1)

for (const tier of ['S', 'B'] as const) {
  test(`env-gpu Tier ${tier}: windAtEnu vs windCPU <= 0.01 vmax + 0.02`, async ({ page }) => {
    await openEnv(page, srv.get().url, `&tier=${tier}`)
    const seed = sharedSeeds()[0] // the shared turbulence box generated by sim-core (worlds/_shared/env/turb)
    const r = await page.evaluate(async (s) => {
      const env = (window as unknown as { __env: { gpuParity(seed?: number, waitTurbMs?: number): Promise<Record<string, number | boolean>> } }).__env
      return env.gpuParity(s, s === undefined ? 0 : 15_000)
    }, seed)
    expect(r.points).toBe(1024)
    expect(r.gusty as number).toBeGreaterThan(0)
    if (seed !== undefined) expect(r.turb).toBe(true)
    expect(r.worst as number).toBeLessThanOrEqual(r.bound as number)
    expect(pageErrors(page)).toEqual([])
  })
}
