#!/usr/bin/env python3
"""transitions.dev skills/transitions-dev/_root.css -> apps/web/src/styles/motion/tokens.css (M15-FR-045, FR-050; g07 §3.2).

Usage:
  python3 tools/shadcn/gen-motion-tokens.py [ROOT_CSS] [OUT] [--check]

Defaults: ROOT_CSS = refs/design/transitions.dev/skills/transitions-dev/_root.css (snapshot e2d5551, tools/shadcn/VENDOR.md),
OUT = apps/web/src/styles/motion/tokens.css. With --check the output is compared with OUT and the exit code is 1 on drift.

Output layout (AWR-15 §8.1, §13.3; g07 §3.2-§3.3):
  1. `@theme static`: --ease-* and --blur-* (Tailwind namespaces, emitted even when unused because JS reads them) and the
     --transition-duration-* aliases so that `duration-fast` style utilities exist; the defaults for transition-colors.
  2. `@layer theme :root`: the shared --duration/--distance/--scale scale and the 32 recipe variable groups verbatim.
  3. `.dark`: recipe colour variables re-pointed at semantic tokens (d02 §4.3).
The project extension keys (--distance-drawer, --stagger-cap, --duration-camera-*, --duration-lod-fade, --telemetry-*,
--duration-chart-*, --ease-spring-snappy) are NOT emitted here: styles/motion/ext-tokens.css is their only source
(AWR-15 §13.3 migration note).
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SRC = ROOT / "refs/design/transitions.dev/skills/transitions-dev/_root.css"
DEFAULT_OUT = ROOT / "apps/web/src/styles/motion/tokens.css"


def generate(src_text: str) -> str:
    body = src_text[src_text.index(":root {") + 7 : src_text.rindex("}")]
    i = body.index("/* Card resize */")
    shared, recipes = body[:i], body[i:]

    def decl(s):
        return re.findall(r"(--[a-z0-9-]+):\s*([^;]+);", s)

    sh = dict(decl(shared))
    out = [
        "/* ===== transitions.dev motion tokens (generated by tools/shadcn/gen-motion-tokens.py from",
        "   refs/design/transitions.dev/skills/transitions-dev/_root.css; DO NOT EDIT) =====",
        "   @theme static: Tailwind 4.3 only emits the theme variables that are used; JS (bezier sampler, canvas charts, StateIcon)",
        "   reads --ease-* with getComputedStyle, so the block must be static (g07 §3.3). --ease-out and --ease-in-out follow",
        "   transitions.dev (CSS keywords) and override the Tailwind defaults. Tailwind durations live in --transition-duration-*,",
        "   hence the aliases. Extension keys are defined once in ext-tokens.css (AWR-15 §13.3). */",
        "@theme static {",
    ]
    out.extend(
        f"  {k}: {sh[k]};"
        for k in ["--ease-smooth-out", "--ease-in-out", "--ease-out", "--ease-bounce", "--ease-bounce-strong"]
    )
    out.extend(f"  {k}: {sh[k]};" for k in ["--blur-small", "--blur-medium", "--blur-large"])
    out.extend(
        f"  --transition-duration-{k}: var(--duration-{k});"
        for k in ["stagger", "micro", "quick", "fast", "medium", "slow", "very-slow"]
    )
    out += [
        "  --default-transition-duration: var(--duration-quick);",
        "  --default-transition-timing-function: var(--ease-smooth-out);",
        "}",
        "",
        "@layer theme {",
        "  :root {",
    ]
    out.extend(
        f"    {k}: {v.strip()};"
        for k, v in decl(shared)
        if k.startswith(("--duration", "--distance", "--scale")) or k == "--ease-linear"
    )
    out.append("    --check-len: 1;  /* checkbox tick path uses pathLength=1 (g07 §4.2) */")
    out.append("    /* 32 recipe variable groups (verbatim) */")
    out += ["    " + r.strip() for r in recipes.strip().splitlines() if r.strip()]
    out += [
        "  }",
        "  .dark {  /* recipe colours re-pointed at the ANet Graphite semantic tokens (d02 §4.3) */",
        "    --tabs-bar-bg: var(--muted); --tabs-pill-bg: var(--accent); --tabs-text-muted: var(--muted-foreground); --tabs-text-active: var(--foreground);",
        "    --tt-bg: var(--popover); --tt-fg: var(--popover-foreground);",
        "    --shimmer-base: var(--muted-foreground); --shimmer-highlight: var(--foreground);",
        "    --think-base: var(--muted-foreground); --think-highlight: var(--foreground);",
        "    --matrix-base: color-mix(in oklab, var(--foreground) 18%, transparent); --matrix-active: color-mix(in oklab, var(--foreground) 72%, transparent);",
        "    --like-color: var(--brand);",
        "  }",
        "}",
    ]
    return "\n".join(out) + "\n"


def main(argv):
    args = [a for a in argv if not a.startswith("--")]
    src = Path(args[0]) if len(args) > 0 else DEFAULT_SRC
    dst = Path(args[1]) if len(args) > 1 else DEFAULT_OUT
    text = generate(src.read_text(encoding="utf-8"))
    if "--check" in argv:
        cur = dst.read_text(encoding="utf-8") if dst.exists() else ""
        if cur != text:
            print(
                f"gen-motion-tokens: {dst} is out of date; run python3 tools/shadcn/gen-motion-tokens.py",
                file=sys.stderr,
            )
            return 1
        print(f"gen-motion-tokens: {dst.name} up to date")
        return 0
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(text, encoding="utf-8")
    print(f"gen-motion-tokens: wrote {dst} ({text.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
