#!/usr/bin/env python3
"""Python code generator for packages/contracts -> python/awr/contracts (AWR-17 §10.4; AWR-03 §5.10).

Usage:
    python tools/contracts/gen.py            # regenerate
    python tools/contracts/gen.py --check    # exit 1 when the committed output differs

Generated modules: __init__, _paths, enums, layouts, frame, reasons, commands, topics, units, bus_keys,
rng_streams, presets, safety_codes, schema_types. Everything under python/awr/contracts is generated;
hand edits are overwritten.
"""

from __future__ import annotations

import argparse
import json
import keyword
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import contracts_lib as L

HDR = '"""{doc}\n\nGenerated by tools/contracts/gen.py from packages/contracts. Do not edit."""\n\n'


def pylit(v) -> str:
    """Deterministic Python literal for JSON-like values."""
    if v is None:
        return "None"
    if v is True:
        return "True"
    if v is False:
        return "False"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return json.dumps(v, ensure_ascii=False)
    if isinstance(v, (list, tuple)):
        return "(" + ", ".join(pylit(x) for x in v) + ("," if len(v) == 1 else "") + ")"
    if isinstance(v, dict):
        return "{" + ", ".join(f"{json.dumps(k, ensure_ascii=False)}: {pylit(x)}" for k, x in v.items()) + "}"
    raise TypeError(type(v))


def jsonlit(v) -> str:
    """Python literal that keeps JSON lists as lists (for JSON Schema payloads)."""
    if isinstance(v, list):
        return "[" + ", ".join(jsonlit(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{" + ", ".join(f"{json.dumps(k, ensure_ascii=False)}: {jsonlit(x)}" for k, x in v.items()) + "}"
    return pylit(v)


# ---------------------------------------------------------------- __init__ and _paths
def gen_init(c: dict) -> str:
    return (HDR.format(doc="AWR contracts: generated types, dtypes, accessors and tables (AWR-03 §5.10).")
            + f'__version__ = "{c["version"]}"\nCONTRACTS_VERSION = __version__\n'
            + f"LAYOUT_ID = 0x{c['layout_id']:08X}\n\n"
            + '__all__ = ["CONTRACTS_VERSION", "LAYOUT_ID", "__version__"]\n')


def gen_paths() -> str:
    return (HDR.format(doc="Location of the packages/contracts source tree (schemas, golden, fixtures).")
            + "from __future__ import annotations\n\nimport os\nfrom pathlib import Path\n\n\n"
            + "def contracts_root() -> Path:\n"
            + '    """packages/contracts of this checkout; AWR_CONTRACTS_DIR overrides."""\n'
            + '    env = os.environ.get("AWR_CONTRACTS_DIR")\n'
            + "    if env:\n        return Path(env)\n"
            + '    return Path(__file__).resolve().parents[3] / "packages" / "contracts"\n\n\n'
            + "def schema_path(rel: str) -> Path:\n    return contracts_root() / rel\n")


# ---------------------------------------------------------------- enums
def gen_enums(c: dict) -> str:
    E = c["enums"]
    out = [HDR.format(doc="Enumerations from packages/contracts/rt/enums.json (awr.enums.v1)."),
           "from __future__ import annotations\n\nfrom enum import IntEnum, IntFlag\n\n"]
    for name in E:
        if not name[0].isupper():
            continue
        if L.is_simple_enum(E, name):
            base = "IntFlag" if name in L.FLAG_ENUMS else "IntEnum"
            members = L.enum_members(E, name)
            out.append(f"\nclass {name}({base}):\n")
            for idn, v, _ in members:
                out.append(f"    {idn} = {v}\n")
            names = {v: w for _, v, w in members}
            out.append(f"\n\n{L.ident(name)}_NAMES: dict[int, str] = {pylit(names)}\n")
            out.append(f"{L.ident(name)}_BY_NAME: dict[str, int] = {pylit({w: v for v, w in names.items()})}\n\n")
    fs = [x for x in E["FlightState"]]
    sub = {k: v for k, v in E["FlightSub"].items()}
    out.append("\n# FlightSub: 3-bit sub-mode names per FlightState (None = reserved slot)\n")
    out.append("FLIGHT_SUB: dict[int, tuple[str | None, ...]] = {\n")
    for i, n in enumerate(fs):
        out.append(f"    {i}: {pylit(sub[n])},\n")
    out.append("}\n\n")
    out.append("SEVERITY: dict[int, int] = {" + ", ".join(f"FlightState.{k}: {v}" for k, v in E["Severity"].items()) + "}\n\n")
    out.append("JOB_STATE: dict[str, tuple[str, ...]] = {" + ", ".join(f"{json.dumps(k)}: {pylit(v)}" for k, v in E["JobState"].items()) + "}\n\n")
    out.append(
        "\ndef sub_name(fs: int, sub: int) -> str | None:\n"
        "    names = FLIGHT_SUB.get(fs, ())\n"
        "    return names[sub] if 0 <= sub < len(names) else None\n\n\n"
        "def sub_value(fs: int, name: str) -> int:\n"
        "    return FLIGHT_SUB[fs].index(name)\n\n\n"
        "def time_state(state_byte: int) -> TimeState:\n"
        '    """Low 4 bits of TIME.state / clock_state; bit7 (REPLAY) is masked (AWR-03 §5.2 rule 6)."""\n'
        "    return TimeState(state_byte & TimeFlags.STATE_MASK)\n\n\n"
        "def time_is_replay(state_byte: int) -> bool:\n"
        "    return bool(state_byte & TimeFlags.REPLAY)\n\n\n"
        "def time_advances(state_byte: int) -> bool:\n"
        '    """SimClockView advances only in PLAYING and LIVE; every other state freezes."""\n'
        "    return time_state(state_byte) in (TimeState.PLAYING, TimeState.LIVE)\n\n\n"
        "def red_highlight(fs: int, flags: int) -> bool:\n"
        '    """Swarm-wide red highlight: CORRECTING <= fs <= CRASHED and fs != LANDED, or ALERT (g04 §5.4)."""\n'
        "    return (FlightState.CORRECTING <= fs <= FlightState.CRASHED and fs != FlightState.LANDED) or bool(flags & FlightFlags.ALERT)\n"
    )
    return "".join(out)


# ---------------------------------------------------------------- layouts
def gen_layouts(c: dict) -> str:
    Ls = c["layouts"]["schemas"]
    out = [HDR.format(doc="Binary layouts from packages/contracts/rt/layouts.json: numpy dtypes, offsets, bit fields (AWR-17 §10.3, §10.4)."),
           "from __future__ import annotations\n\nimport numpy as np\n\n",
           f"LAYOUT_ID = 0x{c['layout_id']:08X}\n",
           "SCHEMA_HASH: dict[str, str] = {\n" + "".join(f'    "{k}": "{v}",\n' for k, v in c["schema_hash"].items()) + "}\n\n"]
    for sch in Ls:
        cn = L.const_name(sch["schemaName"])
        fields = sch["fields"]
        names = [f["n"] for f in fields]
        fmts = [(L.NP_FMT[f["t"]], f.get("c", 1)) for f in fields]
        fmt_lit = ", ".join(f'"{t}"' if cnt == 1 else f'("{t}", {cnt})' for t, cnt in fmts)
        out.append(f"# {sch['schemaName']} ({sch['size']} B): {sch.get('doc', '')}\n")
        out.append(f"{cn} = np.dtype({{\n    \"names\": {json.dumps(names)},\n"
                   f"    \"formats\": [{fmt_lit}],\n"
                   f"    \"offsets\": {json.dumps([f['o'] for f in fields])},\n"
                   f"    \"itemsize\": {sch['size']},\n}})\n")
        out.append(f"assert {cn}.itemsize == {sch['size']}\n")
        out.append(f"{cn}_OFFSETS: dict[str, int] = {pylit({f['n']: f['o'] for f in fields})}\n")
        scales = {f["n"]: f["scale"] for f in fields if "scale" in f}
        if scales:
            out.append(f"{cn}_SCALE: dict[str, float] = {pylit(scales)}\n")
        nones = {f["n"]: f["none"] for f in fields if "none" in f}
        if nones:
            out.append(f"{cn}_NONE: dict[str, int] = {pylit(nones)}\n")
        bits = {f["n"]: {k: tuple(v) for k, v in f["bits"].items()} for f in fields if "bits" in f}
        if bits:
            out.append(f"{cn}_BITS: dict[str, dict[str, tuple]] = {pylit(bits)}\n")
        consts = {f["n"]: f["const"] for f in fields if "const" in f}
        if consts:
            out.append(f"{cn}_CONST: dict[str, int] = {pylit(consts)}\n")
        out.append("\n")
    out.append("DTYPES: dict[str, np.dtype] = {\n" + "".join(f'    "{s["schemaName"]}": {L.const_name(s["schemaName"])},\n' for s in Ls) + "}\n")
    out.append("SIZES: dict[str, int] = {\n" + "".join(f'    "{s["schemaName"]}": {s["size"]},\n' for s in Ls) + "}\n")
    out.append(
        "\n\ndef pack_bits(spec: dict[str, tuple], **values: int) -> int:\n"
        '    """Pack named bit fields (spec from *_BITS[field]) into an integer."""\n'
        "    v = 0\n"
        "    for name, x in values.items():\n"
        "        start, width = spec[name][0], spec[name][1]\n"
        "        v |= (int(x) & ((1 << width) - 1)) << start\n"
        "    return v\n\n\n"
        "def unpack_bits(spec: dict[str, tuple], value: int) -> dict[str, int]:\n"
        "    return {name: (int(value) >> s[0]) & ((1 << s[1]) - 1) for name, s in spec.items()}\n\n\n"
        "def pack_fs(state: int, sub: int = 0) -> int:\n"
        '    """flight_state byte: bit0-4 FlightState, bit5-7 sub-mode."""\n'
        "    return (state & 0x1F) | ((sub & 7) << 5)\n\n\n"
        "def unpack_fs(b: int) -> tuple[int, int]:\n"
        "    return b & 0x1F, (b >> 5) & 7\n\n\n"
        "def pack_ctrl(owner: int, locked: bool, native: int, pose: int) -> int:\n"
        '    """ctrl byte: bit0-2 owner, bit3 locked, bit4-5 native, bit6-7 pose_src."""\n'
        "    return (owner & 7) | (int(locked) << 3) | ((native & 3) << 4) | ((pose & 3) << 6)\n\n\n"
        "def unpack_ctrl(b: int) -> tuple[int, bool, int, int]:\n"
        "    return b & 7, bool(b & 8), (b >> 4) & 3, (b >> 6) & 3\n\n\n"
        "def lite_from_full(full: np.ndarray, out: np.ndarray | None = None) -> np.ndarray:\n"
        '    """Quantise Full64 rows into Lite32 rows (q x32767, vel x100, both rounded and clamped to +-32767)."""\n'
        "    if out is None:\n        out = np.zeros(len(full), SWARM_LITE32)\n"
        "    out[\"agent_no\"] = full[\"agent_no\"]\n"
        "    out[\"flight_state\"] = full[\"flight_state\"]\n"
        "    out[\"battery_pct\"] = full[\"battery_pct\"]\n"
        "    out[\"pos\"] = full[\"pos\"]\n"
        "    out[\"q_snorm\"] = np.clip(np.rint(full[\"q\"].astype(np.float64) * 32767.0), -32767, 32767).astype(np.int16)\n"
        "    out[\"vel_cms\"] = np.clip(np.rint(full[\"vel\"].astype(np.float64) * 100.0), -32767, 32767).astype(np.int16)\n"
        "    out[\"flags\"] = full[\"flags\"]\n"
        "    out[\"ctrl\"] = full[\"ctrl\"]\n"
        "    return out\n"
    )
    return "".join(out)


# ---------------------------------------------------------------- frame (struct formats and codecs)
def gen_frame(c: dict) -> str:
    S = {s["schemaName"]: s for s in c["layouts"]["schemas"]}
    out = [HDR.format(doc="awr.rt.v1 frame codecs: struct formats, opcodes, flag bits, TIME and BATCH helpers (AWR-17 §6.4)."),
           "from __future__ import annotations\n\nimport struct\nfrom collections.abc import Iterator\nfrom typing import NamedTuple\n\n"
           "from .enums import TimeFlags, TimeState\n\n"]
    out.append("STRUCT_FORMATS: dict[str, str] = {\n" + "".join(f'    "{n}": "{L.struct_format(s)}",\n' for n, s in S.items()) + "}\n")
    out.append("STRUCTS: dict[str, struct.Struct] = {k: struct.Struct(v) for k, v in STRUCT_FORMATS.items()}\n\n")
    named = [("FRAME_HDR", "awr.rt.BatchHeader.v1"), ("REC_HDR", "awr.rt.RecordHeader.v1"), ("TIME", "awr.rt.Time.v1"),
             ("CLIENT_DATA_HDR", "awr.rt.ClientDataHeader.v1"), ("SETPOINT32", "awr.bus.Setpoint32.v1"), ("VEL_SETPOINT16", "awr.VelSetpoint16.v1"),
             ("REC_PREFIX8", "awr.rec.RecPrefix8.v1"), ("AWRT_HDR", "awr.fixture.AwrtHeader.v1"), ("AWRT_REC", "awr.fixture.AwrtRecord.v1"),
             ("BLOB_HDR", "awr.blob.Header.v1"), ("SWARM_BLOCK_HDR", "awr.SwarmLite32Block.v1"), ("AWRV_HDR", "awr.env.AwrvHeader.v1"),
             ("AWSL_HDR", "awr.env.AwslHeader.v1"), ("AWTR_HDR", "awr.recon.AwtrHeader.v1"), ("HEARTBEAT16", "awr.ipc.Heartbeat16.v1")]
    for n, sn in named:
        out.append(f'{n} = STRUCTS["{sn}"]\n')
    out.append('SETPOINT_BUS = struct.Struct("<HBBIq")  # header part of awr.bus.Setpoint32.v1 (M11 §6.3.9)\n')
    out.append('assert SETPOINT_BUS.size + VEL_SETPOINT16.size == SETPOINT32.size\n\n')
    bh = S["awr.rt.BatchHeader.v1"]["fields"]
    rh = S["awr.rt.RecordHeader.v1"]["fields"]
    cd = S["awr.rt.ClientDataHeader.v1"]["fields"]
    tm = S["awr.rt.Time.v1"]["fields"]
    def const_of(fields, n):
        return next(f["const"] for f in fields if f["n"] == n)
    out.append(f"OP_TIME = 0x{const_of(tm, 'op'):02X}\nOP_BATCH = 0x{const_of(bh, 'op'):02X}\nOP_CLIENT_DATA = 0x{const_of(cd, 'op'):02X}\n\n")
    for fields, prefix, fname in [(bh, "BATCH_", "flags"), (rh, "RF_", "rflags"), (cd, "CD_", "flags")]:
        f = next(x for x in fields if x["n"] == fname)
        for bn, spec in f["bits"].items():
            out.append(f"{prefix}{bn.upper()} = 0x{1 << spec[0]:02X}\n")
        out.append("\n")
    enc = c["enums"]["Encoding"]
    for i, e in enumerate(enc):
        out.append(f"ENC_{e.upper()} = {i}\n")
    out.append(
        "\nTIME_REPLAY_BIT = int(TimeFlags.REPLAY)\n\n\n"
        "def pad8(n: int) -> int:\n    return (n + 7) & ~7\n\n\n"
        "class TimeFrame(NamedTuple):\n"
        "    state: int\n    replay: bool\n    epoch: int\n    rate: float\n    t_sim_ns: int\n    t_srv_ns: int\n\n\n"
        "def encode_time(state: int, epoch: int, rate: float, t_sim_ns: int, t_srv_ns: int, replay: bool = False) -> bytes:\n"
        "    b = (int(state) & 0x0F) | (TIME_REPLAY_BIT if replay else 0)\n"
        "    return TIME.pack(OP_TIME, b, epoch & 0xFFFF, rate, t_sim_ns, t_srv_ns)\n\n\n"
        "def decode_time(buf: bytes | memoryview, off: int = 0) -> TimeFrame:\n"
        "    op, st, epoch, rate, t_sim, t_srv = TIME.unpack_from(buf, off)\n"
        "    if op != OP_TIME:\n        raise ValueError(f\"not a TIME frame: op=0x{op:02x}\")\n"
        "    return TimeFrame(st & 0x0F, bool(st & TIME_REPLAY_BIT), epoch, rate, t_sim, t_srv)\n\n\n"
        "def time_advances(frame: TimeFrame) -> bool:\n"
        "    return frame.state in (TimeState.PLAYING, TimeState.LIVE)\n\n\n"
        "class BatchHeader(NamedTuple):\n"
        "    flags: int\n    epoch: int\n    frame_seq: int\n    t_sim_ns: int\n\n\n"
        "class Record(NamedTuple):\n"
        "    channel_id: int\n    encoding: int\n    rflags: int\n    length: int\n    seq: int\n    dt_us: int\n    payload_off: int\n\n\n"
        "def decode_batch_header(buf: bytes | memoryview) -> BatchHeader:\n"
        "    op, flags, epoch, frame_seq, t_sim = FRAME_HDR.unpack_from(buf, 0)\n"
        "    if op != OP_BATCH:\n        raise ValueError(f\"not a BATCH frame: op=0x{op:02x}\")\n"
        "    return BatchHeader(flags, epoch, frame_seq, t_sim)\n\n\n"
        "def iter_records(buf: bytes | memoryview, off: int = 16) -> Iterator[Record]:\n"
        '    """Walk BATCH records; unknown encodings are yielded too (callers skip them). Raises on truncation."""\n'
        "    n = len(buf)\n"
        "    while off < n:\n"
        "        if off + REC_HDR.size > n:\n            raise ValueError(\"truncated record header\")\n"
        "        ch, enc, rf, length, seq, dt = REC_HDR.unpack_from(buf, off)\n"
        "        p = off + REC_HDR.size\n"
        "        if p + length > n:\n            raise ValueError(\"truncated record payload\")\n"
        "        yield Record(ch, enc, rf, length, seq, dt, p)\n"
        "        off = p + pad8(length)\n\n\n"
        "def encode_record(channel_id: int, encoding: int, rflags: int, seq: int, dt_us: int, payload: bytes) -> bytes:\n"
        "    n = len(payload)\n"
        "    return REC_HDR.pack(channel_id, encoding, rflags, n, seq & 0xFFFFFFFF, dt_us) + payload + b\"\\0\" * (pad8(n) - n)\n\n\n"
        "def encode_batch(flags: int, epoch: int, frame_seq: int, t_sim_ns: int, records: list[bytes]) -> bytes:\n"
        "    return FRAME_HDR.pack(OP_BATCH, flags, epoch & 0xFFFF, frame_seq & 0xFFFFFFFF, t_sim_ns) + b\"\".join(records)\n"
    )
    awrt = S["awr.fixture.AwrtHeader.v1"]["fields"]
    out.append(
        "\n\n# ---------------------------------------------------------------- .awrrt protocol fixtures (AWR-16 §13.9)\n"
        f"AWRT_MAGIC = {const_of(awrt, 'magic')}\nAWRT_VERSION = {const_of(awrt, 'version')}\nAWRT_TIMED = 0x01\n"
        "AWRT_S2C, AWRT_C2S = 0, 1\nAWRT_TEXT, AWRT_BINARY = 0, 1\n\n\n"
        "class AwrtRecord(NamedTuple):\n"
        "    dir: int\n    kind: int\n    t_rel_ns: int\n    payload: bytes\n\n\n"
        "class Awrrt(NamedTuple):\n"
        "    flags: int\n    t0_wall_ns: int\n    header: dict\n    records: list[AwrtRecord]\n\n\n"
        "def write_awrrt(header: dict, records: list[AwrtRecord], flags: int = AWRT_TIMED, t0_wall_ns: int = 0) -> bytes:\n"
        '    """Header JSON is written with sorted keys and no whitespace so fixtures are byte-reproducible."""\n'
        "    import json\n\n"
        "    hj = json.dumps(header, sort_keys=True, separators=(\",\", \":\"), ensure_ascii=False).encode()\n"
        "    parts = [AWRT_HDR.pack(AWRT_MAGIC, AWRT_VERSION, flags, len(hj), 0, t0_wall_ns), hj, b\"\\0\" * (pad8(len(hj)) - len(hj))]\n"
        "    last = -1\n"
        "    for r in records:\n"
        "        if r.t_rel_ns < last:\n            raise ValueError(\"t_rel_ns must be monotonic\")\n"
        "        last = r.t_rel_ns\n"
        "        n = len(r.payload)\n"
        "        parts += [AWRT_REC.pack(r.dir, r.kind, 0, n, r.t_rel_ns), bytes(r.payload), b\"\\0\" * (pad8(n) - n)]\n"
        "    return b\"\".join(parts)\n\n\n"
        "def read_awrrt(buf: bytes | memoryview) -> Awrrt:\n"
        "    import json\n\n"
        "    magic, version, flags, hlen, _res, t0 = AWRT_HDR.unpack_from(buf, 0)\n"
        "    if magic != AWRT_MAGIC or version != AWRT_VERSION:\n"
        "        raise ValueError(f\"not an .awrrt v1 file: magic=0x{magic:08x} version={version}\")\n"
        "    off = AWRT_HDR.size\n"
        "    header = json.loads(bytes(buf[off:off + hlen]).decode(\"utf-8\"))\n"
        "    off += pad8(hlen)\n"
        "    recs: list[AwrtRecord] = []\n"
        "    n = len(buf)\n"
        "    while off < n:\n"
        "        if off + AWRT_REC.size > n:\n            raise ValueError(\"truncated .awrrt record header\")\n"
        "        d, k, _r, length, t_rel = AWRT_REC.unpack_from(buf, off)\n"
        "        p = off + AWRT_REC.size\n"
        "        if p + length > n:\n            raise ValueError(\"truncated .awrrt record payload\")\n"
        "        recs.append(AwrtRecord(d, k, t_rel, bytes(buf[p:p + length])))\n"
        "        off = p + pad8(length)\n"
        "    return Awrrt(flags, t0, header, recs)\n"
    )
    return "".join(out)


# ---------------------------------------------------------------- reasons
def gen_reasons(c: dict) -> str:
    R = c["reasons"]
    out = [HDR.format(doc="Reason codes from packages/contracts/rt/reasons.json (AWR-17 §8)."),
           "from __future__ import annotations\n\nfrom enum import IntEnum\nfrom typing import NamedTuple\n\n\n",
           "class Reason(IntEnum):\n"]
    out.extend(f"    {r['name']} = {r['code']}\n" for r in R["reasons"])
    out.append("\n\nclass ReasonInfo(NamedTuple):\n    code: int\n    name: str\n    http: int | None\n    category: str\n"
               "    step: str | None\n    message_zh: str\n    remedy_zh: str\n    d1: str\n\n\n")
    out.append("REASONS: dict[int, ReasonInfo] = {\n")
    out.extend(f"    {r['code']}: ReasonInfo({r['code']}, {pylit(r['name'])}, {pylit(r['http'])}, {pylit(r['category'])}, "
                   f"{pylit(r['step'])}, {pylit(r['message_zh'])}, {pylit(r['remedy_zh'])}, {pylit(r['d1'])}),\n" for r in R["reasons"])
    out.append("}\n\n")
    out.append("DETAIL_ONLY: frozenset[str] = frozenset(" + pylit(R["detail_only"]) + ")\n")
    out.append("WARNINGS: frozenset[str] = frozenset(" + pylit(R["warnings"]) + ")\n")
    out.append("WS_CLOSE: dict[str, int] = {" + ", ".join(f"{json.dumps(w['name'])}: {w['code']}" for w in R["ws_close_codes"]) + "}\n\n\n")
    out.append("def info(code: int) -> ReasonInfo:\n    return REASONS[int(code)]\n\n\n"
               "def http_status(code: int) -> int:\n"
               '    """HTTP status for a REST problem+json response; codes without a mapping use 409."""\n'
               "    h = REASONS[int(code)].http\n    return 409 if h is None else h\n")
    return "".join(out)


# ---------------------------------------------------------------- commands
def gen_commands(c: dict) -> str:
    C = c["commands"]
    cols = C["admission_columns"]
    out = [HDR.format(doc="Command services, argument schemas and the admission matrix from packages/contracts/rt/commands.json (AWR-17 §7.1; AWR-12 §5.2)."),
           "from __future__ import annotations\n\nimport re\nfrom typing import Any, NamedTuple\n\nfrom .enums import FlightFlags, FlightState\n\n"]
    out.append("ADMISSION_COLUMNS: tuple[str, ...] = " + pylit([x["id"] for x in cols]) + "\n")
    out.append("ADMISSION_SYMBOL_CODE: dict[str, int] = " + pylit({k: v["code"] for k, v in C["admission_symbols"].items()}) + "\n")
    out.append("ADMISSION_CONDITION_ELSE: dict[str, str] = " + pylit({k: v["else"] for k, v in C["admission_conditions"].items()}) + "\n\n")
    out.append("\nclass Service(NamedTuple):\n    name: str\n    op: str\n    pattern: re.Pattern[str]\n    category: str\n    lease: bool | str | None\n"
               "    agent: str\n    d1: str\n    batchable: bool\n    aliases: tuple[str, ...]\n    args_schema: dict[str, Any]\n"
               "    admission: tuple[str, ...] | None\n    admission_cond: dict[str, str]\n\n\n")
    out.append("def _pattern(name: str) -> re.Pattern[str]:\n"
               '    return re.compile("^" + re.sub(r"\\\\\\{(\\w+)\\\\\\}", lambda m: f"(?P<{m.group(1)}>[a-z0-9][a-z0-9_-]*)", re.escape(name)) + "$")\n\n\n')
    out.append("SERVICES: tuple[Service, ...] = (\n")
    for s in C["services"]:
        adm = pylit([s["admission"][cid["id"]] for cid in cols]) if "admission" in s else "None"
        out.append(f"    Service({pylit(s['name'])}, {pylit(s['op'])}, _pattern({pylit(s['name'])}), {pylit(s['category'])}, {pylit(s['lease'])}, "
                   f"{pylit(s['agent'])}, {pylit(s['d1'])}, {pylit(s.get('batchable', False))}, {pylit(s.get('aliases', []))},\n"
                   f"            {jsonlit(s['args_schema'])},\n            {adm}, {pylit(s.get('admission_cond', {}))}),\n")
    out.append(")\n\nSERVICE_BY_OP: dict[str, Service] = {s.op: s for s in SERVICES}\n")
    out.append("_ALIAS: list[tuple[re.Pattern[str], Service]] = [(_pattern(a), s) for s in SERVICES for a in s.aliases]\n\n\n")
    out.append("def match_service(name: str) -> tuple[Service, dict[str, str]] | None:\n"
               '    """Resolve a WS service name (uav/{id}/cmd/goto, fleet/cmd/rtl, sim/play ...) to its Service and path parameters."""\n'
               "    for s in SERVICES:\n"
               "        m = s.pattern.match(name)\n"
               "        if m:\n            return s, m.groupdict()\n"
               "    for p, s in _ALIAS:\n"
               "        m = p.match(name)\n"
               "        if m:\n            return s, m.groupdict()\n"
               "    return None\n\n\n")
    out.append("def admission_column(fs: int, flags: int) -> int:\n"
               '    """Column index of the admission matrix: RTL and LANDING split by flags.FAILSAFE (operator vs automatic)."""\n'
               "    auto = bool(flags & FlightFlags.FAILSAFE)\n"
               "    order = [FlightState.UNKNOWN, FlightState.DISARMED, FlightState.PREFLIGHT, FlightState.READY, FlightState.TAKING_OFF,\n"
               "             FlightState.FLYING, FlightState.CORRECTING, FlightState.HOLD]\n"
               "    if fs in order:\n        return order.index(fs)\n"
               "    if fs == FlightState.RTL:\n        return 9 if auto else 8\n"
               "    if fs == FlightState.LANDING:\n        return 11 if auto else 10\n"
               "    return {FlightState.ELAND: 12, FlightState.FAILSAFE: 13, FlightState.LANDED: 14, FlightState.CRASHED: 15}[FlightState(fs)]\n\n\n"
               "def admit_symbol(op: str, fs: int, flags: int) -> tuple[str, str | None]:\n"
               '    """(symbol, condition id) for a vehicle command; symbol Y, =, S, - (AWR-12 §5.2). Conditions are applied by the caller."""\n'
               "    s = SERVICE_BY_OP[op]\n"
               "    if s.admission is None:\n        raise KeyError(f\"{op} has no admission row\")\n"
               "    col = admission_column(fs, flags)\n"
               "    return s.admission[col], s.admission_cond.get(ADMISSION_COLUMNS[col])\n")
    return "".join(out)


# ---------------------------------------------------------------- topics, units, bus keys, rng, safety codes
def gen_topics(c: dict) -> str:
    T = c["topics"]
    out = [HDR.format(doc="Topic table from packages/contracts/rt/topics.json (AWR-17 §6.6)."),
           "from __future__ import annotations\n\nimport re\nfrom typing import NamedTuple\n\n",
           f"RATE_CLASSES: tuple[int, ...] = {pylit(T['rate_classes'])}\nTICK_HZ = {T['tick_hz']}\nCHUNK_RE = re.compile({pylit(T['chunk_pattern'])})\n\n\n",
           "class Topic(NamedTuple):\n    pattern: str\n    kind: str\n    encoding: str\n    schema_name: str\n    native_hz: float\n"
           "    default_rate: dict[str, int] | None\n    mode: str | None\n    priority: int | None\n    self_contained: bool\n    owner: str\n    d1: str\n"
           "    aliases: tuple[str, ...]\n    regex: re.Pattern[str]\n\n\n",
           "def _rx(p: str) -> re.Pattern[str]:\n"
           '    return re.compile("^" + re.sub(r"\\\\\\{\\w+\\\\\\}", "[a-z0-9][a-z0-9_-]*", re.escape(p)) + "$")\n\n\n',
           "TOPICS: tuple[Topic, ...] = (\n"]
    out.extend(f"    Topic({pylit(t['pattern'])}, {pylit(t['kind'])}, {pylit(t['encoding'])}, {pylit(t['schemaName'])}, {pylit(t['native_hz'])}, "
                   f"{pylit(t['default_rate'])}, {pylit(t['mode'])}, {pylit(t['priority'])}, {pylit(t['self_contained'])}, {pylit(t['owner'])}, "
                   f"{pylit(t['d1'])}, {pylit(t.get('aliases', []))}, _rx({pylit(t['pattern'])})),\n" for t in T["topics"])
    out.append(")\n\n\n")
    out.append("def match_topic(topic: str) -> Topic | None:\n"
               "    for t in TOPICS:\n"
               "        if t.regex.match(topic) or topic in t.aliases:\n            return t\n"
               "    return None\n\n\n"
               "def quantize_rate(rate: float) -> int:\n"
               '    """Round a requested rate up to the nearest rate class; 0 means native rate capped by the tick (AWR-17 §6.7)."""\n'
               "    if rate <= 0:\n        return TICK_HZ\n"
               "    for r in RATE_CLASSES:\n"
               "        if r >= rate:\n            return r\n"
               "    return RATE_CLASSES[-1]\n\n\n"
               "def valid_topic(topic: str, allow_wildcards: bool = False) -> bool:\n"
               '    """zenoh key-expr subset: chunks [a-z0-9][a-z0-9_-]*; * and ** only in subscriptions."""\n'
               '    parts = topic.split("/")\n'
               '    return bool(parts) and all(CHUNK_RE.match(p) or (allow_wildcards and p in ("*", "**")) for p in parts)\n')
    return "".join(out)


def gen_units(c: dict) -> str:
    U = c["units"]
    return (HDR.format(doc="Unit suffix dictionary from packages/contracts/rt/units.json (AWR-03 §5.4).")
            + "from __future__ import annotations\n\n"
            + "SUFFIXES: dict[str, tuple[str, str]] = {\n" + "".join(f"    {json.dumps(k)}: ({json.dumps(v['unit'])}, {json.dumps(v['quantity'])}),\n" for k, v in U["suffixes"].items()) + "}\n"
            + f"DENIED_SUFFIXES: dict[str, str] = {pylit(U.get('denied_suffixes', {}))}\n"
            + f"DENIED_NAMES: dict[str, str] = {pylit(U.get('denied_names', {}))}\n"
            + f"UNIT_LIKE_TOKENS: frozenset[str] = frozenset({pylit(U.get('unit_like_tokens', []))})\n"
            + "EXCEPTIONS: dict[str, str] = {" + ", ".join(f"{json.dumps(e['field'])}: {json.dumps(e['unit'])}" for e in U["exceptions"]) + "}\n")


def gen_bus_keys(c: dict) -> str:
    K = c["keys"]
    out = [HDR.format(doc="Zenoh key space from packages/contracts/bus/keys.json (AWR-17 §9.3). Key literals are allowed only in this module."),
           "from __future__ import annotations\n\nimport re\n\n",
           f"NAMESPACE_FMT = {pylit(K['namespace'])}\nCHUNK_RE = re.compile({pylit(K['chunk_pattern'])})\n",
           f"EVENT_CATEGORIES: tuple[str, ...] = {pylit(K['event_categories'])}\n",
           f"PRODUCERS: tuple[str, ...] = {pylit(K['producers'])}\n\n\n",
           "def _chunk(x: str) -> str:\n"
           "    if not CHUNK_RE.match(x):\n        raise ValueError(f\"invalid key chunk: {x!r}\")\n"
           "    return x\n\n\n",
           "def namespace(world: str, run: str) -> str:\n"
           '    return NAMESPACE_FMT.format(world=_chunk(world), run=_chunk(run))\n\n\n']
    for k in K["keys"]:
        params = re.findall(r"\{(\w+)\}", k["key"])
        fn = k["name"].lower()
        if params:
            sig = ", ".join(f"{p}: str" for p in params)
            body = "f" + json.dumps(re.sub(r"\{(\w+)\}", lambda m: "{_chunk(" + m.group(1) + ")}", k["key"]))
            out.append(f"def {fn}({sig}) -> str:\n    return {body}\n\n\n")
        else:
            out.append(f"{k['name']} = {json.dumps(k['key'])}\n\n\n")
    return "".join(out).rstrip() + "\n"


def gen_rng(c: dict) -> str:
    R = c["rng"]["streams"]
    out = [HDR.format(doc="RNG stream registry from packages/contracts/rt/rng_streams.json (AWR-17 §10.8; ADR-049)."),
           "from __future__ import annotations\n\nfrom enum import IntEnum\n\nimport numpy as np\n\n\nclass Stream(IntEnum):\n"]
    out.extend(f"    {s['name'].upper()} = {s['stream_id']}\n" for s in R)
    out.append("\n\ndef rng(world_seed: int, stream: int, *keys: int) -> np.random.Generator:\n"
               '    """PCG64(SeedSequence([world_seed, stream_id, *keys])); keys derive keyed child sequences (stream 5)."""\n'
               "    return np.random.Generator(np.random.PCG64(np.random.SeedSequence([int(world_seed), int(stream), *map(int, keys)])))\n")
    return "".join(out)


def gen_safety(c: dict) -> str:
    out = [HDR.format(doc="SafetyEvent catalogue from packages/contracts/rt/safety_codes.json (M09 §6.13)."),
           "from __future__ import annotations\n\nfrom typing import NamedTuple\n\n\n",
           "class SafetyCode(NamedTuple):\n    code: str\n    type: str\n    cls: str\n    level: int\n    fsm: str | None\n    ui: str\n    icon: str\n    merge_key: str | None\n    d1: str\n\n\n",
           "SAFETY_CODES: dict[str, SafetyCode] = {\n"]
    out.extend(f"    {json.dumps(s['code'])}: SafetyCode({json.dumps(s['code'])}, {json.dumps(s['type'])}, {json.dumps(s['cls'])}, {s['level']}, "
                   f"{pylit(s['fsm'])}, {json.dumps(s['ui'])}, {json.dumps(s['icon'])}, {pylit(s['merge_key'])}, {json.dumps(s['d1'])}),\n"
               for s in c["safety"]["codes"])
    out.append("}\n")
    return "".join(out)


def gen_presets(c: dict) -> str:
    text = c["presets_text"]
    P = json.loads(text)
    out = [HDR.format(doc="Environment presets: verbatim bytes of packages/contracts/env/presets.json, sha256 and EnvScalars indices (M07 §6.2.1)."),
           "from __future__ import annotations\n\nimport hashlib\nimport json\nfrom typing import Any\n\n",
           f"PRESETS_TEXT = {text!r}\n",
           "PRESETS_JSON: bytes = PRESETS_TEXT.encode(\"utf-8\")\n",
           f"PRESETS_SHA256 = \"{L.hashlib.sha256(text.encode('utf-8')).hexdigest()}\"\n",
           "assert hashlib.sha256(PRESETS_JSON).hexdigest() == PRESETS_SHA256\n",
           "PRESETS: dict[str, Any] = json.loads(PRESETS_TEXT)\n\n"]
    for i, f in enumerate(P["fields"]):
        out.append(f"F_{f['path'].replace('.', '_').upper()} = {i}\n")
    out.append(f"\nNF = {len(P['fields'])}\n")
    out.append("FIELD_PATHS: tuple[str, ...] = " + pylit([f["path"] for f in P["fields"]]) + "\n")
    out.append("PRESET_IDS: tuple[str, ...] = " + pylit([p["id"] for p in P["presets"]]) + "\n")
    return "".join(out)


# ---------------------------------------------------------------- schema TypedDicts
def _union(parts: list[str]) -> str:
    flat: list[str] = []
    for p in parts:
        for q in p.split(" | "):
            if q not in flat:
                flat.append(q)
    flat.sort(key=lambda q: q == "None")
    return " | ".join(flat) if flat else "Any"


class TypeGen:
    """JSON Schema (all files under packages/contracts) -> TypedDict definitions and type aliases."""

    def __init__(self):
        self.docs: dict[str, tuple[Path, dict]] = {}
        for p in L.schema_files():
            d = json.loads(p.read_text(encoding="utf-8"))
            self.docs[d["$id"]] = (p, d)
        self.names: dict[tuple[str, str], str] = {}
        used: set[str] = set()
        for sid, (p, _d) in sorted(self.docs.items()):
            dom = sid.split("/")[3]
            stem = p.name[: -len(".schema.json")]
            base = self._pascal(stem)
            if base in used or base in {"Command", "Event", "Detail", "Common"}:
                base = self._pascal(dom) + base
            used.add(base)
            self.names[(sid, "")] = base
        self.blocks: dict[str, str] = {}
        self.kinds: dict[str, str] = {}
        self.deps: dict[str, set[str]] = {}

    @staticmethod
    def _pascal(s: str) -> str:
        return "".join(w[:1].upper() + w[1:] for w in re.split(r"[-_./@ $]+", s) if w)

    def ref_target(self, sid: str, ref: str) -> tuple[str, str]:
        if ref.startswith("#"):
            return sid, ref[1:]
        base, _, frag = ref.partition("#")
        parts = sid.rsplit("/", 1)[0].split("/")
        for seg in base.split("/"):
            if seg == "..":
                parts.pop()
            elif seg and seg != ".":
                parts.append(seg)
        return "/".join(parts), frag

    def node(self, sid: str, ptr: str):
        d = self.docs[sid][1]
        for seg in [s for s in ptr.split("/") if s]:
            d = d[int(seg)] if isinstance(d, list) else d[seg.replace("~1", "/").replace("~0", "~")]
        return d

    def name_for(self, sid: str, ptr: str) -> str:
        key = (sid, ptr)
        if key not in self.names:
            base = self.names[(sid, "")]
            tail = [s for s in ptr.split("/") if s and s not in ("$defs", "properties", "items", "definitions", "additionalProperties")]
            name = base + "".join(self._pascal(t) for t in tail if not t.isdigit()) + "".join(t for t in tail if t.isdigit())
            while name in self.names.values():
                name += "_"
            self.names[key] = name
        return self.names[key]

    def annot(self, sid: str, ptr: str, s) -> str:
        if s is True or s == {} or not isinstance(s, dict):
            return "Any"
        if "$ref" in s:
            tsid, tptr = self.ref_target(sid, s["$ref"])
            return self.named(tsid, tptr)
        if "const" in s:
            return f"Literal[{pylit(s['const'])}]" if not isinstance(s["const"], (list, dict)) else "Any"
        if "enum" in s:
            vals = [v for v in s["enum"] if not isinstance(v, (list, dict))]
            lits = [pylit(v) for v in vals if v is not None]
            a = f"Literal[{', '.join(lits)}]" if lits else "None"
            return a + (" | None" if None in s["enum"] and lits else "")
        for comb in ("oneOf", "anyOf"):
            if comb in s and not s.get("properties"):
                parts: list[str] = []
                for i, sub in enumerate(s[comb]):
                    a = self.annot(sid, f"{ptr}/{comb}/{i}", sub)
                    if a not in parts:
                        parts.append(a)
                return _union(parts)
        t = s.get("type")
        if isinstance(t, list):
            parts = []
            for tt in t:
                a = self.annot(sid, ptr, {**s, "type": tt})
                if a not in parts:
                    parts.append(a)
            return _union(parts)
        if t == "string":
            return "str"
        if t == "integer":
            return "int"
        if t == "number":
            return "float"
        if t == "boolean":
            return "bool"
        if t == "null":
            return "None"
        if t == "array":
            it = s.get("items")
            return f"list[{self.annot(sid, ptr + '/items', it)}]" if isinstance(it, dict) else "list[Any]"
        if t == "object" or "properties" in s:
            if s.get("properties"):
                return self.named(sid, ptr)
            ap = s.get("additionalProperties")
            if isinstance(ap, dict):
                return f"dict[str, {self.annot(sid, ptr + '/additionalProperties', ap)}]"
            return "dict[str, Any]"
        return "Any"

    def named(self, sid: str, ptr: str) -> str:
        """Emit (once) a TypedDict for object schemas or a type alias for other named definitions; return its name."""
        name = self.name_for(sid, ptr)
        if name in self.kinds:
            return name
        s = self.node(sid, ptr)
        self.kinds[name] = "pending"  # recursion guard
        src = f"# {self.docs[sid][0].relative_to(L.CONTRACTS)}#{ptr}"
        doc = (s.get("title") or "").replace("\n", " ") if isinstance(s, dict) else ""
        head = f"{src}{(' ' + doc[:100]) if doc else ''}\n"
        if isinstance(s, dict) and s.get("properties"):
            req = set(s.get("required", []))
            items = [(k, self.annot(sid, f"{ptr}/properties/{k}", sub), k in req) for k, sub in s["properties"].items()]
            if all(k.isidentifier() and not keyword.iskeyword(k) for k, _, _ in items):
                body = "".join(f"    {k}: {a if r else f'NotRequired[{a}]'}\n" for k, a, r in items)
                self.kinds[name] = "class"
                self.blocks[name] = f"{head}class {name}(TypedDict):\n{body}"
            else:
                body = "".join(f"    {json.dumps(k)}: {a if r else f'NotRequired[{a}]'},\n" for k, a, r in items)
                self.kinds[name] = "functional"
                self.deps[name] = set(re.findall(r"\b[A-Z][A-Za-z0-9_]*\b", "".join(a for _, a, _ in items)))
                self.blocks[name] = f"{head}{name} = TypedDict(\"{name}\", {{\n{body}}})\n"
        else:
            self.kinds[name] = "alias"
            self.blocks[name] = f"{head}type {name} = {self.annot(sid, ptr, s) if isinstance(s, dict) else 'Any'}\n"
        return name

    def run(self) -> str:
        for sid in sorted(self.docs):
            d = self.docs[sid][1]
            self.named(sid, "")
            for k in d.get("$defs", {}):
                self.named(sid, f"/$defs/{k}")
        aliases = sorted(n for n, k in self.kinds.items() if k == "alias")
        classes = sorted(n for n, k in self.kinds.items() if k == "class")
        funcs = sorted(n for n, k in self.kinds.items() if k == "functional")
        ordered: list[str] = []
        seen: set[str] = set()

        def visit(n: str, stack: tuple[str, ...] = ()) -> None:
            if n in seen or n in stack:
                return
            for d in sorted(self.deps.get(n, ())):
                if self.kinds.get(d) == "functional":
                    visit(d, (*stack, n))
            seen.add(n)
            ordered.append(n)

        for n in funcs:
            visit(n)
        body = "\n\n".join(self.blocks[n] for n in [*aliases, *classes, *ordered])
        imports = ["Any", "Literal", "NotRequired", "TypedDict"]
        imports = [i for i in imports if re.search(rf"\b{i}\b", body)]
        allnames = sorted(self.blocks)
        head = (HDR.format(doc="TypedDict definitions and type aliases for every JSON Schema under packages/contracts (keys as on the wire).")
                + "from __future__ import annotations\n\n"
                + f"from typing import {', '.join(imports)}\n\n"
                + "__all__ = [\n" + "".join(f"    \"{n}\",\n" for n in allnames) + "]\n\n")
        return head + body


def build(c: dict) -> dict[Path, str]:
    P = L.PY_OUT
    files = {
        P / "__init__.py": gen_init(c),
        P / "_paths.py": gen_paths(),
        P / "enums.py": gen_enums(c),
        P / "layouts.py": gen_layouts(c),
        P / "frame.py": gen_frame(c),
        P / "reasons.py": gen_reasons(c),
        P / "commands.py": gen_commands(c),
        P / "topics.py": gen_topics(c),
        P / "units.py": gen_units(c),
        P / "bus_keys.py": gen_bus_keys(c),
        P / "rng_streams.py": gen_rng(c),
        P / "safety_codes.py": gen_safety(c),
        P / "presets.py": gen_presets(c),
        P / "schema_types.py": TypeGen().run(),
    }
    return files


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="compare with committed output, do not write")
    args = ap.parse_args(argv)
    try:
        c = L.load_all()
        files = build(c)
    except L.ContractError as e:
        print(f"contract error: {e}", file=sys.stderr)
        return 2
    diffs = L.write_or_check(files, args.check, L.PY_OUT)
    if args.check and diffs:
        print(f"gen.py --check: {diffs} file(s) differ; run python tools/contracts/gen.py", file=sys.stderr)
        return 1
    print(f"gen.py: {'up to date' if not diffs else f'{diffs} file(s) updated'} (layout_id 0x{c['layout_id']:08X}, contracts {c['version']})")
    return 0


if __name__ == "__main__":
    sys.exit(main())

