#!/usr/bin/env node
// TypeScript code generator: packages/contracts -> packages/contracts/gen/ts (AWR-17 §10.4; AWR-03 §5.10).
//
// Usage:
//   node tools/contracts/gen.mjs            regenerate
//   node tools/contracts/gen.mjs --check    exit 1 when the committed output differs
//
// Output (npm package @awr/contracts): index, layouts, frame, time, enums, reasons, commands, topics,
// units, presets, safetyCodes, types (json-schema-to-typescript 16 over one bundled schema).
// Hot-path accessors take out parameters and allocate nothing per call.

import { createHash } from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(HERE, '..', '..')
const CONTRACTS = path.join(ROOT, 'packages', 'contracts')
const OUT = path.join(CONTRACTS, 'gen', 'ts')
const BANNER = '// Generated by tools/contracts/gen.mjs from packages/contracts. Do not edit.\n'

const TYPE_SIZE = { u8: 1, i8: 1, u16: 2, i16: 2, u32: 4, i32: 4, u64: 8, i64: 8, f32: 4, f64: 8 }
const INT_TYPES = new Set(['u8', 'i8', 'u16', 'i16', 'u32', 'i32', 'u64', 'i64'])
const DV_GET = { u8: 'getUint8', i8: 'getInt8', u16: 'getUint16', i16: 'getInt16', u32: 'getUint32', i32: 'getInt32', f32: 'getFloat32', f64: 'getFloat64' }
const DV_SET = { u8: 'setUint8', i8: 'setInt8', u16: 'setUint16', i16: 'setInt16', u32: 'setUint32', i32: 'setInt32', f32: 'setFloat32', f64: 'setFloat64' }
const SHORT = {
  'awr.DroneState64.v1': 'DS64',
  'awr.SwarmLite32.v1': 'SL32',
  'awr.EnvSample32.v1': 'ES32',
  'awr.VelSetpoint16.v1': 'VS16',
  'awr.SensorPose48.v1': 'SP48',
}
const FLAG_ENUMS = new Set(['FlightFlags', 'EnvFlags', 'TimeFlags', 'EnvFields'])

const readJson = (rel) => JSON.parse(fs.readFileSync(path.join(CONTRACTS, rel), 'utf8'))

// ---------------------------------------------------------------- canonical JSON and hashes (identical to contracts_lib.py)
function canonical(v) {
  if (v === null || typeof v !== 'object') return JSON.stringify(v)
  if (Array.isArray(v)) return '[' + v.map(canonical).join(',') + ']'
  return '{' + Object.keys(v).sort().map((k) => JSON.stringify(k) + ':' + canonical(v[k])).join(',') + '}'
}
const sha256 = (s) => createHash('sha256').update(Buffer.from(s, 'utf8')).digest()
const layoutId = (layouts) => sha256(canonical(layouts)).readUInt32LE(0)
const schemaHash = (s) => sha256(canonical(s)).toString('hex').slice(0, 8)

// ---------------------------------------------------------------- layouts.json rules (AWR-17 §10.3)
function checkLayouts(layouts, enums) {
  const errs = []
  const seen = new Set()
  for (const s of layouts.schemas) {
    if (seen.has(s.schemaName)) errs.push(`${s.schemaName}: duplicate`)
    seen.add(s.schemaName)
    if (s.size % 8) errs.push(`${s.schemaName}: size not a multiple of 8`)
    const used = new Uint8Array(s.size)
    for (const f of s.fields) {
      const sz = TYPE_SIZE[f.t]
      const c = f.c ?? 1
      if (f.o % sz) errs.push(`${s.schemaName}.${f.n}: misaligned`)
      if (f.o + sz * c > s.size) errs.push(`${s.schemaName}.${f.n}: beyond size`)
      for (let b = f.o; b < Math.min(f.o + sz * c, s.size); b++) {
        if (used[b]) { errs.push(`${s.schemaName}.${f.n}: overlap`); break }
        used[b] = 1
      }
      if (f.scale !== undefined && !INT_TYPES.has(f.t)) errs.push(`${s.schemaName}.${f.n}: scale on non-integer`)
      if (f.enum && !(f.enum in enums)) errs.push(`${s.schemaName}.${f.n}: unknown enum`)
      for (const [bn, spec] of Object.entries(f.bits ?? {})) {
        if (spec[0] + spec[1] > sz * 8) errs.push(`${s.schemaName}.${f.n}.${bn}: bits exceed integer`)
        if (spec.length > 2 && !(spec[2] in enums)) errs.push(`${s.schemaName}.${f.n}.${bn}: unknown enum`)
      }
    }
  }
  return errs
}

// ---------------------------------------------------------------- naming
const pascal = (sn) => sn.split('.').slice(1, -1).map((p) => p[0].toUpperCase() + p.slice(1)).join('')
function constName(sn) {
  return sn.split('.').slice(1, -1)
    .map((p) => p.replace(/([a-z])([A-Z])/g, '$1_$2').replace(/([A-Z])([A-Z][a-z])/g, '$1_$2').toUpperCase())
    .join('_')
}
const ident = (name) => {
  let s = name.replace(/[^A-Za-z0-9]+/g, '_').replace(/^_+|_+$/g, '').toUpperCase()
  if (!s || /^[0-9]/.test(s)) s = 'V_' + s
  return s
}
const upperSnake = (name) => name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase()
const lit = (v) => JSON.stringify(v)

function isSimpleEnum(e) {
  if (Array.isArray(e)) return true
  if (!e || typeof e !== 'object') return false
  const v = Object.values(e)
  return v.every((x) => Number.isInteger(x)) && new Set(v).size === v.length
}
function enumMembers(e) {
  if (Array.isArray(e)) return e.map((v, i) => (v === null ? null : [ident(v), i, v])).filter(Boolean)
  return Object.entries(e).map(([k, v]) => [ident(k), v, k])
}

// ---------------------------------------------------------------- layouts.ts
function genLayouts(c) {
  const out = [BANNER, '// Binary layouts from packages/contracts/rt/layouts.json (AWR-17 §10.3, §10.4). Little endian.\n\n']
  out.push(`export const CONTRACTS_VERSION = ${lit(c.version)}\n`)
  out.push(`export const LAYOUT_ID = 0x${c.layoutId.toString(16).toUpperCase().padStart(8, '0')}\n`)
  out.push('export const SCHEMA_HASH: Readonly<Record<string, string>> = {\n')
  for (const [k, v] of Object.entries(c.schemaHash)) out.push(`  ${lit(k)}: ${lit(v)},\n`)
  out.push('}\n')
  out.push('/** Record size in bytes per schemaName (same as Python layouts.SIZES). */\n')
  out.push('export const SIZES: Readonly<Record<string, number>> = {\n')
  for (const s of c.layouts.schemas) out.push(`  ${lit(s.schemaName)}: ${s.size},\n`)
  out.push('}\n\n')
  const TWO32 = '4294967296'
  for (const s of c.layouts.schemas) {
    const P = pascal(s.schemaName)
    const K = SHORT[s.schemaName] ?? constName(s.schemaName)
    out.push(`// ${s.schemaName} (${s.size} B): ${s.doc ?? ''}\n`)
    out.push(`export const ${K} = {\n  SIZE: ${s.size},\n`)
    for (const f of s.fields) out.push(`  ${upperSnake(f.n).replace(/^_+/, 'PAD_')}: ${f.o},\n`)
    out.push('} as const\n')
    const scales = s.fields.filter((f) => f.scale !== undefined)
    if (scales.length) out.push(`export const ${K}_SCALE = { ${scales.map((f) => `${f.n}: ${f.scale}`).join(', ')} } as const\n`)
    const nones = s.fields.filter((f) => f.none !== undefined)
    if (nones.length) out.push(`export const ${K}_NONE = { ${nones.map((f) => `${f.n}: ${f.none}`).join(', ')} } as const\n`)
    out.push(`export interface ${P}Rec {\n`)
    for (const f of s.fields) out.push(`  ${f.n}: ${(f.c ?? 1) > 1 ? 'number[]' : 'number'}\n`)
    out.push('}\n')
    out.push(`export function new${P}(): ${P}Rec {\n  return { ${s.fields.map((f) => `${f.n}: ${(f.c ?? 1) > 1 ? `new Array<number>(${f.c}).fill(0)` : '0'}`).join(', ')} }\n}\n`)
    // reader
    out.push(`export function read${P}(dv: DataView, off: number, out: ${P}Rec): ${P}Rec {\n`)
    for (const f of s.fields) {
      const c1 = f.c ?? 1
      const one = (o) => {
        if (f.t === 'i64') return `dv.getUint32(${o}, true) + dv.getInt32(${o} + 4, true) * ${TWO32}`
        if (f.t === 'u64') return `dv.getUint32(${o}, true) + dv.getUint32(${o} + 4, true) * ${TWO32}`
        return `dv.${DV_GET[f.t]}(${o}${TYPE_SIZE[f.t] > 1 ? ', true' : ''})`
      }
      if (c1 === 1) out.push(`  out.${f.n} = ${one(`off + ${f.o}`)}\n`)
      else if (c1 <= 4) {
        out.push(`  {\n    const a = out.${f.n}\n`)
        for (let i = 0; i < c1; i++) out.push(`    a[${i}] = ${one(`off + ${f.o + i * TYPE_SIZE[f.t]}`)}\n`)
        out.push('  }\n')
      } else {
        out.push(`  for (let i = 0; i < ${c1}; i++) out.${f.n}[i] = ${one(`off + ${f.o} + i * ${TYPE_SIZE[f.t]}`)}\n`)
      }
    }
    out.push('  return out\n}\n')
    // writer
    out.push(`export function write${P}(dv: DataView, off: number, v: ${P}Rec): void {\n`)
    for (const f of s.fields) {
      const c1 = f.c ?? 1
      const one = (o, x) => {
        if (f.t === 'i64' || f.t === 'u64') return `setI64(dv, ${o}, ${x})`
        return `dv.${DV_SET[f.t]}(${o}, ${x}${TYPE_SIZE[f.t] > 1 ? ', true' : ''})`
      }
      if (c1 === 1) out.push(`  ${one(`off + ${f.o}`, `v.${f.n}`)}\n`)
      else if (c1 <= 4) for (let i = 0; i < c1; i++) out.push(`  ${one(`off + ${f.o + i * TYPE_SIZE[f.t]}`, `v.${f.n}[${i}]`)}\n`)
      else out.push(`  for (let i = 0; i < ${c1}; i++) ${one(`off + ${f.o} + i * ${TYPE_SIZE[f.t]}`, `v.${f.n}[i]`)}\n`)
    }
    out.push('}\n\n')
  }
  out.push(`/** Write a 64-bit integer given as a JS number (exact for |x| < 2^53); unsigned and two's complement share the bytes. */
export function setI64(dv: DataView, off: number, x: number): void {
  const hi = Math.floor(x / ${TWO32})
  dv.setUint32(off, x - hi * ${TWO32}, true)
  dv.setInt32(off + 4, hi, true)
}

// ---- hot-path bit helpers (Full64 byte 2/3/7, Lite32 byte 2/30/31)
export const fsOf = (u8: Uint8Array, rec: number): number => u8[rec + 2] & 0x1f
export const subOf = (u8: Uint8Array, rec: number): number => u8[rec + 2] >>> 5
export const flagBit = (flags: number, bit: number): number => (flags >>> bit) & 1
export const ctrlOwner = (b: number): number => b & 7
export const ctrlLocked = (b: number): number => (b >>> 3) & 1
export const ctrlNative = (b: number): number => (b >>> 4) & 3
export const ctrlPose = (b: number): number => b >>> 6
export const packFs = (state: number, sub = 0): number => (state & 0x1f) | ((sub & 7) << 5)
export const packCtrl = (owner: number, locked: boolean | number, native: number, pose: number): number =>
  (owner & 7) | ((locked ? 1 : 0) << 3) | ((native & 3) << 4) | ((pose & 3) << 6)

/** Pre-allocated SoA filled by decodeSwarmLite32Into (rt.worker). */
export interface SwarmSoA {
  agentNo: Uint16Array
  fs: Uint8Array
  battery: Uint8Array
  pos: Float32Array
  quat: Float32Array
  vel: Float32Array
  flags: Uint8Array
  ctrl: Uint8Array
}
export function newSwarmSoA(capacity: number): SwarmSoA {
  return {
    agentNo: new Uint16Array(capacity), fs: new Uint8Array(capacity), battery: new Uint8Array(capacity),
    pos: new Float32Array(capacity * 3), quat: new Float32Array(capacity * 4), vel: new Float32Array(capacity * 3),
    flags: new Uint8Array(capacity), ctrl: new Uint8Array(capacity),
  }
}
let cachedBuf: ArrayBufferLike | null = null
let cachedF32: Float32Array<ArrayBufferLike> = new Float32Array(0)
let cachedI16: Int16Array<ArrayBufferLike> = new Int16Array(0)
let cachedU8: Uint8Array<ArrayBufferLike> = new Uint8Array(0)
function viewsFor(buf: ArrayBufferLike): void {
  if (buf === cachedBuf && cachedU8.byteLength === buf.byteLength) return
  cachedBuf = buf
  cachedF32 = new Float32Array(buf, 0, buf.byteLength >>> 2)
  cachedI16 = new Int16Array(buf, 0, buf.byteLength >>> 1)
  cachedU8 = new Uint8Array(buf, 0, buf.byteLength)
}
/** Decode n Lite32 rows at byte offset off (off % 4 == 0) into out; views are built once per receive buffer. */
export function decodeSwarmLite32Into(buf: ArrayBufferLike, off: number, n: number, out: SwarmSoA): number {
  viewsFor(buf)
  const f32 = cachedF32, i16 = cachedI16, u8 = cachedU8
  const qs = SL32_SCALE.q_snorm, vs = SL32_SCALE.vel_cms
  for (let k = 0; k < n; k++) {
    const b = off + 32 * k, f = b >>> 2, h = b >>> 1
    out.agentNo[k] = u8[b] | (u8[b + 1] << 8)
    out.fs[k] = u8[b + 2]
    out.battery[k] = u8[b + 3]
    out.pos[3 * k] = f32[f + 1]; out.pos[3 * k + 1] = f32[f + 2]; out.pos[3 * k + 2] = f32[f + 3]
    for (let j = 0; j < 4; j++) out.quat[4 * k + j] = i16[h + 8 + j] * qs
    for (let j = 0; j < 3; j++) out.vel[3 * k + j] = i16[h + 12 + j] * vs
    out.flags[k] = u8[b + 30]
    out.ctrl[k] = u8[b + 31]
  }
  return n
}
`)
  return out.join('')
}

// ---------------------------------------------------------------- frame.ts
function genFrame(c) {
  const S = Object.fromEntries(c.layouts.schemas.map((s) => [s.schemaName, s]))
  const constOf = (sn, n) => S[sn].fields.find((f) => f.n === n).const
  const bitsOf = (sn, n) => S[sn].fields.find((f) => f.n === n).bits
  const out = [BANNER, '// awr.rt.v1 BATCH and CLIENT_DATA helpers (AWR-17 §6.4). Out parameters, no per-call allocation.\n\n']
  out.push("import type { RtBatchHeaderRec } from './layouts.ts'\nimport { readRtBatchHeader, setI64 } from './layouts.ts'\n\n")
  out.push(`export const OP_TIME = 0x${constOf('awr.rt.Time.v1', 'op').toString(16).padStart(2, '0')}\n`)
  out.push(`export const OP_BATCH = 0x${constOf('awr.rt.BatchHeader.v1', 'op').toString(16).padStart(2, '0')}\n`)
  out.push(`export const OP_CLIENT_DATA = 0x${constOf('awr.rt.ClientDataHeader.v1', 'op').toString(16).padStart(2, '0')}\n`)
  for (const [bn, spec] of Object.entries(bitsOf('awr.rt.BatchHeader.v1', 'flags'))) out.push(`export const BATCH_${bn.toUpperCase()} = 0x${(1 << spec[0]).toString(16).padStart(2, '0')}\n`)
  for (const [bn, spec] of Object.entries(bitsOf('awr.rt.RecordHeader.v1', 'rflags'))) out.push(`export const RF_${bn.toUpperCase()} = 0x${(1 << spec[0]).toString(16).padStart(2, '0')}\n`)
  for (const [bn, spec] of Object.entries(bitsOf('awr.rt.ClientDataHeader.v1', 'flags'))) out.push(`export const CD_${bn.toUpperCase()} = 0x${(1 << spec[0]).toString(16).padStart(2, '0')}\n`)
  c.enums.Encoding.forEach((e, i) => out.push(`export const ENC_${e.toUpperCase()} = ${i}\n`))
  out.push(`
export const pad8 = (n: number): number => (n + 7) & ~7

/** Frame header; throws when the opcode is not BATCH. */
export function readFrameHeader(dv: DataView, out: RtBatchHeaderRec): RtBatchHeaderRec {
  readRtBatchHeader(dv, 0, out)
  if (out.op !== OP_BATCH) throw new Error('not a BATCH frame')
  return out
}

export interface RecordView {
  channel_id: number
  encoding: number
  rflags: number
  length: number
  seq: number
  dt_us: number
  payload_off: number
}
export const newRecordView = (): RecordView => ({ channel_id: 0, encoding: 0, rflags: 0, length: 0, seq: 0, dt_us: 0, payload_off: 0 })

/**
 * Read the record at off into out and return the offset of the next record, or -1 at the end of the frame.
 * Unknown encodings and reserved bits are returned as-is (callers skip them); truncation throws.
 */
export function nextRecord(dv: DataView, off: number, out: RecordView): number {
  if (off >= dv.byteLength) return -1
  if (off + 16 > dv.byteLength) throw new Error('truncated record header')
  out.channel_id = dv.getUint16(off, true)
  out.encoding = dv.getUint8(off + 2)
  out.rflags = dv.getUint8(off + 3)
  out.length = dv.getUint32(off + 4, true)
  out.seq = dv.getUint32(off + 8, true)
  out.dt_us = dv.getInt32(off + 12, true)
  out.payload_off = off + 16
  if (out.payload_off + out.length > dv.byteLength) throw new Error('truncated record payload')
  return out.payload_off + pad8(out.length)
}

/** CLIENT_DATA (C->S) frame with an awr.VelSetpoint16.v1 payload; dv must hold at least 32 bytes. */
export function writeClientData(dv: DataView, channelId: number, seq: number, tClientSimNs: number, flags: number,
  vx: number, vy: number, vz: number, yawRate: number): number {
  dv.setUint8(0, OP_CLIENT_DATA)
  dv.setUint8(1, flags)
  dv.setUint16(2, channelId, true)
  dv.setUint32(4, seq >>> 0, true)
  setI64(dv, 8, tClientSimNs)
  dv.setFloat32(16, vx, true)
  dv.setFloat32(20, vy, true)
  dv.setFloat32(24, vz, true)
  dv.setFloat32(28, yawRate, true)
  return 32
}

// ---------------------------------------------------------------- .awrrt protocol fixtures (AWR-16 §13.9)
export const AWRT_MAGIC = ${constOf('awr.fixture.AwrtHeader.v1', 'magic')}
export const AWRT_VERSION = ${constOf('awr.fixture.AwrtHeader.v1', 'version')}
export const AWRT_TIMED = 0x01
export const AWRT_S2C = 0
export const AWRT_C2S = 1
export const AWRT_TEXT = 0
export const AWRT_BINARY = 1

export interface AwrtRecord {
  dir: number
  kind: number
  /** relative monotonic time; fixtures stay far below 2^53 ns */
  t_rel_ns: number
  payload: Uint8Array
}
export interface Awrrt {
  flags: number
  t0_wall_ns: bigint
  header: Record<string, unknown>
  records: AwrtRecord[]
}

/** Parse a whole .awrrt file (test and FakeSource use only; allocates). Payloads are views into buf. */
export function readAwrrt(buf: ArrayBuffer | Uint8Array): Awrrt {
  const u8 = buf instanceof Uint8Array ? buf : new Uint8Array(buf)
  const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength)
  if (dv.getUint32(0, true) !== AWRT_MAGIC || dv.getUint16(4, true) !== AWRT_VERSION) throw new Error('not an .awrrt v1 file')
  const flags = dv.getUint16(6, true)
  const hlen = dv.getUint32(8, true)
  const t0 = dv.getBigUint64(16, true)
  const header = JSON.parse(new TextDecoder().decode(u8.subarray(24, 24 + hlen))) as Record<string, unknown>
  let off = 24 + pad8(hlen)
  const records: AwrtRecord[] = []
  while (off < u8.byteLength) {
    if (off + 16 > u8.byteLength) throw new Error('truncated .awrrt record header')
    const len = dv.getUint32(off + 4, true)
    const p = off + 16
    if (p + len > u8.byteLength) throw new Error('truncated .awrrt record payload')
    records.push({ dir: dv.getUint8(off), kind: dv.getUint8(off + 1), t_rel_ns: Number(dv.getBigUint64(off + 8, true)), payload: u8.subarray(p, p + len) })
    off = p + pad8(len)
  }
  return { flags, t0_wall_ns: t0, header, records }
}
`)
  return out.join('')
}

// ---------------------------------------------------------------- time.ts
function genTime(c) {
  const ts = c.enums.TimeState
  return BANNER + `// TIME frame (AWR-17 §6.4, §6.10): state low 4 bits TimeState, bit7 REPLAY. SimClockView advances only in PLAYING and LIVE.

import { setI64 } from './layouts.ts'

export const TIME_SIZE = 24
export const TIME_STATE_MASK = ${c.enums.TimeFlags.STATE_MASK}
export const TIME_REPLAY_BIT = ${c.enums.TimeFlags.REPLAY}
export const TIME_PLAYING = ${ts.indexOf('PLAYING')}
export const TIME_LIVE = ${ts.indexOf('LIVE')}

export interface TimeView {
  state: number
  replay: boolean
  epoch: number
  rate: number
  t_sim_ns: number
  t_srv_ns: number
}
export const newTimeView = (): TimeView => ({ state: 0, replay: false, epoch: 0, rate: 0, t_sim_ns: 0, t_srv_ns: 0 })

export const timeState = (stateByte: number): number => stateByte & TIME_STATE_MASK
export const isReplay = (stateByte: number): boolean => (stateByte & TIME_REPLAY_BIT) !== 0
/** True only for PLAYING and LIVE after masking bit7. */
export const advances = (stateByte: number): boolean => {
  const s = stateByte & TIME_STATE_MASK
  return s === TIME_PLAYING || s === TIME_LIVE
}

/** Decode a TIME frame at off; t_sim_ns and t_srv_ns are exact below 2^53 (lo + hi * 2^32). */
export function readTime(dv: DataView, off: number, out: TimeView): TimeView {
  if (dv.getUint8(off) !== 0x02) throw new Error('not a TIME frame')
  const b = dv.getUint8(off + 1)
  out.state = b & TIME_STATE_MASK
  out.replay = (b & TIME_REPLAY_BIT) !== 0
  out.epoch = dv.getUint16(off + 2, true)
  out.rate = dv.getFloat32(off + 4, true)
  out.t_sim_ns = dv.getUint32(off + 8, true) + dv.getInt32(off + 12, true) * 4294967296
  out.t_srv_ns = dv.getUint32(off + 16, true) + dv.getInt32(off + 20, true) * 4294967296
  return out
}

export function writeTime(dv: DataView, off: number, v: TimeView): void {
  dv.setUint8(off, 0x02)
  dv.setUint8(off + 1, (v.state & TIME_STATE_MASK) | (v.replay ? TIME_REPLAY_BIT : 0))
  dv.setUint16(off + 2, v.epoch & 0xffff, true)
  dv.setFloat32(off + 4, v.rate, true)
  setI64(dv, off + 8, v.t_sim_ns)
  setI64(dv, off + 16, v.t_srv_ns)
}
`
}

// ---------------------------------------------------------------- enums.ts
function genEnums(c) {
  const E = c.enums
  const out = [BANNER, '// Enumerations from packages/contracts/rt/enums.json (awr.enums.v1).\n\n']
  for (const [name, val] of Object.entries(E)) {
    if (!/^[A-Z]/.test(name) || !isSimpleEnum(val)) continue
    const m = enumMembers(val)
    out.push(`export const ${name} = { ${m.map(([id, v]) => `${id}: ${v}`).join(', ')} } as const\n`)
    out.push(`export type ${name} = (typeof ${name})[keyof typeof ${name}]\n`)
    out.push(`export const ${upperSnake(name)}_NAMES: Readonly<Record<number, string>> = { ${m.map(([, v, w]) => `${v}: ${lit(w)}`).join(', ')} }\n\n`)
  }
  out.push('/** FlightSub: 3-bit sub-mode names per FlightState (null = reserved slot). */\n')
  out.push('export const FLIGHT_SUB: ReadonlyArray<ReadonlyArray<string | null>> = [\n')
  for (const fs of E.FlightState) out.push(`  ${lit(E.FlightSub[fs])},\n`)
  out.push(']\n')
  out.push(`export const SEVERITY: Readonly<Record<number, number>> = { ${Object.entries(E.Severity).map(([k, v]) => `${E.FlightState.indexOf(k)}: ${v}`).join(', ')} }\n`)
  out.push(`export const JOB_STATE: Readonly<Record<string, readonly string[]>> = ${lit(E.JobState)}\n\n`)
  out.push(`export const subName = (fs: number, sub: number): string | null => FLIGHT_SUB[fs]?.[sub] ?? null
export const subValue = (fs: number, name: string): number => FLIGHT_SUB[fs].indexOf(name)
/** Swarm-wide red highlight: CORRECTING <= fs <= CRASHED and fs != LANDED, or ALERT (g04 §5.4). */
export const redHighlight = (fs: number, flags: number): boolean =>
  (fs >= FlightState.CORRECTING && fs <= FlightState.CRASHED && fs !== FlightState.LANDED) || (flags & FlightFlags.ALERT) !== 0
`)
  return out.join('')
}

// ---------------------------------------------------------------- reasons.ts
function genReasons(c) {
  const R = c.reasons
  const out = [BANNER, '// Reason codes from packages/contracts/rt/reasons.json (AWR-17 §8).\n\n']
  out.push('export interface ReasonInfo {\n  code: number\n  name: string\n  http: number | null\n  category: string\n  step: string | null\n  message_zh: string\n  remedy_zh: string\n  d1: string\n}\n\n')
  out.push('export const Reason = {\n')
  for (const r of R.reasons) out.push(`  ${r.name}: ${r.code},\n`)
  out.push('} as const\nexport type Reason = (typeof Reason)[keyof typeof Reason]\n\n')
  out.push('export const REASONS: Readonly<Record<number, ReasonInfo>> = {\n')
  for (const r of R.reasons) out.push(`  ${r.code}: { code: ${r.code}, name: ${lit(r.name)}, http: ${lit(r.http)}, category: ${lit(r.category)}, step: ${lit(r.step)}, message_zh: ${lit(r.message_zh)}, remedy_zh: ${lit(r.remedy_zh)}, d1: ${lit(r.d1)} },\n`)
  out.push('}\n\n')
  out.push(`export const WS_CLOSE = { ${R.ws_close_codes.map((w) => `${w.name}: ${w.code}`).join(', ')} } as const\n`)
  out.push(`export const REASON_WARNINGS: readonly string[] = ${lit(R.warnings)}\n`)
  return out.join('')
}

// ---------------------------------------------------------------- commands.ts
function genCommands(c) {
  const C = c.commands
  const cols = C.admission_columns
  const out = [BANNER, '// Command services, argument schemas and admission matrix from packages/contracts/rt/commands.json (AWR-17 §7.1; AWR-12 §5.2).\n\n']
  out.push(`export const ADMISSION_COLUMNS: readonly string[] = ${lit(cols.map((x) => x.id))}\n`)
  out.push(`export const ADMISSION_SYMBOL_CODE: Readonly<Record<string, number>> = ${lit(Object.fromEntries(Object.entries(C.admission_symbols).map(([k, v]) => [k, v.code])))}\n`)
  out.push(`export const ADMISSION_CONDITION_ELSE: Readonly<Record<string, string>> = ${lit(Object.fromEntries(Object.entries(C.admission_conditions).map(([k, v]) => [k, v.else])))}\n\n`)
  out.push('export interface Service {\n  name: string\n  op: string\n  category: string\n  lease: boolean | string | null\n  agent: string\n  d1: string\n  batchable: boolean\n  aliases: readonly string[]\n  argsSchema: Readonly<Record<string, unknown>>\n  admission: readonly string[] | null\n  admissionCond: Readonly<Record<string, string>>\n}\n\n')
  out.push('export const SERVICES: readonly Service[] = [\n')
  for (const s of C.services) {
    const adm = s.admission ? lit(cols.map((x) => s.admission[x.id])) : 'null'
    out.push(`  { name: ${lit(s.name)}, op: ${lit(s.op)}, category: ${lit(s.category)}, lease: ${lit(s.lease)}, agent: ${lit(s.agent)}, d1: ${lit(s.d1)}, batchable: ${lit(!!s.batchable)}, aliases: ${lit(s.aliases ?? [])},\n    argsSchema: ${lit(s.args_schema)},\n    admission: ${adm}, admissionCond: ${lit(s.admission_cond ?? {})} },\n`)
  }
  out.push(']\n\n')
  out.push(`const escapeRe = (s: string): string => s.replace(/[.*+?^$()|[\\]\\\\]/g, '\\\\$&')
const toRe = (name: string): RegExp => new RegExp('^' + escapeRe(name).replace(/\\{(\\w+)\\}/g, '(?<$1>[a-z0-9][a-z0-9_-]*)') + '$')
const PATTERNS: ReadonlyArray<readonly [RegExp, Service]> = [
  ...SERVICES.map((s) => [toRe(s.name), s] as const),
  ...SERVICES.flatMap((s) => s.aliases.map((a) => [toRe(a), s] as const)),
]
export const SERVICE_BY_OP: Readonly<Record<string, Service>> = Object.fromEntries(SERVICES.map((s) => [s.op, s]))

/** Resolve a WS service name to its Service and path parameters, or null. */
export function matchService(name: string): { service: Service; params: Record<string, string> } | null {
  for (const [re, s] of PATTERNS) {
    const m = re.exec(name)
    if (m) return { service: s, params: { ...(m.groups ?? {}) } }
  }
  return null
}

const COL_OF_FS: readonly number[] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 13, 14, 15]
/** Admission column: RTL (8) and LANDING (9) split by flags.FAILSAFE (bit3) into operator and automatic columns. */
export function admissionColumn(fs: number, flags: number): number {
  const auto = (flags & 8) !== 0
  if (fs === 8) return auto ? 9 : 8
  if (fs === 9) return auto ? 11 : 10
  return COL_OF_FS[fs]
}
/** [symbol, condition id or null]; symbols Y, =, S, - (AWR-12 §5.2). */
export function admitSymbol(op: string, fs: number, flags: number): readonly [string, string | null] {
  const s = SERVICE_BY_OP[op]
  if (!s?.admission) throw new Error(op + ' has no admission row')
  const col = admissionColumn(fs, flags)
  return [s.admission[col], s.admissionCond[ADMISSION_COLUMNS[col]] ?? null]
}
`)
  return out.join('')
}

// ---------------------------------------------------------------- topics.ts, units.ts, safetyCodes.ts, presets.ts
function genTopics(c) {
  const T = c.topics
  const out = [BANNER, '// Topic table from packages/contracts/rt/topics.json (AWR-17 §6.6).\n\n']
  out.push(`export const RATE_CLASSES: readonly number[] = ${lit(T.rate_classes)}\nexport const TICK_HZ = ${T.tick_hz}\n\n`)
  out.push('export interface TopicInfo {\n  pattern: string\n  kind: string\n  encoding: string\n  schemaName: string\n  nativeHz: number\n  defaultRate: Readonly<Record<string, number>> | null\n  mode: string | null\n  priority: number | null\n  selfContained: boolean\n  owner: string\n  d1: string\n  aliases: readonly string[]\n}\n\n')
  out.push('export const TOPICS: readonly TopicInfo[] = [\n')
  for (const t of T.topics) out.push(`  { pattern: ${lit(t.pattern)}, kind: ${lit(t.kind)}, encoding: ${lit(t.encoding)}, schemaName: ${lit(t.schemaName)}, nativeHz: ${t.native_hz}, defaultRate: ${lit(t.default_rate)}, mode: ${lit(t.mode)}, priority: ${lit(t.priority)}, selfContained: ${lit(t.self_contained)}, owner: ${lit(t.owner)}, d1: ${lit(t.d1)}, aliases: ${lit(t.aliases ?? [])} },\n`)
  out.push(']\n\n')
  out.push(`const CHUNK = new RegExp(${lit(T.chunk_pattern)})
const TOPIC_RE: ReadonlyArray<readonly [RegExp, TopicInfo]> = TOPICS.map((t) => [
  new RegExp('^' + t.pattern.replace(/[.*+?^$()|[\\]\\\\]/g, '\\\\$&').replace(/\\{\\w+\\}/g, '[a-z0-9][a-z0-9_-]*') + '$'), t] as const)

export function matchTopic(topic: string): TopicInfo | null {
  for (const [re, t] of TOPIC_RE) if (re.test(topic) || t.aliases.includes(topic)) return t
  return null
}
/** Round up to the nearest rate class; 0 = native rate capped by the tick (AWR-17 §6.7). */
export function quantizeRate(rate: number): number {
  if (rate <= 0) return TICK_HZ
  for (const r of RATE_CLASSES) if (r >= rate) return r
  return RATE_CLASSES[RATE_CLASSES.length - 1]
}
export function validTopic(topic: string, allowWildcards = false): boolean {
  return topic.split('/').every((p) => CHUNK.test(p) || (allowWildcards && (p === '*' || p === '**')))
}
`)
  return out.join('')
}

function genUnits(c) {
  const U = c.units
  return BANNER + '// Unit suffix dictionary from packages/contracts/rt/units.json (AWR-03 §5.4).\n\n'
    + `export const UNIT_SUFFIXES: Readonly<Record<string, readonly [string, string]>> = {\n${Object.entries(U.suffixes).map(([k, v]) => `  ${lit(k)}: [${lit(v.unit)}, ${lit(v.quantity)}],\n`).join('')}}\n`
    + `export const UNIT_DENIED_SUFFIXES: Readonly<Record<string, string>> = ${lit(U.denied_suffixes ?? {})}\n`
    + `export const UNIT_DENIED_NAMES: Readonly<Record<string, string>> = ${lit(U.denied_names ?? {})}\n`
}

function genSafety(c) {
  const out = [BANNER, '// SafetyEvent catalogue from packages/contracts/rt/safety_codes.json (M09 §6.13).\n\n']
  out.push('export interface SafetyCodeInfo {\n  code: string\n  type: string\n  cls: string\n  level: number\n  fsm: string | null\n  ui: string\n  icon: string\n  mergeKey: string | null\n  d1: string\n}\n\n')
  out.push('export const SAFETY_CODES: Readonly<Record<string, SafetyCodeInfo>> = {\n')
  for (const s of c.safety.codes) out.push(`  ${lit(s.code)}: { code: ${lit(s.code)}, type: ${lit(s.type)}, cls: ${lit(s.cls)}, level: ${s.level}, fsm: ${lit(s.fsm)}, ui: ${lit(s.ui)}, icon: ${lit(s.icon)}, mergeKey: ${lit(s.merge_key)}, d1: ${lit(s.d1)} },\n`)
  out.push('}\n')
  return out.join('')
}

function genPresets(c) {
  const P = JSON.parse(c.presetsText)
  const out = [BANNER, '// Environment presets: verbatim text of packages/contracts/env/presets.json, its sha256 and EnvScalars indices (M07 §6.2.1).\n\n']
  out.push("import type { Presets } from './types.ts'\n\n")
  out.push(`export const PRESETS_JSON = ${lit(c.presetsText)}\n`)
  out.push(`export const PRESETS_SHA256 = ${lit(sha256(c.presetsText).toString('hex'))}\n`)
  out.push('export const PRESETS = JSON.parse(PRESETS_JSON) as Presets\n\n')
  P.fields.forEach((f, i) => out.push(`export const F_${f.path.replace('.', '_').toUpperCase()} = ${i}\n`))
  out.push(`export const NF = ${P.fields.length}\n`)
  out.push(`export const FIELD_PATHS: readonly string[] = ${lit(P.fields.map((f) => f.path))}\n`)
  out.push(`export const PRESET_IDS: readonly string[] = ${lit(P.presets.map((p) => p.id))}\n`)
  return out.join('')
}

// ---------------------------------------------------------------- types.ts via json-schema-to-typescript over one bundle
function schemaFiles() {
  const out = []
  const walk = (d) => {
    for (const f of fs.readdirSync(d).sort()) {
      const p = path.join(d, f)
      const rel = path.relative(CONTRACTS, p)
      if (fs.statSync(p).isDirectory()) {
        if (!['gen', 'fixtures', 'golden'].includes(rel.split(path.sep)[0])) walk(p)
      } else if (f.endsWith('.schema.json')) out.push(p)
    }
  }
  walk(CONTRACTS)
  return out
}

function bundleSchemas() {
  const docs = new Map()
  for (const p of schemaFiles()) {
    const d = JSON.parse(fs.readFileSync(p, 'utf8'))
    docs.set(d.$id, { p, d })
  }
  const pas = (s) => s.split(/[-_./@ $]+/).filter(Boolean).map((w) => w[0].toUpperCase() + w.slice(1)).join('')
  const base = new Map()
  const used = new Set()
  for (const [id, { p }] of [...docs.entries()].sort()) {
    const dom = id.split('/')[3]
    let b = pas(path.basename(p, '.schema.json'))
    if (used.has(b) || ['Command', 'Event', 'Detail', 'Common'].includes(b)) b = pas(dom) + b
    used.add(b)
    base.set(id, b)
  }
  const defs = {}
  const nameOf = (id, frag) => {
    const segs = frag.split('/').filter((s) => s && s !== '$defs')
    return base.get(id) + segs.map(pas).join('')
  }
  const resolveId = (from, ref) => {
    const [b, frag = ''] = ref.split('#')
    if (!b) return [from, frag]
    const parts = from.split('/').slice(0, -1)
    for (const seg of b.split('/')) {
      if (seg === '..') parts.pop()
      else if (seg && seg !== '.') parts.push(seg)
    }
    return [parts.join('/'), frag]
  }
  const pending = []
  const hoist = (id, frag) => {
    const n = nameOf(id, frag)
    if (!(n in defs)) {
      defs[n] = null
      pending.push([id, frag, n])
    }
    return n
  }
  const nodeAt = (id, frag) => {
    let d = docs.get(id).d
    for (const seg of frag.split('/').filter(Boolean)) d = d[seg.replace(/~1/g, '/').replace(/~0/g, '~')]
    return d
  }
  const rewrite = (id, node) => {
    if (Array.isArray(node)) return node.map((x) => rewrite(id, x))
    if (!node || typeof node !== 'object') return node
    const out = {}
    for (const [k, v] of Object.entries(node)) {
      if (k === '$ref') {
        const [tid, frag] = resolveId(id, v)
        out.$ref = '#/definitions/' + hoist(tid, frag)
      } else if (k === '$defs' || k === '$id' || k === '$schema' || k === 'if' || k === 'then' || k === 'else' || k === 'not') {
        continue
      } else if (k === 'prefixItems') {
        continue
      } else out[k] = rewrite(id, v)
    }
    return out
  }
  for (const id of [...docs.keys()].sort()) {
    hoist(id, '')
    for (const k of Object.keys(docs.get(id).d.$defs ?? {})) hoist(id, '/$defs/' + k)
  }
  while (pending.length) {
    const [id, frag, n] = pending.shift()
    const node = rewrite(id, nodeAt(id, frag))
    const title = node.title
    node.title = n
    if (title) node.description = title + (node.description ? '. ' + node.description : '')
    defs[n] = node
  }
  const sorted = Object.fromEntries(Object.keys(defs).sort().map((k) => [k, defs[k]]))
  return { $schema: 'http://json-schema.org/draft-07/schema#', title: 'AwrContracts', type: 'object', additionalProperties: false, properties: {}, definitions: sorted }
}

async function genTypes() {
  const { compile } = await import(path.join(ROOT, 'node_modules', 'json-schema-to-typescript', 'dist', 'src', 'index.js'))
  const ts = await compile(bundleSchemas(), 'AwrContracts', {
    bannerComment: BANNER.trim() + '\n// Types for every JSON Schema under packages/contracts (json-schema-to-typescript 16, one bundled schema).',
    additionalProperties: false,
    unreachableDefinitions: true,
    declareExternallyReferenced: true,
    maxItems: -1,
    format: true,
    strictIndexSignatures: false,
    style: { semi: false, singleQuote: true, printWidth: 140 },
  })
  return ts
}

function genIndex() {
  return BANNER + `// @awr/contracts entry point (AWR-17 §10.4). apps/web/src/net/rt/layouts.ts re-exports from here.

export * from './layouts.ts'
export * from './frame.ts'
export * from './time.ts'
export * from './enums.ts'
export * from './reasons.ts'
export * from './commands.ts'
export * from './topics.ts'
export * from './units.ts'
export * from './presets.ts'
export * from './safetyCodes.ts'
export type * as types from './types.ts'
`
}

// ---------------------------------------------------------------- main
async function main() {
  const check = process.argv.includes('--check')
  const layouts = readJson('rt/layouts.json')
  const enums = readJson('rt/enums.json')
  const errs = checkLayouts(layouts, enums)
  if (errs.length) {
    console.error('contract error: ' + errs.join('; '))
    process.exit(2)
  }
  const c = {
    version: readJson('package.json').version,
    layouts, enums,
    commands: readJson('rt/commands.json'),
    reasons: readJson('rt/reasons.json'),
    topics: readJson('rt/topics.json'),
    units: readJson('rt/units.json'),
    safety: readJson('rt/safety_codes.json'),
    presetsText: fs.readFileSync(path.join(CONTRACTS, 'env', 'presets.json'), 'utf8'),
    layoutId: layoutId(layouts),
    schemaHash: Object.fromEntries(layouts.schemas.map((s) => [s.schemaName, schemaHash(s)])),
  }
  const files = {
    'index.ts': genIndex(),
    'layouts.ts': genLayouts(c),
    'frame.ts': genFrame(c),
    'time.ts': genTime(c),
    'enums.ts': genEnums(c),
    'reasons.ts': genReasons(c),
    'commands.ts': genCommands(c),
    'topics.ts': genTopics(c),
    'units.ts': genUnits(c),
    'presets.ts': genPresets(c),
    'safetyCodes.ts': genSafety(c),
    'types.ts': await genTypes(),
  }
  let diffs = 0
  for (const [name, text] of Object.entries(files).sort()) {
    const p = path.join(OUT, name)
    const cur = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null
    if (cur !== text) {
      diffs++
      if (check) console.log(`out of date: ${path.relative(ROOT, p)}`)
      else {
        fs.mkdirSync(OUT, { recursive: true })
        fs.writeFileSync(p, text)
        console.log(`wrote ${path.relative(ROOT, p)}`)
      }
    }
  }
  for (const f of fs.existsSync(OUT) ? fs.readdirSync(OUT).sort() : []) {
    if (!(f in files)) {
      diffs++
      if (check) console.log(`unexpected file (not generated): ${path.relative(ROOT, path.join(OUT, f))}`)
      else {
        fs.rmSync(path.join(OUT, f))
        console.log(`removed stale ${f}`)
      }
    }
  }
  if (check && diffs) {
    console.error(`gen.mjs --check: ${diffs} file(s) differ; run node tools/contracts/gen.mjs`)
    process.exit(1)
  }
  console.log(`gen.mjs: ${diffs ? `${diffs} file(s) updated` : 'up to date'} (layout_id 0x${c.layoutId.toString(16).toUpperCase().padStart(8, '0')}, contracts ${c.version})`)
}

await main()
