#!/usr/bin/env python3
"""生成 `apps/web/src/engine/sensors/specs.gen.ts`（M13-FR-001、FR-022；M13 §6.4.3）。

浏览器端的传感器参数与 sim-core 同源：本脚本对 `vehicles/*/params.yaml` 中声明了 `sensors:` 的每个机型目录调用
`awr.sim.sensors.describe.describe_model()`（与 `GET /api/fleet/profiles/{id}` 的 `sensors{}` 同一函数），把有视场与云台的
字段写成 TS 常量。`--check` 只比较不写入（tests/sensors/test_web_specs.py 调用）。
用法：.venv/bin/python tests/sensors/gen_web_specs.py [--check]
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "python"))

from awr.sim.sensors.describe import describe_model  # noqa: E402
from awr.sim.sensors.enums import SensorKind  # noqa: E402

OUT = ROOT / "apps" / "web" / "src" / "engine" / "sensors" / "specs.gen.ts"
KIND_CODE = {k.name.lower(): int(k) for k in SensorKind}


def entry(d: dict) -> dict:
    it = d.get("intrinsics")
    g = d.get("gimbal")
    R = d["mount"]["R"]
    t = d["mount"]["xyz_m"]
    mount = [R[0][0], R[0][1], R[0][2], t[0], R[1][0], R[1][1], R[1][2], t[1], R[2][0], R[2][1], R[2][2], t[2], 0, 0, 0, 1]
    e = {"name": d["name"], "kind": d["kind"], "kindCode": KIND_CODE[d["kind"]], "sensorNo": d["sensor_no"],
         "w": it["w"] if it else 0, "h": it["h"] if it else 0, "fx": it["fx"] if it else 0, "fy": it["fy"] if it else 0,
         "cx": it["cx"] if it else 0, "cy": it["cy"] if it else 0,
         "hfov": d.get("hfov_rad"), "vfov": d.get("vfov_rad"), "rangeM": d.get("range_m"), "rateHz": d.get("rate_hz"),
         "mount": mount, "conf": d.get("conf"),
         "gimbal": None if g is None else {k: g[k] for k in ("yaw_min_deg", "yaw_max_deg", "pitch_min_deg", "pitch_max_deg",
                                                              "rate_max_deg_s", "default_mode", "default_yaw_deg",
                                                              "default_pitch_deg")},
         "capability": (d.get("detector") or {}).get("capability")}
    return e


def render() -> str:
    models: dict[str, list[dict]] = {}
    for p in sorted((ROOT / "vehicles").glob("*/params.yaml")):
        doc = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
        if not doc.get("sensors"):
            continue
        d = describe_model(p.parent)
        models[p.parent.name] = [entry(d[r["name"]]) for r in d["rig"]]
    body = json.dumps(models, ensure_ascii=False, indent=2, sort_keys=True)
    return (
        "// Generated by tests/sensors/gen_web_specs.py from vehicles/*/sensors/*.yaml (M13-FR-001, FR-022). Do not edit.\n"
        "// Same values as GET /api/fleet/profiles/{id} sensors{} (awr.sim.sensors.describe); mount is the row-major\n"
        "// T_base_mount, angles of fov in rad, gimbal limits in degrees; keyed by the vehicle directory (roster `model`).\n"
        "export interface SensorSpecGimbal {\n"
        "  default_mode: string\n  default_pitch_deg: number\n  default_yaw_deg: number\n  pitch_max_deg: number\n"
        "  pitch_min_deg: number\n  rate_max_deg_s: number\n  yaw_max_deg: number\n  yaw_min_deg: number\n}\n"
        "export interface SensorSpecJson {\n"
        "  name: string\n  kind: string\n  kindCode: number\n  sensorNo: number\n  w: number\n  h: number\n  fx: number\n"
        "  fy: number\n  cx: number\n  cy: number\n  hfov: number | null\n  vfov: number | null\n  rangeM: number | null\n"
        "  rateHz: number | null\n  mount: number[]\n  conf: string | null\n  gimbal: SensorSpecGimbal | null\n"
        "  capability: string | null\n}\n"
        f"export const SENSOR_SPECS: Record<string, readonly SensorSpecJson[]> = {body}\n"
    )


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        cur = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if cur != text:
            print(f"{OUT.relative_to(ROOT)} is out of date: run tests/sensors/gen_web_specs.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
