// GENERATED by tools/shadcn/icons/gen-registry.mjs from tools/shadcn/icons/inventory.mjs. DO NOT EDIT.

// Custom stroke icons on the 24 grid (AWR-15 §7.8; d03 §4.1).
import type { IconNode } from './types'

export const PointCloud: IconNode = [['path',{'d':'M3 7V5a2 2 0 0 1 2-2h2'}],['path',{'d':'M17 3h2a2 2 0 0 1 2 2v2'}],['path',{'d':'M21 17v2a2 2 0 0 1-2 2h-2'}],['path',{'d':'M7 21H5a2 2 0 0 1-2-2v-2'}],['circle',{'cx':'8','cy':'10','r':'1'}],['circle',{'cx':'12','cy':'8','r':'1'}],['circle',{'cx':'16','cy':'11','r':'1'}],['circle',{'cx':'10','cy':'15','r':'1'}],['circle',{'cx':'15','cy':'16','r':'1'}]]
export const SandDust: IconNode = [['path',{'d':'M2 8h9'}],['path',{'d':'M2 12h13'}],['path',{'d':'M2 16h8'}],['circle',{'cx':'15','cy':'7','r':'1'}],['circle',{'cx':'20','cy':'9','r':'1'}],['circle',{'cx':'19','cy':'14','r':'1'}],['circle',{'cx':'13','cy':'17','r':'1'}],['circle',{'cx':'20','cy':'19','r':'1'}]]
export const OctreeLod: IconNode = [['rect',{'x':'3','y':'3','width':'18','height':'18','rx':'2'}],['path',{'d':'M12 3v18'}],['path',{'d':'M3 12h18'}],['path',{'d':'M16.5 3v9'}],['path',{'d':'M12 7.5h9'}]]
export const DroneHexa: IconNode = [['circle',{'cx':'12','cy':'12','r':'2'}],['path',{'d':'M12 10V7'}],['path',{'d':'M13.73 11l2.6-1.5'}],['path',{'d':'M13.73 13l2.6 1.5'}],['path',{'d':'M12 14v3'}],['path',{'d':'M10.27 13l-2.6 1.5'}],['path',{'d':'M10.27 11l-2.6-1.5'}],['circle',{'cx':'12','cy':'4.5','r':'2.5'}],['circle',{'cx':'18.5','cy':'8.25','r':'2.5'}],['circle',{'cx':'18.5','cy':'15.75','r':'2.5'}],['circle',{'cx':'12','cy':'19.5','r':'2.5'}],['circle',{'cx':'5.5','cy':'15.75','r':'2.5'}],['circle',{'cx':'5.5','cy':'8.25','r':'2.5'}]]
export const Formation: IconNode = [['circle',{'cx':'12','cy':'5','r':'2.5'}],['circle',{'cx':'5','cy':'18','r':'2.5'}],['circle',{'cx':'19','cy':'18','r':'2.5'}],['path',{'d':'M10.8 7.2 6.2 15.8'}],['path',{'d':'M13.2 7.2l4.6 8.6'}],['path',{'d':'M7.5 18h9'}]]
export const CameraFrustum: IconNode = [['circle',{'cx':'5','cy':'12','r':'2'}],['path',{'d':'M7 11 19 5'}],['path',{'d':'M7 13l12 6'}],['path',{'d':'M19 5v14'}]]
