// GENERATED by tools/shadcn/icons/gen-registry.mjs from tools/shadcn/icons/inventory.mjs. DO NOT EDIT.

// Morph whitelist (M15-FR-062; d03 §4.2): only pairs that pass the four admission rules (same object, <= 2 subpath
// difference or same family, max residual <= 0.5 or pure rotation, contact sheet) are registered; every other change
// is a swap (transitions.dev 09). Rerun tools/shadcn/icons/verify.mjs and the contact sheet after a lucide upgrade.
import { BatteryFull, BatteryLow, BatteryMedium, BatteryWarning, Bot, BotOff, Check, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, ChevronsDownUp, ChevronsUpDown, CircleCheck, CirclePause, CirclePlay, Cloud, CloudFog, CloudRain, CloudSun, Copy, FastForward, Haze, LoaderCircle, Locate, LocateFixed, Lock, LockOpen, Maximize, Menu, Minimize, Moon, OctagonAlert, PanelBottomClose, PanelBottomOpen, PanelLeftClose, PanelLeftOpen, PanelRightClose, PanelRightOpen, Pause, PlaneLanding, PlaneTakeoff, Play, Plus, Power, PowerOff, Repeat, Repeat1, Rewind, ShieldAlert, ShieldCheck, SignalHigh, SignalLow, SignalMedium, SignalZero, Square, Sun, Sunrise, Sunset, TriangleAlert, Wifi, WifiOff, X } from 'lucide'
import type { IconNode } from './types'

export type SpringName = 'snappy' | 'smooth' | 'hud'

/** [from, to, default spring, registering key]; morph is allowed in both directions */
export const MORPH_PAIRS: readonly (readonly [IconNode, IconNode, SpringName, string])[] = [
  [Menu, X, 'snappy', 'nav.menu'],
  [PanelLeftClose, PanelLeftOpen, 'snappy', 'panel.left'],
  [PanelRightClose, PanelRightOpen, 'snappy', 'panel.right'],
  [PanelBottomClose, PanelBottomOpen, 'snappy', 'panel.bottom'],
  [Sun, Moon, 'smooth', 'theme.light'],
  [Maximize, Minimize, 'snappy', 'view.fullscreen'],
  [Wifi, WifiOff, 'snappy', 'conn.online'],
  [Lock, LockOpen, 'snappy', 'layer.lock'],
  [LoaderCircle, CircleCheck, 'smooth', 'layer.loading'],
  [Sun, CloudSun, 'smooth', 'env.clear'],
  [CloudSun, Cloud, 'smooth', 'env.partly'],
  [Cloud, CloudRain, 'smooth', 'env.cloud'],
  [CloudRain, CloudFog, 'smooth', 'env.rain'],
  [CloudFog, Haze, 'smooth', 'env.fog'],
  [Sunrise, Sunset, 'smooth', 'env.sunrise'],
  [PlaneTakeoff, PlaneLanding, 'snappy', 'drone.takeoff'],
  [ShieldCheck, ShieldAlert, 'smooth', 'drone.armed'],
  [Power, PowerOff, 'snappy', 'drone.power'],
  [BatteryFull, BatteryMedium, 'hud', 'bat.full'],
  [BatteryMedium, BatteryLow, 'hud', 'bat.medium'],
  [BatteryLow, BatteryWarning, 'hud', 'bat.low'],
  [SignalHigh, SignalMedium, 'hud', 'link.high'],
  [SignalMedium, SignalLow, 'hud', 'link.medium'],
  [SignalLow, SignalZero, 'hud', 'link.low'],
  [CirclePause, CirclePlay, 'snappy', 'mission.paused'],
  [Play, Square, 'snappy', 'mission.start'],
  [Play, Pause, 'snappy', 'tl.play'],
  [Rewind, FastForward, 'snappy', 'tl.rewind'],
  [Repeat, Repeat1, 'snappy', 'tl.loop'],
  [Locate, LocateFixed, 'snappy', 'cam.follow'],
  [TriangleAlert, OctagonAlert, 'smooth', 'alert.warning'],
  [Bot, BotOff, 'snappy', 'agent'],
  [ChevronDown, ChevronUp, 'snappy', 'chev.down'],
  [ChevronLeft, ChevronRight, 'snappy', 'chev.left'],
  [ChevronRight, ChevronDown, 'snappy', 'chev.right'],
  [ChevronsUpDown, ChevronsDownUp, 'snappy', 'chev.updown'],
  [Check, X, 'snappy', 'check'],
  [Plus, X, 'snappy', 'plus'],
  [Copy, Check, 'snappy', 'copy'],
]

const OK = new Map<IconNode, Map<IconNode, SpringName>>()
for (const [a, b, s] of MORPH_PAIRS) {
  if (!OK.has(a)) OK.set(a, new Map())
  if (!OK.has(b)) OK.set(b, new Map())
  OK.get(a)!.set(b, s)
  OK.get(b)!.set(a, s)
}

/** default spring of a whitelisted pair, or null when the change must be a swap */
export function morphSpring(from: IconNode, to: IconNode): SpringName | null {
  return OK.get(from)?.get(to) ?? null
}
