// Generated by tests/sensors/gen_web_specs.py from vehicles/*/sensors/*.yaml (M13-FR-001, FR-022). Do not edit.
// Same values as GET /api/fleet/profiles/{id} sensors{} (awr.sim.sensors.describe); mount is the row-major
// T_base_mount, angles of fov in rad, gimbal limits in degrees; keyed by the vehicle directory (roster `model`).
export interface SensorSpecGimbal {
  default_mode: string
  default_pitch_deg: number
  default_yaw_deg: number
  pitch_max_deg: number
  pitch_min_deg: number
  rate_max_deg_s: number
  yaw_max_deg: number
  yaw_min_deg: number
}
export interface SensorSpecJson {
  name: string
  kind: string
  kindCode: number
  sensorNo: number
  w: number
  h: number
  fx: number
  fy: number
  cx: number
  cy: number
  hfov: number | null
  vfov: number | null
  rangeM: number | null
  rateHz: number | null
  mount: number[]
  conf: string | null
  gimbal: SensorSpecGimbal | null
  capability: string | null
}
export const SENSOR_SPECS: Record<string, readonly SensorSpecJson[]> = {
  "p600": [
    {
      "capability": "rgb.zoom",
      "conf": "D",
      "cx": 3000.0,
      "cy": 2000.0,
      "fx": 5196.152,
      "fy": 5196.152,
      "gimbal": {
        "default_mode": "fixed",
        "default_pitch_deg": -15.0,
        "default_yaw_deg": 0.0,
        "pitch_max_deg": 30.0,
        "pitch_min_deg": -90.0,
        "rate_max_deg_s": 90.0,
        "yaw_max_deg": 150.0,
        "yaw_min_deg": -150.0
      },
      "h": 4000,
      "hfov": 1.047197622,
      "kind": "camera",
      "kindCode": 0,
      "mount": [
        1.0,
        0.0,
        0.0,
        0.12,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        -0.08,
        0,
        0,
        0,
        1
      ],
      "name": "camera",
      "rangeM": 300.0,
      "rateHz": 30.0,
      "sensorNo": 0,
      "vfov": 0.734843864,
      "w": 6000
    },
    {
      "capability": "thermal.imaging",
      "conf": "D",
      "cx": 320.0,
      "cy": 256.0,
      "fx": 686.3,
      "fy": 686.3,
      "gimbal": {
        "default_mode": "fixed",
        "default_pitch_deg": -15.0,
        "default_yaw_deg": 0.0,
        "pitch_max_deg": 30.0,
        "pitch_min_deg": -90.0,
        "rate_max_deg_s": 90.0,
        "yaw_max_deg": 150.0,
        "yaw_min_deg": -150.0
      },
      "h": 512,
      "hfov": 0.872600125,
      "kind": "thermal",
      "kindCode": 2,
      "mount": [
        1.0,
        0.0,
        0.0,
        0.12,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        -0.08,
        0,
        0,
        0,
        1
      ],
      "name": "thermal",
      "rangeM": 400.0,
      "rateHz": 30.0,
      "sensorNo": 1,
      "vfov": 0.714058026,
      "w": 640
    },
    {
      "capability": null,
      "conf": "C",
      "cx": 0,
      "cy": 0,
      "fx": 0,
      "fy": 0,
      "gimbal": null,
      "h": 0,
      "hfov": 6.283185307,
      "kind": "lidar",
      "kindCode": 1,
      "mount": [
        0.939692620786,
        0.0,
        0.342020143326,
        0.13,
        0.0,
        1.0,
        0.0,
        0.0,
        -0.342020143326,
        0.0,
        0.939692620786,
        0.28,
        0,
        0,
        0,
        1
      ],
      "name": "mid360",
      "rangeM": 70.0,
      "rateHz": 10.0,
      "sensorNo": 2,
      "vfov": 1.036725576,
      "w": 0
    },
    {
      "capability": null,
      "conf": "D",
      "cx": 0,
      "cy": 0,
      "fx": 0,
      "fy": 0,
      "gimbal": null,
      "h": 0,
      "hfov": null,
      "kind": "gnss",
      "kindCode": 4,
      "mount": [
        1.0,
        0.0,
        0.0,
        -0.1,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.2,
        0,
        0,
        0,
        1
      ],
      "name": "gnss",
      "rangeM": null,
      "rateHz": 10.0,
      "sensorNo": 3,
      "vfov": null,
      "w": 0
    },
    {
      "capability": null,
      "conf": "C",
      "cx": 0,
      "cy": 0,
      "fx": 0,
      "fy": 0,
      "gimbal": null,
      "h": 0,
      "hfov": null,
      "kind": "imu",
      "kindCode": 5,
      "mount": [
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0,
        0,
        0,
        1
      ],
      "name": "imu",
      "rangeM": null,
      "rateHz": 200.0,
      "sensorNo": 4,
      "vfov": null,
      "w": 0
    }
  ],
  "x500": [
    {
      "capability": "rgb.zoom",
      "conf": "D",
      "cx": 3000.0,
      "cy": 2000.0,
      "fx": 5196.152,
      "fy": 5196.152,
      "gimbal": {
        "default_mode": "fixed",
        "default_pitch_deg": -15.0,
        "default_yaw_deg": 0.0,
        "pitch_max_deg": 30.0,
        "pitch_min_deg": -90.0,
        "rate_max_deg_s": 90.0,
        "yaw_max_deg": 150.0,
        "yaw_min_deg": -150.0
      },
      "h": 4000,
      "hfov": 1.047197622,
      "kind": "camera",
      "kindCode": 0,
      "mount": [
        1.0,
        0.0,
        0.0,
        0.12,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        -0.08,
        0,
        0,
        0,
        1
      ],
      "name": "camera",
      "rangeM": 300.0,
      "rateHz": 30.0,
      "sensorNo": 0,
      "vfov": 0.734843864,
      "w": 6000
    }
  ]
}
